### ISSUE TITLE
ValueError: Unsupported type: episodes after upgrade

### ISSUE THREAD

**Issue by JacquelineHyde** [Taxel/PlexTraktSync#1106]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

Worked perfectly before upgrading to 0.22.2. Now ValueError when scanning a library with TV shows. (Movies works perfectly.)

### Error trace / logs

```text
2022-10-16T23:51:35.671194745Z Traceback (most recent call last):
2022-10-16T23:51:35.671375586Z   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2022-10-16T23:51:35.671442462Z     return _run_code(code, main_globals, None,
2022-10-16T23:51:35.671494576Z   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
2022-10-16T23:51:35.671542127Z     exec(code, run_globals)
2022-10-16T23:51:35.671587105Z   File "/app/plextraktsync/__main__.py", line 18, in <module>
2022-10-16T23:51:35.671635315Z     cli()
2022-10-16T23:51:35.671675968Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
2022-10-16T23:51:35.671731916Z     return self.main(*args, **kwargs)
2022-10-16T23:51:35.671776845Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
2022-10-16T23:51:35.671827837Z     rv = self.invoke(ctx)
2022-10-16T23:51:35.671871775Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
2022-10-16T23:51:35.671926693Z     rv = super().invoke(ctx)
2022-10-16T23:51:35.671971861Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
2022-10-16T23:51:35.672020264Z     return ctx.invoke(self.callback, **ctx.params)
2022-10-16T23:51:35.672064755Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
2022-10-16T23:51:35.672143202Z     return __callback(*args, **kwargs)
2022-10-16T23:51:35.672190930Z   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
2022-10-16T23:51:35.672243040Z     return f(get_current_context(), *args, **kwargs)
2022-10-16T23:51:35.672292944Z   File "/app/plextraktsync/cli.py", line 46, in cli
2022-10-16T23:51:35.672341286Z     sync()
2022-10-16T23:51:35.672382073Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
2022-10-16T23:51:35.672432419Z     return self.main(*args, **kwargs)
2022-10-16T23:51:35.672474393Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
2022-10-16T23:51:35.672523013Z     rv = self.invoke(ctx)
2022-10-16T23:51:35.672564018Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
2022-10-16T23:51:35.672610765Z     return ctx.invoke(self.callback, **ctx.params)
2022-10-16T23:51:35.672654291Z   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
2022-10-16T23:51:35.672700672Z     return __callback(*args, **kwargs)
2022-10-16T23:51:35.672749872Z   File "/app/plextraktsync/cli.py", line 28, in wrap
2022-10-16T23:51:35.672796801Z     cmd(*args, **kwargs)
2022-10-16T23:51:35.672840847Z   File "/app/plextraktsync/commands/sync.py", line 58, in sync
2022-10-16T23:51:35.672888099Z     runner.sync(walker=w, dry_run=config.dry_run)
2022-10-16T23:51:35.672934000Z   File "/app/plextraktsync/sync.py", line 96, in sync
2022-10-16T23:51:35.672983007Z     self.sync_ratings(episode, dry_run=dry_run)
2022-10-16T23:51:35.673031059Z   File "/app/plextraktsync/sync.py", line 133, in sync_ratings
2022-10-16T23:51:35.673099697Z     if m.plex_rating is m.trakt_rating:
2022-10-16T23:51:35.673148315Z   File "/app/plextraktsync/media.py", line 149, in trakt_rating
2022-10-16T23:51:35.673199881Z     return self.trakt_api.rating(self.trakt)
2022-10-16T23:51:35.673246229Z   File "/app/plextraktsync/trakt_api.py", line 226, in rating
2022-10-16T23:51:35.673291342Z     raise ValueError(f"Unsupported type: {m.media_type}")
2022-10-16T23:51:35.673340449Z ValueError: Unsupported type: episodes
```

### Expected behavior

Parse and operation of TV library.

### Steps to reproduce the behavior

 pipx upgrade plextraktsync
plextraktsync

### Install method

pipx (Recommended)

### Version

0.22.2

### Python Version

3.8.12

### Operating System and Version

Linux 4.4.180+ x86_64

**Comment by glensc** [comment]
> Worked perfectly before upgrading to 0.22.2

Please indicate what was the version before, would help to find the commit that broke.

**Comment by kimpenhaus** [comment]
@glensc I am running into the same issue with the latest docker image. previous version is hard to tell - I am updating the docker image automated with watchtower and after release 0.22.2 (which came yesterday: 10-16-2022)  it was the first time I had that issue. My assumption when looking at the stack trace is, that it might be introduced by
 - [Use trakt_api.rating in Media class](https://github.com/Taxel/PlexTraktSync/commit/4c16f016fd8e324df8720e1b493bf6cb1214bc67)

together with
 - [Always fetch ratings via api](https://github.com/Taxel/PlexTraktSync/commit/e214aa9bf0d2ecb9ccac6f0bae7716d5c9fa4c03)

but that's just a wild guess - sorry for couldn't being more precise...

**Comment by glensc** [comment]
Log file logs version on startup:

```
2022-10-17 23:15:21,850 INFO[PlexTraktSync]:PlexTraktSync [0.22.0dev0: 387b38a6: Print event state in watch on_play @2
022-10-17 23:12:12]
```
