### ISSUE TITLE
sync throws missing argument error

### ISSUE THREAD

**Issue by marksie1988** [Taxel/PlexTraktSync#1130]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

When running `plextraktsync sync` the error below is displayed

```shell
TypeError: <lambda>() missing 1 required positional argument: 'type'
```

### Error trace / logs

```text
INFO     PlexTraktSync [0.23.3]
INFO     Sync Movie sections: [<PlexLibrarySection:movie:Films>]
INFO     Sync Show sections: [<PlexLibrarySection:show:TV programmes>]
INFO     Downloaded List Fast and Furious Chronology
INFO     Downloaded List The Matrix Franchise
INFO     Downloaded List The Bourne Identity Series
Traceback (most recent call last):
  File "/root/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/commands/sync.py", line 57, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/sync.py", line 83, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/trakt/core.py", line 561, in inner
    return generator.send(json_data)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: <lambda>() missing 1 required positional argument: 'type'
```

### Expected behavior

Sync should complete without error

### Steps to reproduce the behavior

1. run `plextraktsync sync` 

### Install method

pipx (Recommended)

### Version

0.23.3

### Python Version

3.9.2

### Operating System and Version

Debian 11 (bullseye)

**Comment by glensc** [comment]
@marksie1988 off topic, but you probably should not run this app as `root` user!

**Comment by twolaw** [comment]
Does `plextraktsync self-update` also update dependences ?
@marksie1988  be sure you have `trakt` version 3.4.7

**Comment by glensc** [comment]
@twolaw yes, it installs new venv. here problem is different, data does not have the `type`, previously problem was that the class did not support `type` parameter.

**Comment by twolaw** [comment]
Trakt lists are cached, try to remove cache file.

Readme states :

> After that, movie details and Trakt lists are cached, so it should run a lot quicker the second time. This does mean, however, that Trakt lists are not updated dynamically (which is fine for lists like "2018 Academy Award Nominees" but might not be ideal for lists that are updated often).

**Comment by marksie1988** [comment]
Seems removing the cache fixed this👍 thanks for the help guys.

**Comment by marksie1988** [comment]
Maybe worth adding something to the self-update that clears caches?

**Comment by glensc** [comment]
self-update and cache have nothing to do with each other.

**Comment by marksie1988** [comment]
Well they do really, if an update causes the cache to no longer be valid and raise and error as it did for me... Then the cache should be cleared.

If the update had cleared the cache in this scenario I would have seen no error and would have saved any troubleshooting.

**Comment by glensc** [comment]
No, they don't. The update to structures was from trakt.tv site.
