### ISSUE TITLE
ModuleNotFoundError: No module named 'pytrakt'

### ISSUE THREAD

**Issue by samcro1967** [Taxel/PlexTraktSync#1145]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

Started seeing this error a few days ago.  The last successful run from what I can tell was on 10/20/2022.  It runs as a scheduled task so I just noticed today that it was generating an error trying to run.

### Error trace / logs

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/plextraktsync/cli.py", line 53, in cli
    sync()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/cli.py", line 24, in wrap
    module = importlib.import_module(f".commands.{name}", package=__package__)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/plextraktsync/commands/sync.py", line 5, in <module>
    from plextraktsync.commands.login import ensure_login
  File "/app/plextraktsync/commands/login.py", line 5, in <module>
    from plextraktsync.commands.trakt_login import (has_trakt_token,
  File "/app/plextraktsync/commands/trakt_login.py", line 10, in <module>
    from plextraktsync.trakt_api import TraktApi
  File "/app/plextraktsync/trakt_api.py", line 21, in <module>
    from plextraktsync.decorators.retry import retry
  File "/app/plextraktsync/decorators/retry.py", line 9, in <module>
    from pytrakt.trakt.errors import BadResponseException
ModuleNotFoundError: No module named 'pytrakt'
```
```


### Expected behavior

Container runs without an error.

### Steps to reproduce the behavior

1.  docker run --rm --name=plextraktsync -v /home/user/Documents/Docker/plextraktsync:/app/config ghcr.io/taxel/plextraktsync:latest

### Inspect of problematic items

```text
N/A
```

### Workarounds

No known at this time

### Install method

docker-compose

### Version

taxel/plextraktsync:latest

### Python Version

taxel/plextraktsync:latest

### Operating System and Version

Ubuntu 20.04

**Comment by glensc** [comment]
`taxel/plextraktsync:latest` that is not a version! don't cheat!

This is already fixed in 0.23.2

**Comment by glensc** [comment]
> Workarounds
>
> No known at this time

nonsense! there's always a way to downgrade!

**Comment by glensc** [comment]
```
✖  docker inspect ghcr.io/taxel/plextraktsync:latest -f '{{ index .Config.Labels "org.opencontainers.image.version"}}'
0.21.2
```

- https://stackoverflow.com/a/33884893/2314626

**Comment by glensc** [comment]
```
➜ docker run --rm ghcr.io/taxel/plextraktsync:latest --version
PlexTraktSync 0.23.4
```
