### ISSUE TITLE
AttributeError: 'Media' object has no attribute 'show'

### ISSUE THREAD

**Issue by floppy86** [Taxel/PlexTraktSync#1151]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

i just run plextraktsync sync --show "All of Us Are Dead"
and I get 

Traceback (most recent call last):
  File "/home/media/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/media/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/media/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/media/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/media/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/media/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/media/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/home/media/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/commands/sync.py", line 57, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/media/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/sync.py", line 101, in sync
    shows.add(episode.show)
AttributeError: 'Media' object has no attribute 'show'

### Expected behavior

no error is thrown

### Steps to reproduce the behavior

run plextraktsync sync --show "All of Us Are Dead"

### Workarounds

Downgrade to version 0.23.4

### Install method

pipx (Recommended)

### Version

0.23.5

### Python Version

 3.10.6

### Operating System and Version

Ubuntu 20.04 server

**Comment by caffeineflo** [comment]
Same issue here on multiple TV Shows, tried changing the scanners with no luck

**Comment by floppy86** [comment]
Hi, thank you for the comment, I can confirm that older version 0.23.4 works

**Comment by twolaw** [comment]
attribute `show` has been removed by mistake, it will be back with #1152
