### ISSUE TITLE
ImportError: cannot import name 'BadResponseException' from 'trakt.errors'

### ISSUE THREAD

**Issue by solid-pixel** [Taxel/PlexTraktSync#1154]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

Hello, thanks for pushing so many updates, you guys are doing a great job.

It seems like every 0.23.x version is throwing this error for me whenever I run `plextraktsync.sh`. 
0.22.4 is the last one to work flawlessly.

Also I'm not sure if it's the expected behavior, but running `plextraktsync.sh --version` shows `0.23.0dev0` instead of `0.23.7`:

```console
mrrobot@polaris:/home1/mrrobot/custom/PlexTraktSync$ git describe --tags
0.23.7
mrrobot@polaris:/home1/mrrobot/custom/PlexTraktSync$ ./plextraktsync.sh --version
PlexTraktSync 0.23.0dev0: e7ec3755: Bring back media.show property mistakenly removed in 1eaf574 (#1152) @2022-10-29 12:19:38
```

Running `plextraktsync.sh info` or any other argument also throws the error showed below.

### Error trace / logs

```console
mrrobot@polaris:/home1/mrrobot/custom/PlexTraktSync$ ./plextraktsync.sh
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home1/mrrobot/custom/PlexTraktSync/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home1/mrrobot/custom/PlexTraktSync/plextraktsync/cli.py", line 53, in cli
    sync()
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mrrobot/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home1/mrrobot/custom/PlexTraktSync/plextraktsync/cli.py", line 24, in wrap
    module = importlib.import_module(f".commands.{name}", package=__package__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home1/mrrobot/custom/PlexTraktSync/plextraktsync/commands/sync.py", line 5, in <module>
    from plextraktsync.commands.login import ensure_login
  File "/home1/mrrobot/custom/PlexTraktSync/plextraktsync/commands/login.py", line 5, in <module>
    from plextraktsync.commands.trakt_login import (has_trakt_token,
  File "/home1/mrrobot/custom/PlexTraktSync/plextraktsync/commands/trakt_login.py", line 10, in <module>
    from plextraktsync.trakt_api import TraktApi
  File "/home1/mrrobot/custom/PlexTraktSync/plextraktsync/trakt_api.py", line 21, in <module>
    from plextraktsync.decorators.retry import retry
  File "/home1/mrrobot/custom/PlexTraktSync/plextraktsync/decorators/retry.py", line 6, in <module>
    from trakt.errors import BadResponseException, TraktInternalException
ImportError: cannot import name 'BadResponseException' from 'trakt.errors' (/home/mrrobot/.local/lib/python3.7/site-packages/trakt/errors.py)
```

### Expected behavior

The script should run

### Steps to reproduce the behavior

1. `git checkout tags/0.23.7` (but also any other tag from 0.23.0 onwards)
2. `./plextraktsync.sh`
3. Error

### Workarounds

Downgrading to 0.22.4 works well

### Install method

git clone

### Version

0.23.7

### Python Version

Python 3.7.3

### Operating System and Version

Debian 10

**Comment by twolaw** [comment]
_git clone_  is not a recommended and not supported install method.
Have you really read Readme.md file?

**Comment by glensc** [comment]
duplicate https://github.com/Taxel/PlexTraktSync/issues/1144
