### ISSUE TITLE
Python Errors with latest release

### ISSUE THREAD

**Issue by jeremehancock** [Taxel/PlexTraktSync#1214]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I am getting this error running via Docker. If I downgrade to 0.23.14 things work just fine.

```
INFO     PlexTraktSync [0.24.0]                                                                         
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 39, in sync
    w = factory.walker()
        ^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/factory.py", line 125, in walker
    plex = self.plex_api()
           ^^^^^^^^^^^^^^^
  File "/app/plextraktsync/factory.py", line 19, in plex_api
    server = self.plex_server()
             ^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/factory.py", line 38, in plex_server
    server = self.server_config()
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/factory.py", line 56, in server_config
    server_config.load()
  File "/app/plextraktsync/config/ServerConfig.py", line 29, in load
    defaults = loader.load(default_servers_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/config/ConfigLoader.py", line 5, in load
    return cls.load_yaml(path)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/config/ConfigLoader.py", line 45, in load_yaml
    with open(path, "r", encoding="utf-8") as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/app/plextraktsync/servers.default.yml'
```

### Expected behavior

Should work as before :)

### Steps to reproduce the behavior

Run docker compose up with latest version

### Install method

docker-compose

### Version

0.24

### Python Version

3.10.8

### Operating System and Version

Ubuntu

**Comment by jrhbcn** [comment]
same here.

**Comment by AD1995** [comment]
Also getting this issue. I'm running in docker and have tried to recreate the container with an empty config directory as if it's a fresh install and am still have the same issue

**Comment by jeremehancock** [comment]
@AD1995 

I updated to the latest and now it is working again for me.

**Comment by AD1995** [comment]
> @AD1995
> 
> I updated to the latest and now it is working again for me.

Figured out my issue. I'd restored an old docker compose file from a backup recently and I'd been using the LinuxServer Labs image instead of the one in the example docker compose. Changed to that docker image and it's working now. 
User error strikes again!
