### ISSUE TITLE
Throwing exception while syncing

### ISSUE THREAD

**Issue by alessandrocaputo13** [Taxel/PlexTraktSync#130]
While running the script it crashes throwing the below exception. It actually syncs some movies before crashing. Any clues on what could be the cause? Thanks.

```
Processing section Movies
Traceback (most recent call last):
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='192-168-1-12.e8ec2a133f7345d68fa9d336dcbd162d.plex.direct', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 405, in <module>
    main()
  File "main.py", line 383, in main
    process_movie_section(
  File "main.py", line 40, in process_movie_section
    if len(movie.guids) > 0:
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\plexapi\base.py", line 396, in __getattribute__
    self.reload()
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\plexapi\base.py", line 279, in reload
    data = self._server.query(key)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\plexapi\server.py", line 496, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\aleca\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='192-168-1-12.e8ec2a133f7345d68fa9d336dcbd162d.plex.direct', port=32400): Read timed out. (read timeout=30)
```

**Comment by glensc** [comment]
> `requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='192-168-112.e8ec2a133f7345d68fa9d336dcbd162d.plex.direct', port=32400): Read timed out. (read timeout=30)`

30-second timeout too small, your Plex too slow or became unavailable. And it's not a crash, it's abort.

**Comment by alessandrocaputo13** [comment]
Okay, got it. Is it possible to increase the timeout?

**Comment by glensc** [comment]
@alessandrocaputo13 I think Plex got overloaded after it got to process 1800+ movies. However this script caches some requests, so retry and I hope it will go away eventually. You can also have look on PlexServer logs, maybe there's something interesting. The 30s should be for one request.

**Comment by glensc** [comment]
Don't know about 'new tv scanner' problem, please open a new bug report. one problem, one bug report.
