### ISSUE TITLE
PlexTraktSync crashes on initial setup: InquirerPy.exceptions.InvalidArgument: rawlist argument choices cannot exceed length of 9

### ISSUE THREAD

**Issue by BRAYDIN72** [Taxel/PlexTraktSync#1397]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Both on docker and windows druting the initial setup , right after log in it crashes.

### Error trace / logs

```text
╭─ Plex Login ───────────────────╮
│                                │
│ Login to MyPlex was successful │
│                                │
╰────────────────────────────────╯

Select default server: 1Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main26 01:59:59, Server: Plexamp/4.6.1 on iOS: iOS/16.2
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code8.1.36:32500
    exec(code, run_globals)K+: Last seen: 2023-01-25 23:32:56, Server: Plex for Roku/7.0.24.8154-127760991-Plex on Roku
  File "C:\PlexTraktSync-0.25.14\plextraktsync\__main__.py", line 18, in <module>
    cli() TV Cube: Last seen: 2023-01-25 22:46:07, Server: Plex for Android (TV)/9.14.0.37895 on AFTA: Android/7.1.2
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__ Media Server/1.30.2.6563-3d4dc0cce on Docker Containe
    return self.main(*args, **kwargs)1089403e95df6d33f8971e72.plex.direct:32400
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main2.plex.direct:8443
    rv = self.invoke(ctx)t seen: 2023-01-25 16:56:27, Server: Plex for Roku/7.0.24.8154-127760991-Plex on 65S421: Roku/
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1635, in invoke/8.13 on iPad: iOS/16.2
    rv = super().invoke(ctx)32500
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invokelex.direct:32400
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\PlexTraktSync-0.25.14\plextraktsync\cli.py", line 69, in cli
    sync()
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\PlexTraktSync-0.25.14\plextraktsync\cli.py", line 25, in wrap
    cmd(*args, **kwargs)
  File "C:\PlexTraktSync-0.25.14\plextraktsync\commands\sync.py", line 49, in sync
    ensure_login()
  File "C:\PlexTraktSync-0.25.14\plextraktsync\commands\login.py", line 12, in ensure_login
    plex_login_autoconfig()
  File "C:\PlexTraktSync-0.25.14\plextraktsync\commands\plex_login.py", line 192, in plex_login_autoconfig
    login(username, password)
  File "C:\PlexTraktSync-0.25.14\plextraktsync\commands\plex_login.py", line 208, in login
    [server, plex] = choose_server(account)
  File "C:\PlexTraktSync-0.25.14\plextraktsync\commands\plex_login.py", line 168, in choose_server
    server = pick_server(account)
  File "C:\PlexTraktSync-0.25.14\plextraktsync\commands\plex_login.py", line 155, in pick_server
    server_name = prompt_server(servers)
  File "C:\PlexTraktSync-0.25.14\plextraktsync\commands\plex_login.py", line 144, in prompt_server
    ).execute()
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\InquirerPy\base\simple.py", line 330, in execute
    result = self._run()
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\InquirerPy\base\complex.py", line 208, in _run
    return self.application.run()
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\application\application.py", line 978, in run
    return loop.run_until_complete(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\application\application.py", line 885, in run_async
    return await _run_async(f)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\application\application.py", line 743, in _run_async
    self._redraw()
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\application\application.py", line 557, in _redraw
    self.context.copy().run(run_in_context)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\application\application.py", line 545, in run_in_context
    self.after_render.fire()
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\utils.py", line 83, in fire
    self()
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\utils.py", line 79, in __call__
    handler(self.sender)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\InquirerPy\base\complex.py", line 165, in _after_render
    self._on_rendered(app)
  File "C:\Users\brayd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\InquirerPy\prompts\rawlist.py", line 269, in _on_rendered
    raise InvalidArgument("rawlist argument choices cannot exceed length of 9")
InquirerPy.exceptions.InvalidArgument: rawlist argument choices cannot exceed length of 9
```

### Expected behavior

At this point I should see a server selection screen, 

### Steps to reproduce the behavior

1. Install docker container
2. run for first time
3. log in to plex
4. crash
5. repeat thinking you will get a different result
6. download windows source code on desktop PC
7. run setup
8. login to plex
9. crash

### Install method

Unraid installation (not supported)

### Version

0.25.14

### Python Version

3.10

### Operating System and Version

Windows 11 and Unraid 6.11.5

**Comment by BRAYDIN72** [comment]
I understand neither docker or windows are supported but figured I would post this anyway, That being said I had it working on windows about 5 days ago. I didn't install the docker version until yesterday. I tried the windows version again after the docker failed and it wanted to work, but I changed servers (going from my desktop to a separate machine running unraid) so it hung trying to connect to the now non existent server. I ran setup again and then got the same error as on docker.

**Comment by glensc** [comment]
If you read the error, your server list was over 9 items in plex login screen?

> `InquirerPy.exceptions.InvalidArgument: rawlist argument choices cannot exceed length of 9`

**Comment by glensc** [comment]
> > Workarounds
> No response

you have checked that you have tested downgrade, so the workaround is to use that older version. what version this worked?

**Comment by BRAYDIN72** [comment]
Thank you! That worked. Looking at the raw list of "servers" it included not only my server but my phone, TV, roku, my old server, a test env copy of my new server that I blanked out before moving the server into production. To say the least, it was a mess. Anyway removing the restriction let me select a server! All I can say is WOW! that was quick of you guys.
