### ISSUE TITLE
Sync crashes on my raspberry pi setup

### ISSUE THREAD

**Issue by unicornsandcandies** [Taxel/PlexTraktSync#1408]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Script doesn't seem to work on my raspberry pi setup with python 3.9. It's giving me a bunch of errors that I've pasted below (I've censored my ip and port because I felt weird leaving it, even though it's local)

### Error trace / logs

```text
Traceback (most recent call last):
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(censored): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dietpi/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/cli.py", line 25, in wrap
    cmd(*args, **kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/commands/sync.py", line 73, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/sync.py", line 67, in sync
    self.sync_ratings(movie, dry_run=dry_run)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/sync.py", line 146, in sync_ratings
    logger.info(f"Rating '{m.title}' with {m.trakt_rating} on Plex")
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/media.py", line 49, in title
    return self.plex.title
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/plex/PlexLibraryItem.py", line 104, in title
    if self.type == "movie" and self.item.editionTitle:
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plexapi/base.py", line 503, in __getattribute__
    self._reload(_overwriteNone=False)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plexapi/base.py", line 377, in _reload
    data = self._server.query(key)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/requests_cache/session.py", line 103, in get
    return self.request('GET', url, params=params, **kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/requests_cache/session.py", line 159, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/requests_cache/session.py", line 206, in send
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/requests_cache/session.py", line 230, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/dietpi/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(censored): Read timed out. (read timeout=30)
```

### Expected behavior

Sync works without errors

### Steps to reproduce the behavior

1. Install with pix
2. Run with "sync" argument
3. Wait

### Install method

pipx

### Version

0.25.15

### Python Version

3.9

### Operating System and Version

dietpi

**Comment by glensc** [comment]
no way related to python version or distro. it can't connect to plex, try plex-login subcommand to log in again

**Comment by unicornsandcandies** [comment]
> no way related to python version or distro. it can't connect to plex, try plex-login subcommand to log in again. check that the ip and port in error message connect with telnet or netcat program

I did it and nothing's changed

**Comment by glensc** [comment]
did what? show your telnet or netcat or ping. your plextraktsync installation can't connect to the plex server. that is what your error is about. basic networking problem here.

**Comment by glensc** [comment]
closing stale issue
