### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by FloydKulis** [Taxel/PlexTraktSync#16]
I have a problem with the installation.
Unfortunately, during the first step I have problems:

```
[~] # pip3 /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt
ERROR: unknown command "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt"
[~] # pip3 install -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt
Collecting astroid==2.3.2
  Downloading astroid-2.3.2-py3-none-any.whl (205 kB)
     |████████████████████████████████| 205 kB 1.1 MB/s
Collecting certifi==2019.9.11
  Downloading certifi-2019.9.11-py2.py3-none-any.whl (154 kB)
     |████████████████████████████████| 154 kB 205 kB/s
Requirement already satisfied: chardet==3.0.4 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: idna==2.8 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt (line 4)) (2.8)
Collecting isort==4.3.21
  Downloading isort-4.3.21-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.5 MB/s
Requirement already satisfied: lazy-object-proxy==1.4.2 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt (line 6)) (1.4.2)
Collecting mccabe==0.6.1
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: oauthlib==3.1.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt (line 8)) (3.1.0)
Collecting PlexAPI==3.2.0
  Downloading PlexAPI-3.2.0.tar.gz (73 kB)
     |████████████████████████████████| 73 kB 3.0 MB/s
Collecting pylint==2.4.3
  Downloading pylint-2.4.3-py3-none-any.whl (302 kB)
     |████████████████████████████████| 302 kB 1.7 MB/s
Collecting python-dotenv==0.10.3
  Downloading python_dotenv-0.10.3-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: requests==2.22.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt (line 12)) (2.22.0)
Requirement already satisfied: requests-cache==0.5.2 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt (line 13)) (0.5.2)
Collecting requests-oauthlib==1.2.0
  Downloading requests_oauthlib-1.2.0-py2.py3-none-any.whl (22 kB)
Requirement already satisfied: six==1.12.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt (line 15)) (1.12.0)
Collecting tqdm==4.36.1
  Downloading tqdm-4.36.1-py2.py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 1.8 MB/s
Collecting trakt==2.11.0
  Downloading trakt-2.11.0.tar.gz (31 kB)
Collecting typed-ast==1.4.0
  Downloading typed_ast-1.4.0.tar.gz (206 kB)
     |████████████████████████████████| 206 kB 1.7 MB/s
Collecting urllib3==1.25.6
  Downloading urllib3-1.25.6-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 1.7 MB/s
Collecting websocket-client==0.56.0
  Downloading websocket_client-0.56.0-py2.py3-none-any.whl (200 kB)
     |████████████████████████████████| 200 kB 3.0 MB/s
Requirement already satisfied: wrapt==1.11.2 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from -r /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/PlexTraktSync-master/requirements.txt (line 21)) (1.11.2)
Installing collected packages: typed-ast, astroid, certifi, isort, mccabe, tqdm, websocket-client, PlexAPI, pylint, python-dotenv, requests-oauthlib, trakt, urllib3
    Running setup.py install for typed-ast ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-h89e36at/typed-ast/setup.py'"'"'; __file__='"'"'/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-h89e36at/typed-ast/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-record-3ya_66qz/install-record.txt --single-version-externally-managed --compile --install-headers /opt/include/python3.7/typed-ast
         cwd: /share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-h89e36at/typed-ast/
    Complete output (25 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/typed_ast
    copying typed_ast/__init__.py -> build/lib.linux-x86_64-3.7/typed_ast
    copying typed_ast/ast27.py -> build/lib.linux-x86_64-3.7/typed_ast
    copying typed_ast/ast3.py -> build/lib.linux-x86_64-3.7/typed_ast
    copying typed_ast/conversions.py -> build/lib.linux-x86_64-3.7/typed_ast
    package init file 'ast3/tests/__init__.py' not found (or not a regular file)
    creating build/lib.linux-x86_64-3.7/typed_ast/tests
    copying ast3/tests/test_basics.py -> build/lib.linux-x86_64-3.7/typed_ast/tests
    warning: build_py: byte-compiling is disabled, skipping.

    running build_ext
    building '_ast27' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/ast27
    creating build/temp.linux-x86_64-3.7/ast27/Parser
    creating build/temp.linux-x86_64-3.7/ast27/Python
    creating build/temp.linux-x86_64-3.7/ast27/Custom
    x86_64-openwrt-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -pipe -fomit-frame-pointer -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -O2 -pipe -fomit-frame-pointer -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -DNDEBUG -fno-inline -O2 -pipe -fomit-frame-pointer -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -DNDEBUG -fno-inline -I/media/ware/Entware.2019.10/staging_dir/target-x86_64_glibc-2.27/opt/include -I/media/ware/Entware.2019.10/staging_dir/toolchain-x86_64_gcc-7.4.0_glibc-2.27/include -fPIC -Iast27/Include -I/opt/include/python3.7 -c ast27/Parser/acceler.c -o build/temp.linux-x86_64-3.7/ast27/Parser/acceler.o
    unable to execute 'x86_64-openwrt-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-openwrt-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-h89e36at/typed-ast/setup.py'"'"'; __file__='"'"'/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-h89e36at/typed-ast/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-record-3ya_66qz/install-record.txt --single-version-externally-managed --compile --install-headers /opt/include/python3.7/typed-ast Check the logs for full command output.
[~] # pip instal urllib3
ERROR: unknown command "instal" - maybe you meant "install"
[~] # pip install urllib3
Requirement already satisfied: urllib3 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (1.25.8)
[~] # pip install websocket-client
Requirement already satisfied: websocket-client in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (0.57.0)
Requirement already satisfied: six in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from websocket-client) (1.12.0)
[~] # pip install pip
Requirement already satisfied: pip in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (20.0.2)
[~] # pip install wrapt
Requirement already satisfied: wrapt in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (1.11.2)
[~] #
```

**Comment by Vaxter** [comment]
You don't have to run this on QNAP in order to sync.
Run it on your machine and target Plex on QNAP with it.
Finish the entire setup on your local machine and after that just change base_url in config.json to point QNAPs local network or public address.

**Comment by FloydKulis** [comment]
@Vaxter 
I did as you said. The package was successfully installed on Windows 10.
now the error appears when trying to run main.py:
C:\Users\floyd>python C:\Python\PlexTraktSync-master\main.py
Traceback (most recent call last):
  File "C:\Python\PlexTraktSync-master\main.py", line 20, in <module>
    from config import CONFIG
  File "C:\Python\PlexTraktSync-master\config.py", line 3, in <module>
    with open('config.json', 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

My file:
{
    "base_url": "http://192.168.50.123:32400",
    "log_debug_messages": false,
    "sync": {
        "liked_lists": true,
        "watchlist": true,
        "watched_status": true,
        "collection": true,
        "ratings": true
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    }
}
