### ISSUE TITLE
TypeError: UserList.__new__() got an unexpected keyword argument 'share_link'

### ISSUE THREAD

**Issue by nick-harper** [Taxel/PlexTraktSync#1779]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

When trying to sync I get the following:

INFO: Downloaded List Trakt Watchlist
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 16, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 111, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 69, in sync
    listutil.addList(lst['username'], lst['listname'])
  File "/app/plextraktsync/trakt_list_util.py", line 80, in addList
    self.lists.append(TraktList(username, listname))
  File "/app/plextraktsync/trakt_list_util.py", line 45, in __init__
    prelist = [(elem[0], elem[1]) for elem in LazyUserList._get(listname, username)._items if elem[0] in ["movies", "episodes"]]
  File "/usr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/app/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: UserList.__new__() got an unexpected keyword argument 'share_link'

### Steps to reproduce the behavior

Just running:

docker-compose run --rm plextraktsync sync

### Error trace / logs

```text
INFO: Downloaded List Trakt Watchlist
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 16, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 111, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 69, in sync
    listutil.addList(lst['username'], lst['listname'])
  File "/app/plextraktsync/trakt_list_util.py", line 80, in addList
    self.lists.append(TraktList(username, listname))
  File "/app/plextraktsync/trakt_list_util.py", line 45, in __init__
    prelist = [(elem[0], elem[1]) for elem in LazyUserList._get(listname, username)._items if elem[0] in ["movies", "episodes"]]
  File "/usr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/app/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: UserList.__new__() got an unexpected keyword argument 'share_link'
```

### Expected behavior

It should sync?

### Install method

docker-compose

### Config file contents

```yaml
{
    "log_debug_messages": true,
    "logging": {
        "append": false
    },
    "cache": {
        "path": "$PTS_CACHE_DIR/trakt_cache"
    },
    "sync": {
        "trakt_to_plex": {
            "watched_status": true,
            "ratings": true,
            "liked_lists": true,
            "watchlist": true
        },
        "plex_to_trakt": {
            "watched_status": true,
            "ratings": true,
            "collection": true
        }
    },
    "watch": {
        "username_filter": false
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    },
    "excluded-libraries": [
        "Private",
        "Family Holidays"
    ]
}
```

### Version

0.16.4

### Python Version

3.10.0

### Plex Server Version

4.7.2

### Operating System and Version

Ubuntu 18.04

**Comment by glensc** [comment]
>  [x] I have checked if identical issue already exists
Liar!

Search gives already two identical issues:
- https://github.com/Taxel/PlexTraktSync/issues?q=is%3Aissue+sort%3Aupdated-desc+UserList.__new__+is%3Aclosed+share_link
  - https://github.com/Taxel/PlexTraktSync/issues/1456
  - https://github.com/Taxel/PlexTraktSync/issues/1459

> Version: 0.16.4

This version is over 2 years old. Not supported.
