### ISSUE TITLE
Playback status from trakt is not writen back to plex for managed/ home users on same plex server

### ISSUE THREAD

**Issue by charles474** [Taxel/PlexTraktSync#2003]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

When the **`playback_status`** flag to **`true`**, for a managed user (or a user that has a Plex account but is part of a home), when syncing from Trakt to plex, this causes the script to fail with `401) unauthorized` messages before crashing. However, for the server admin it syncs with the same config without any issues.

## Approach 1 - Sign in as server admin and select the managed/ home user
1. Login with `pletraktsync plex-login`.
2. Login in with server admin plex credentials
3. Select managed user/ user that is part of the home (after this selection, their credentials are created)

## Approach 2 - Sign in as managed or user with an account but part of a home
1. Login with `pletraktsync plex-login`.
2. Login in with managed user/ user that is part of the home plex credentials
3. Select managed user/ user that is part of the home (after this selection, their credentials are created)

### Error trace / logs

```text
2024-06-27 07:08:31,008 INFO[plextraktsync.plex.PlexServerConnection]:Connecting with url: https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400, timeout 30 seconds
2024-06-27 07:08:31,182 INFO[plextraktsync.watch.WebSocketListener]:Listening for events!
2024-06-27 07:08:31,184 INFO[plextraktsync.watch.WatchStateUpdater]:Server connected: Plex Home Server (1.40.3.8555-fef15d30c)
2024-06-27 07:08:31,192 INFO[plexapi]:Starting AlertListener: wss://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400/:/websockets/notifications?X-Plex-Token=<hidden>
2024-06-27 07:08:31,283 INFO[websocket]:Websocket connected
2024-06-27 07:08:31,327 INFO[plextraktsync.commands.sync]:PlexTraktSync [0.31.4]
2024-06-27 07:08:31,436 INFO[plextraktsync.plex.PlexServerConnection]:Connecting with url: https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400, timeout 30 seconds
2024-06-27 07:08:31,500 INFO[plextraktsync.commands.sync]:Sync Movie sections: ['Movies']
2024-06-27 07:08:31,502 INFO[plextraktsync.commands.sync]:Sync Show sections: ['Shows']
2024-06-27 07:08:31,517 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'AddCollectionPlugin': True
2024-06-27 07:08:31,520 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'ClearCollectedPlugin': False
2024-06-27 07:08:31,521 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'LikedListsPlugin': True
2024-06-27 07:08:31,523 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'SyncRatingsPlugin': True
2024-06-27 07:08:31,552 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'SyncWatchedPlugin': True
2024-06-27 07:08:31,553 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'TraktListsPlugin': True
2024-06-27 07:08:31,555 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'WatchListPlugin': True
2024-06-27 07:08:33,629 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'WatchProgressPlugin': True
2024-06-27 07:08:33,789 WARNING[plextraktsync.sync.TraktListsPlugin]:Disabling TraktListsPlugin: No lists to process
2024-06-27 07:08:34,871 INFO[plextraktsync.decorators.measure_time]:Movies processed in 1.08 seconds
2024-06-27 07:08:34,873 INFO[plextraktsync.plan.Walker]:Preload shows data
2024-06-27 07:08:35,074 INFO[plextraktsync.decorators.measure_time]:Shows processed in 199 milliseconds and 970 microseconds
2024-06-27 07:08:35,075 INFO[plextraktsync.plan.Walker]:Preloaded shows data (68 shows)
2024-06-27 07:08:35,076 INFO[plextraktsync.plan.Walker]:Preload shows matches
2024-06-27 07:08:35,271 INFO[plextraktsync.plan.Walker]:Preloaded shows matches (68 shows)
2024-06-27 07:08:39,024 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e01/Episode 1: Skipping <PlexGuid:local://963> because provider 'local' has no external Id
2024-06-27 07:08:39,026 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e02/Episode 2 (2024): Skipping <PlexGuid:local://964> because provider 'local' has no external Id
2024-06-27 07:08:39,027 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e03/Episode 3 (2024): Skipping <PlexGuid:local://965> because provider 'local' has no external Id
2024-06-27 07:08:39,029 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e04/Episode 4 (2024): Skipping <PlexGuid:local://970> because provider 'local' has no external Id
2024-06-27 07:08:39,031 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e05/Episode 5 (2024): Skipping <PlexGuid:local://971> because provider 'local' has no external Id
2024-06-27 07:08:40,482 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s01e55/Episode 55: Skipping <PlexGuid:local://2782> because provider 'local' has no external Id
2024-06-27 07:08:40,487 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s02e13/Episode 13: Skipping <PlexGuid:local://2785> because provider 'local' has no external Id
2024-06-27 07:08:40,492 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s03e13/Episode 13: Skipping <PlexGuid:local://2141> because provider 'local' has no external Id
2024-06-27 07:08:40,498 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s04e14/Episode 14: Skipping <PlexGuid:local://2786> because provider 'local' has no external Id
2024-06-27 07:08:41,583 WARNING[plextraktsync.media.MediaFactory]:Krypton/s01e2017/Episode 2017: Skipping <PlexGuid:local://1350> because provider 'local' has no external Id
2024-06-27 07:08:41,591 INFO[plextraktsync.sync.WatchProgressPlugin]:Lessons in Chemistry/s01e02/Her and Him (2023): Set watch progress to 29.33%: 0:15:56.789000 -> 0:14:42.316000
2024-06-27 07:08:41,602 ERROR[plextraktsync.cli]:(401) unauthorized; https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400/:/progress?key=1365&identifier=com.plexapp.plugins.library&time=882316&state=stopped <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
Traceback (most recent call last):
  File "/app/plextraktsync/cli.py", line 26, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 80, in sync
    run_async(runner, walker=w, dry_run=config.dry_run)
  File "/usr/local/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/decorators/coro.py", line 13, in coro
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/plextraktsync/commands/sync.py", line 13, in run_async
    await runner.sync(**kwargs)
  File "/app/plextraktsync/sync/Sync.py", line 53, in sync
    await pm.ahook.walk_episode(episode=episode, dry_run=dry_run)
  File "/usr/local/lib/python3.12/site-packages/apluggy/_wrap.py", line 119, in call
    return await asyncio.gather(*coros)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/sync/WatchProgressPlugin.py", line 36, in walk_episode
    await self.sync_progress(episode, dry_run=dry_run)
  File "/app/plextraktsync/sync/WatchProgressPlugin.py", line 57, in sync_progress
    m.plex.item.updateProgress(progress)
  File "/usr/local/lib/python3.12/site-packages/plexapi/base.py", line 901, in updateProgress
    self._server.query(key)
  File "/usr/local/lib/python3.12/site-packages/plexapi/server.py", line 766, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400/:/progress?key=1365&identifier=com.plexapp.plugins.library&time=882316&state=stopped <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
2024-06-27 07:08:43,590 INFO[plextraktsync.commands.sync]:PlexTraktSync [0.31.4]
2024-06-27 07:08:43,710 INFO[plextraktsync.plex.PlexServerConnection]:Connecting with url: https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400, timeout 30 seconds
2024-06-27 07:08:43,772 INFO[plextraktsync.commands.sync]:Sync Movie sections: ['Movies']
2024-06-27 07:08:43,773 INFO[plextraktsync.commands.sync]:Sync Show sections: ['Shows']
2024-06-27 07:08:43,790 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'AddCollectionPlugin': True
2024-06-27 07:08:43,793 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'ClearCollectedPlugin': False
2024-06-27 07:08:43,794 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'LikedListsPlugin': True
2024-06-27 07:08:43,796 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'SyncRatingsPlugin': True
2024-06-27 07:08:43,798 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'SyncWatchedPlugin': True
2024-06-27 07:08:43,799 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'TraktListsPlugin': True
2024-06-27 07:08:43,801 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'WatchListPlugin': True
2024-06-27 07:08:45,357 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'WatchProgressPlugin': True
2024-06-27 07:08:45,520 WARNING[plextraktsync.sync.TraktListsPlugin]:Disabling TraktListsPlugin: No lists to process
2024-06-27 07:08:46,370 INFO[plextraktsync.decorators.measure_time]:Movies processed in 846 milliseconds and 362 microseconds
2024-06-27 07:08:46,371 INFO[plextraktsync.plan.Walker]:Preload shows data
2024-06-27 07:08:46,567 INFO[plextraktsync.decorators.measure_time]:Shows processed in 194 milliseconds and 77 microseconds
2024-06-27 07:08:46,568 INFO[plextraktsync.plan.Walker]:Preloaded shows data (68 shows)
2024-06-27 07:08:46,569 INFO[plextraktsync.plan.Walker]:Preload shows matches
2024-06-27 07:08:46,751 INFO[plextraktsync.plan.Walker]:Preloaded shows matches (68 shows)
2024-06-27 07:08:50,331 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e01/Episode 1: Skipping <PlexGuid:local://963> because provider 'local' has no external Id
2024-06-27 07:08:50,332 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e02/Episode 2 (2024): Skipping <PlexGuid:local://964> because provider 'local' has no external Id
2024-06-27 07:08:50,334 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e03/Episode 3 (2024): Skipping <PlexGuid:local://965> because provider 'local' has no external Id
2024-06-27 07:08:50,336 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e04/Episode 4 (2024): Skipping <PlexGuid:local://970> because provider 'local' has no external Id
2024-06-27 07:08:50,338 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e05/Episode 5 (2024): Skipping <PlexGuid:local://971> because provider 'local' has no external Id
2024-06-27 07:08:51,729 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s01e55/Episode 55: Skipping <PlexGuid:local://2782> because provider 'local' has no external Id
2024-06-27 07:08:51,734 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s02e13/Episode 13: Skipping <PlexGuid:local://2785> because provider 'local' has no external Id
2024-06-27 07:08:51,738 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s03e13/Episode 13: Skipping <PlexGuid:local://2141> because provider 'local' has no external Id
2024-06-27 07:08:51,744 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s04e14/Episode 14: Skipping <PlexGuid:local://2786> because provider 'local' has no external Id
2024-06-27 07:08:52,790 WARNING[plextraktsync.media.MediaFactory]:Krypton/s01e2017/Episode 2017: Skipping <PlexGuid:local://1350> because provider 'local' has no external Id
2024-06-27 07:08:52,799 INFO[plextraktsync.sync.WatchProgressPlugin]:Lessons in Chemistry/s01e02/Her and Him (2023): Set watch progress to 29.33%: 0:15:56.789000 -> 0:14:42.316000
2024-06-27 07:08:52,811 ERROR[plextraktsync.cli]:(401) unauthorized; https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400/:/progress?key=1365&identifier=com.plexapp.plugins.library&time=882316&state=stopped <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
Traceback (most recent call last):
  File "/app/plextraktsync/cli.py", line 26, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 80, in sync
    run_async(runner, walker=w, dry_run=config.dry_run)
  File "/usr/local/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/decorators/coro.py", line 13, in coro
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/plextraktsync/commands/sync.py", line 13, in run_async
    await runner.sync(**kwargs)
  File "/app/plextraktsync/sync/Sync.py", line 53, in sync
    await pm.ahook.walk_episode(episode=episode, dry_run=dry_run)
  File "/usr/local/lib/python3.12/site-packages/apluggy/_wrap.py", line 119, in call
    return await asyncio.gather(*coros)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/sync/WatchProgressPlugin.py", line 36, in walk_episode
    await self.sync_progress(episode, dry_run=dry_run)
  File "/app/plextraktsync/sync/WatchProgressPlugin.py", line 57, in sync_progress
    m.plex.item.updateProgress(progress)
  File "/usr/local/lib/python3.12/site-packages/plexapi/base.py", line 901, in updateProgress
    self._server.query(key)
  File "/usr/local/lib/python3.12/site-packages/plexapi/server.py", line 766, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400/:/progress?key=1365&identifier=com.plexapp.plugins.library&time=882316&state=stopped <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
2024-06-27 07:08:54,794 INFO[plextraktsync.commands.sync]:PlexTraktSync [0.31.4]
2024-06-27 07:08:54,924 INFO[plextraktsync.plex.PlexServerConnection]:Connecting with url: https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400, timeout 30 seconds
2024-06-27 07:08:54,983 INFO[plextraktsync.commands.sync]:Sync Movie sections: ['Movies']
2024-06-27 07:08:54,985 INFO[plextraktsync.commands.sync]:Sync Show sections: ['Shows']
2024-06-27 07:08:55,001 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'AddCollectionPlugin': True
2024-06-27 07:08:55,004 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'ClearCollectedPlugin': False
2024-06-27 07:08:55,005 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'LikedListsPlugin': True
2024-06-27 07:08:55,007 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'SyncRatingsPlugin': True
2024-06-27 07:08:55,009 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'SyncWatchedPlugin': True
2024-06-27 07:08:55,011 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'TraktListsPlugin': True
2024-06-27 07:08:55,012 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'WatchListPlugin': True
2024-06-27 07:08:56,773 INFO[plextraktsync.sync.plugin.SyncPluginManager]:Enable sync plugin 'WatchProgressPlugin': True
2024-06-27 07:08:56,971 WARNING[plextraktsync.sync.TraktListsPlugin]:Disabling TraktListsPlugin: No lists to process
2024-06-27 07:08:58,213 INFO[plextraktsync.decorators.measure_time]:Movies processed in 1.24 seconds
2024-06-27 07:08:58,214 INFO[plextraktsync.plan.Walker]:Preload shows data
2024-06-27 07:08:58,407 INFO[plextraktsync.decorators.measure_time]:Shows processed in 192 milliseconds and 455 microseconds
2024-06-27 07:08:58,409 INFO[plextraktsync.plan.Walker]:Preloaded shows data (68 shows)
2024-06-27 07:08:58,410 INFO[plextraktsync.plan.Walker]:Preload shows matches
2024-06-27 07:08:58,595 INFO[plextraktsync.plan.Walker]:Preloaded shows matches (68 shows)
2024-06-27 07:09:02,287 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e01/Episode 1: Skipping <PlexGuid:local://963> because provider 'local' has no external Id
2024-06-27 07:09:02,289 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e02/Episode 2 (2024): Skipping <PlexGuid:local://964> because provider 'local' has no external Id
2024-06-27 07:09:02,291 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e03/Episode 3 (2024): Skipping <PlexGuid:local://965> because provider 'local' has no external Id
2024-06-27 07:09:02,292 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e04/Episode 4 (2024): Skipping <PlexGuid:local://970> because provider 'local' has no external Id
2024-06-27 07:09:02,294 WARNING[plextraktsync.media.MediaFactory]:Echo/s01e05/Episode 5 (2024): Skipping <PlexGuid:local://971> because provider 'local' has no external Id
2024-06-27 07:09:03,710 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s01e55/Episode 55: Skipping <PlexGuid:local://2782> because provider 'local' has no external Id
2024-06-27 07:09:03,715 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s02e13/Episode 13: Skipping <PlexGuid:local://2785> because provider 'local' has no external Id
2024-06-27 07:09:03,720 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s03e13/Episode 13: Skipping <PlexGuid:local://2141> because provider 'local' has no external Id
2024-06-27 07:09:03,725 WARNING[plextraktsync.media.MediaFactory]:The Good Place/s04e14/Episode 14: Skipping <PlexGuid:local://2786> because provider 'local' has no external Id
2024-06-27 07:09:04,805 WARNING[plextraktsync.media.MediaFactory]:Krypton/s01e2017/Episode 2017: Skipping <PlexGuid:local://1350> because provider 'local' has no external Id
2024-06-27 07:09:04,814 INFO[plextraktsync.sync.WatchProgressPlugin]:Lessons in Chemistry/s01e02/Her and Him (2023): Set watch progress to 29.33%: 0:15:56.789000 -> 0:14:42.316000
2024-06-27 07:09:04,825 ERROR[plextraktsync.cli]:(401) unauthorized; https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400/:/progress?key=1365&identifier=com.plexapp.plugins.library&time=882316&state=stopped <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
Traceback (most recent call last):
  File "/app/plextraktsync/cli.py", line 26, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 80, in sync
    run_async(runner, walker=w, dry_run=config.dry_run)
  File "/usr/local/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/decorators/coro.py", line 13, in coro
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/plextraktsync/commands/sync.py", line 13, in run_async
    await runner.sync(**kwargs)
  File "/app/plextraktsync/sync/Sync.py", line 53, in sync
    await pm.ahook.walk_episode(episode=episode, dry_run=dry_run)
  File "/usr/local/lib/python3.12/site-packages/apluggy/_wrap.py", line 119, in call
    return await asyncio.gather(*coros)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/sync/WatchProgressPlugin.py", line 36, in walk_episode
    await self.sync_progress(episode, dry_run=dry_run)
  File "/app/plextraktsync/sync/WatchProgressPlugin.py", line 57, in sync_progress
    m.plex.item.updateProgress(progress)
  File "/usr/local/lib/python3.12/site-packages/plexapi/base.py", line 901, in updateProgress
    self._server.query(key)
  File "/usr/local/lib/python3.12/site-packages/plexapi/server.py", line 766, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://192-168-0-62.defc95e2d6de46bdbeb0e5786516f893.plex.direct:32400/:/progress?key=1365&identifier=com.plexapp.plugins.library&time=882316&state=stopped <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

### Expected behavior

The script should sync the **`playback_status`** for both managed users and users that are part of the home seeing as Plex somehow stores their playback status on the same server.

### Config file contents

```yaml
cache:
  path: $PTS_CACHE_DIR/trakt_cache

# You may want to use per server libraries config instead:
# - https://github.com/Taxel/PlexTraktSync#libraries
excluded-libraries:
  - Private
  - Family Holidays

config:
  dotenv_override: true

plex:
  timeout: 30

logging:
  append: true
  # Whether to show timestamps in console messages
  console_time: false
  debug: false
  filename: plextraktsync.log
  # Additional logger names to apply filtering
  filter_loggers:
  #    - plexapi
  #    - requests_cache.backends
  #    - requests_cache.backends.base
  #    - requests_cache.backends.sqlite
  #    - requests_cache.policy.actions
  #    - requests_cache.session
  #    - trakt.core
  #    - urllib3.connectionpool
  filter:
#    # Filter out all messages with level WARNING
#    - level: WARNING
#    # Filter out message with level WARNING and containing a text
#    - level: WARNING
#      message: "not found on Trakt"
#    - message: "because provider local has no external Id"
#    - message: "because provider none has no external Id"
#    - message: "Retry using search for specific Plex Episode"
#    # Filter out messages by requests_cache
#    - name: requests_cache.backends
#    - name: requests_cache.backends.base
#    - name: requests_cache.backends.sqlite
#    - name: requests_cache.policy.actions
#    - name: requests_cache.session

# settings for 'sync' command
sync:
  # Setting for whether ratings from one platform should have priority.
  # Valid values are trakt, plex or none. (default: plex)
  # none - No rating priority. Existing ratings are not overwritten.
  # trakt - Trakt ratings have priority. Existing Plex ratings are overwritten.
  # plex - Plex ratings have priority. Existing Trakt ratings are overwritten.
  rating_priority: trakt

  plex_to_trakt:
    collection: true
    # Clear collected state of items not present in Plex
    clear_collected: false
    ratings: true
    watched_status: true
    # If plex_to_trakt watchlist=false and trakt_to_plex watchlist=true
    # the Plex watchlist will be overwritten by Trakt watchlist
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    # If trakt_to_plex watchlist=false and plex_to_trakt watchlist=true
    # the Trakt watchlist will be overwritten by Plex watchlist
    watchlist: true
    # If you prefer to fetch trakt watchlist as a playlist instead of
    # plex watchlist, toggle this to true (is read only if watchlist=true)
    watchlist_as_playlist: false
    # Sync Play Progress from Trakt to Plex
    playback_status: true

# Configuration for liked lists
liked_lists:
  # Whether to keep watched items in the list
  keep_watched: true

# Configuration override for specific lists
#liked_list:
#  "Saw Collection":
#    keep_watched: true

# settings for 'watch' command
watch:
  add_collection: false
  remove_collection: false
  # what video watched percentage (0 to 100) triggers the watched status
  scrobble_threshold: 80
  # true to scrobble only what's watched by you, false for all your PMS users
  username_filter: true
  # Show the progress bar of played media in terminal
  media_progressbar: true
  # Clients to ignore when listening Play events
  ignore_clients: ~

xbmc-providers:
  movies: imdb
  shows: tvdb
##### Advanced settings below this line, don't edit unless you know what you're doing #####
#http_cache:
# https://requests-cache.readthedocs.io/en/main/user_guide/expiration.html#url-patterns
# https://requests-cache.readthedocs.io/en/main/user_guide/expiration.html#expiration-values
#
# The value is seconds to cache.
# Or one of the following special values:
# - DO_NOT_CACHE: Skip both reading from and writing to the cache
# - EXPIRE_IMMEDIATELY: Consider the response already expired, but potentially usable
# - NEVER_EXPIRE: Store responses indefinitely
#
# The value can be also suffixed with a time unit:
# - 5m, 1h, 3d
# See full documentation at:
# - https://github.com/wroberts/pytimeparse#pytimeparse-time-expression-parser
#
# NOTE: If there is more than one match, the first match will be used in the order they are defined
#  policy:
#    "*.trakt.tv/users/me": 1d
#    "*.trakt.tv/users/likes/lists": DO_NOT_CACHE

# vim:ts=2:sw=2:et
```

### Install method

docker-compose

### Version

0.31.0dev0

### Python Version

3.12.3

### Plex Server Version

1.40.3.8555

### Operating System and Version

Ubuntu 24.04 LTS

**Comment by glensc** [comment]
Does sound like feature request. An you reword it sound like feature request rather bug. Also remove not relevant logs from logs section.
