### ISSUE TITLE
Add error handling for invalid Plex user/pass

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#226]
During initial setup, I entered an incorrect password for Plex, and the script crashed out. Maybe it should handle incorrect passwords, and allow the user to correct it.

```
bink@Homey-McPlexFace PlexTraktSyncTest % python3 main.py
First run, please follow those configuration instructions.
-- Plex --
Are you logged into this server with a Plex account? (y/n): y
Please enter your Plex username: *REDACTED*
Please enter your Plex password: sdfjshfj
Now enter the server name: *REDACTED*    
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from plex_trakt_sync.cli import cli
  File "/Users/bink/scripts/PlexTraktSyncTest/plex_trakt_sync/cli.py", line 2, in <module>
    from plex_trakt_sync.commands.clear_collections import clear_collections
  File "/Users/bink/scripts/PlexTraktSyncTest/plex_trakt_sync/commands/clear_collections.py", line 2, in <module>
    from plex_trakt_sync.logging import logger
  File "/Users/bink/scripts/PlexTraktSyncTest/plex_trakt_sync/logging.py", line 29, in <module>
    initialize()
  File "/Users/bink/scripts/PlexTraktSyncTest/plex_trakt_sync/logging.py", line 9, in initialize
    log_level = logging.DEBUG if CONFIG['log_debug_messages'] else logging.INFO
  File "/Users/bink/scripts/PlexTraktSyncTest/plex_trakt_sync/config.py", line 26, in __getitem__
    self.initialize()
  File "/Users/bink/scripts/PlexTraktSyncTest/plex_trakt_sync/config.py", line 46, in initialize
    get_env_data()
  File "/Users/bink/scripts/PlexTraktSyncTest/plex_trakt_sync/get_env_data.py", line 16, in get_env_data
    account = MyPlexAccount(username, password)
  File "/Library/Python/3.7/site-packages/plexapi/myplex.py", line 95, in __init__
    data, initpath = self._signin(username, password, timeout)
  File "/Library/Python/3.7/site-packages/plexapi/myplex.py", line 103, in _signin
    data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout)
  File "/Library/Python/3.7/site-packages/plexapi/myplex.py", line 193, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://plex.tv/users/sign_in.xml <?xml version="1.0" encoding="UTF-8"?> <errors>   <error>Invalid email, username, or password.</error> </errors> 
```

**Comment by glensc** [comment]
I started rewriting the login logic to commands:
- https://github.com/Taxel/PlexTraktSync/pull/230

It will definitely attempt to validate credentials before storing them.

This topic was somewhat also covered in earlier PR:
- https://github.com/Taxel/PlexTraktSync/pull/53

**Comment by glensc** [comment]
You can login again with `plex-login` command now ([0.7.18](https://github.com/Taxel/PlexTraktSync/releases/tag/0.7.18)):
- https://github.com/Taxel/PlexTraktSync/pull/230

**Comment by glensc** [comment]
The old login code has been replaced with a new login code which handles retry for invalid input.
