### ISSUE TITLE
New error with 0.7.9 (and 0.7.10) during sync

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#245]
I'm getting a new error using the 0.7.9 version, this error just started happening a day or so ago, so it might be related to some new item I added to my library.

I have three different servers, and the error is happening on all of them (the same media exists on all servers).

Here is the beginning of the traceback:

```
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/Library/Python/3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 206, in sync
    sync_all(movies=movies, tv=tv)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 172, in sync_all
    sync_show_collection(tm, pe, te, trakt)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 29, in sync_show_collection
    collected = trakt.collected(tm)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/decorators/nocache.py", line 10, in inner
    return method(self, *args, **kwargs)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/decorators/rate_limit.py", line 43, in wrapper
    return fn(*args, **kwargs)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/trakt_api.py", line 191, in collected
    return pytrakt_extensions.collected(tm.trakt)
  File "/Library/Python/3.7/site-packages/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/Library/Python/3.7/site-packages/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found
```

**Comment by BEisem** [comment]
I just realized there is a 0.7.10 release, I downloaded that version but I'm still getting the same error...

**Comment by glensc** [comment]
You can check the release notes and changelog generated by github on the releases page. It shows what changes are included in the release, are they even interesting to you.

Are you saying it works with older versions? What's the lowest version it still works?

Altho the likely fix is to catch such error and ignore the item, log a warning.

I think I already fixed such error, but for movie.

**Comment by BEisem** [comment]
I found the offending series that was causing the error, and removed it temporarily from my library. If you decide to catch and ignore the error, I can add it back to my library and test it out.

**Comment by glensc** [comment]
Seems the code that triggers this is changed in https://github.com/Taxel/PlexTraktSync/pull/240, so need to visit this after it's merged.

So, postponing this to avoid duplicate efforts.

**Comment by glensc** [comment]
I think it even fixes the problem, as I see `NotFound` being caught for TV Episodes...
