### ISSUE TITLE
Crash happening during movie sync

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#257]
0.7.19 causes a crash during a movie sync.

End of the script output before the crash:

```
Processing Movies  [#################-------------------]  5268/11117  00:48:45INFO: Add to Trakt Collection: <imdb:tt11908982:<Movie:198327:Jakob's-Wife>>
Processing Movies  [#################-------------------]  5275/11117  00:48:41INFO: Add to Trakt Collection: <imdb:tt0097613:<Movie:197966:The-January-Man>>
Processing Movies  [#################-------------------]  5404/11117  00:47:33INFO: Add to Trakt Collection: <imdb:tt0045943:<Movie:197979:Julius-Caesar>>
Processing Movies  [#################-------------------]  5422/11117  00:47:24INFO: Add to Trakt Collection: <imdb:tt6710826:<Movie:198267:The-Jurassic-Games>>
Processing Movies  [#################-------------------]  5453/11117  00:47:09
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/Library/Python/3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 235, in sync
    sync_all(movies=movies, tv=tv, show=show)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 178, in sync_all
    for pm, tm in for_each_pair(plex.movie_sections, trakt):
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 116, in for_each_pair
    tm = trakt.find_by_media(pm)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/decorators/rate_limit.py", line 45, in wrapper
    return fn(*args, **kwargs)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/trakt_api.py", line 205, in find_by_media
    search = trakt.sync.search_by_id(media.id, id_type=media.provider, media_type=media.type)
  File "/Users/bink/Library/Python/3.7/lib/python/site-packages/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/Users/bink/Library/Python/3.7/lib/python/site-packages/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.TraktInternalException: Internal Server Error
```

originally reported here:
- https://github.com/Taxel/PlexTraktSync/issues/256#issuecomment-821862349

**Comment by glensc** [comment]
Here's immediate mitigation: https://github.com/Taxel/PlexTraktSync/pull/258

**Comment by glensc** [comment]
In this comment, you said you going to run again:
- https://github.com/Taxel/PlexTraktSync/issues/256#issuecomment-821862349

so, re-run emitted same error or not?

**Comment by BEisem** [comment]
The re-run did result in the same error, but I found the problem entry in my library and fixed it. So I don't know if this is something that should be attributed to a problem in the Plex library, or if you want to still try and catch the error.

**Comment by glensc** [comment]
So seems Trakt didn't like the request. But not sure how your changes fixed it, maybe the Trakt id changed.

So, let's leave it like that for now.

**Comment by BEisem** [comment]
I'm getting a new error when trying to run a movie sync. @glensc Since the error is different, would you like me to create a new issue? Or should I posts the traceback in this issue?

**Comment by glensc** [comment]
@BEisem you don't need to re-open the issue just to post a question. Yes, please new issue. your version info is different. and issues tend to get long very fast here. I don't see any value in keeping everything under one issue.
