### ISSUE TITLE
trakt.errors.TraktInternalException: Internal Server Error

### ISSUE THREAD

**Issue by zerosquared** [Taxel/PlexTraktSync#270]
### The problem

It gets almost to the end of processing my Movies (or maybe it finishes?) and then it says this:

```
Processing Movies  [##################################--]  3175/3303  00:00:14
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    cli()
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\xxx\Documents\GitHub\PlexTraktSync-main\plex_trakt_sync\cli.py", line 18, in cli
    sync()
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\xxxs\Documents\GitHub\PlexTraktSync-main\plex_trakt_sync\commands\sync.py", line 240, in sync
    sync_all(movies=movies, tv=tv, show=show)
  File "C:\Users\xxxs\Documents\GitHub\PlexTraktSync-main\plex_trakt_sync\commands\sync.py", line 183, in sync_all
    for pm, tm in for_each_pair(plex.movie_sections, trakt):
  File "C:\Users\xxxs\Documents\GitHub\PlexTraktSync-main\plex_trakt_sync\commands\sync.py", line 116, in for_each_pair
    tm = trakt.find_by_media(pm)
  File "C:\Users\xxxs\Documents\GitHub\PlexTraktSync-main\plex_trakt_sync\trakt_api.py", line 207, in find_by_media
    return self.search_by_id(pm.id, id_type=pm.provider, media_type=pm.type)
  File "C:\Users\xxxs\Documents\GitHub\PlexTraktSync-main\plex_trakt_sync\decorators\rate_limit.py", line 43, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\xxxs\Documents\GitHub\PlexTraktSync-main\plex_trakt_sync\trakt_api.py", line 211, in search_by_id
    search = trakt.sync.search_by_id(media_id, id_type=id_type, media_type=media_type)
  File "C:\Program Files\Python38\lib\site-packages\trakt\core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "C:\Program Files\Python38\lib\site-packages\trakt\core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.TraktInternalException: Internal Server Error
```

### Expected behavior

Successful completion of the script

### Steps to reproduce the behavior

`python main.py`

I've ran it multiple times.  I've seen a lot of the GUID errors as well but that may be how my metadata is set

### Workarounds

I searched but could not find one.  I could not even find this as an error that's been received.

### Environment

- Version: master
- Python version: 3.8
- Platform: Windows 10

**Comment by glensc** [comment]
Duplicate: https://github.com/Taxel/PlexTraktSync/issues/257

Retry added in https://github.com/Taxel/PlexTraktSync/pull/258 (0.7.25)

But that doesn't solve the problem, what should be done here is to skip the item if the retries did not help.
