### ISSUE TITLE
Crash on fresh install : requests_cache AttributeError : 'HTTPResponse' object has no attribute 'isclosed'

### ISSUE THREAD

**Issue by Davst** [Taxel/PlexTraktSync#334]
### The problem
Script not working, tried both with pipenv and without.

Without virtualenv:
```
Login to MyPlex was successful!
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    cli()
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/haddoq/PlexTraktSync/plex_trakt_sync/cli.py", line 21, in cli
    sync()
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/haddoq/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 136, in sync
    ensure_login()
  File "/home/haddoq/PlexTraktSync/plex_trakt_sync/commands/login.py", line 9, in ensure_login
    plex_login()
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/haddoq/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/haddoq/PlexTraktSync/plex_trakt_sync/commands/plex_login.py", line 152, in plex_login
    [server, plex] = choose_server(account)
  File "/home/haddoq/PlexTraktSync/plex_trakt_sync/commands/plex_login.py", line 119, in choose_server
    server = pick_server(account)
  File "/home/haddoq/PlexTraktSync/plex_trakt_sync/commands/plex_login.py", line 99, in pick_server
    servers = account.resources()
  File "/home/haddoq/.local/lib/python3.6/site-packages/plexapi/myplex.py", line 214, in resources
    data = self.query(MyPlexResource.key)
  File "/home/haddoq/.local/lib/python3.6/site-packages/plexapi/myplex.py", line 187, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/home/haddoq/.local/lib/python3.6/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/haddoq/.local/lib/python3.6/site-packages/requests_cache/session.py", line 96, in request
    **kwargs,
  File "/home/haddoq/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/haddoq/.local/lib/python3.6/site-packages/requests_cache/session.py", line 127, in send
    return self._send_and_cache(request, cache_key, **kwargs)
  File "/home/haddoq/.local/lib/python3.6/site-packages/requests_cache/session.py", line 161, in _send_and_cache
    self.cache.save_response(cache_key, response, self._get_expiration(request.url))
  File "/home/haddoq/.local/lib/python3.6/site-packages/requests_cache/backends/base.py", line 49, in save_response
    self.responses[key] = CachedResponse(response, expire_after=expire_after)
  File "/home/haddoq/.local/lib/python3.6/site-packages/requests_cache/response.py", line 54, in __init__
    if hasattr(original_response.raw, '_fp') and not original_response.raw.isclosed():
AttributeError: 'HTTPResponse' object has no attribute 'isclosed'
```

With virtualenv:
```
> pipenv run python main.py                                                                                                       PlexTraktSync -> 91acf55
Creating a virtualenv for this project…
Pipfile: /home/haddoq/PlexTraktSync/Pipfile
Using /usr/bin/python3 (3.6.9) to create virtualenv…
⠦ Creating virtual environment...Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/haddoq/.local/share/virtualenvs/PlexTraktSync-mP6KJ4vR/bin/python3
Also creating executable in /home/haddoq/.local/share/virtualenvs/PlexTraktSync-mP6KJ4vR/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /home/haddoq/.local/share/virtualenvs/PlexTraktSync-mP6KJ4vR
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from plex_trakt_sync.cli import cli
  File "/home/haddoq/PlexTraktSync/plex_trakt_sync/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

### Expected behavior
Expected script not to crash

### Steps to reproduce the behavior
Follow installation instructions on GitHub, breaks when trying to run the first time.

### Environment
- Version: 0.10.3
- Python version: 3.6.9
- Platform: Ubuntu

**Comment by twolaw** [comment]
From the last lines :
```
  File "/home/haddoq/.local/lib/python3.6/site-packages/requests_cache/response.py", line 54, in __init__
    if hasattr(original_response.raw, '_fp') and not original_response.raw.isclosed():
AttributeError: 'HTTPResponse' object has no attribute 'isclosed'
```
I think it could be because of an old version of urllib3 or requests module.

PR https://github.com/reclosedev/requests-cache/pull/269 from 23-May-2021 changes this line of code and states :

- Use urllib3.is_fp_closed() instead of urllib3.response.HTTPResponse.isclosed() (for older versions of urllib3--unsure which version)

@Davst Which version of `urllib3` and `requests` module do you have ? Can you update them and run script again ?

@glensc When a new version of `requests-cache` will be released I think we'll have to update it in the requirements.txt (and maybe add `requests` to be sure to have a not too old version).
________________________________________________________________________________

The virtualenv error seems to show that you forgot to install required modules.

**Comment by glensc** [comment]
please show your versions:

1. `python3 -m pip list`
1. `pipenv run python3 -m pip list`

for pipenv it should run `pipenv install` automatically when `pipenv run` is executed...

**Comment by Davst** [comment]
Sorry.. ofc. 

regular environment
`urllib3                1.22`
`requests               2.25.1`

pipenv doesn't seem to have any of these installed, as said followed the commands in the readme.

will update urllib and requests.

**Comment by Davst** [comment]
runs after updating urllib3

**Comment by glensc** [comment]
@Davst did you run `pipenv install`, did it help?

**Comment by glensc** [comment]
Looks like `pipenv run` does not perform `pipenv install`, so it needs to be ran manually. It does create virtualenv, but does not install the application dependencies.

```
[~/scm/plex/PlexTraktSync (urllib3-dep)★] ➔ rm -rf /Users/glen/.local/share/virtualenvs/PlexTraktSync-bl4IJvfJ/

[~/scm/plex/PlexTraktSync (urllib3-dep)★] ➔ pipenv run python -m pip list
Creating a virtualenv for this project...
Pipfile: /Users/glen/scm/plex/Plugins/PlexTraktSync/Pipfile
Using /usr/local/bin/python3.9 (3.9.5) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython3.9.5.final.0-64 in 934ms
  creator CPython3Posix(dest=/Users/glen/.local/share/virtualenvs/PlexTraktSync-bl4IJvfJ, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/glen/Library/Application Support/virtualenv)
    added seed packages: pip==21.0.1, setuptools==56.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/glen/.local/share/virtualenvs/PlexTraktSync-bl4IJvfJ
Loading .env environment variables...
Package    Version
---------- -------
pip        21.0.1
setuptools 56.0.0
wheel      0.36.2
[~/scm/plex/PlexTraktSync (urllib3-dep)★] ➔
```
