### ISSUE TITLE
ERROR[PlexTraktSync]:Unable to parse a valid provider from guid

### ISSUE THREAD

**Issue by RXWatcher** [Taxel/PlexTraktSync#338]
### The problem

```
WARNING: Skipping local://374486: Provider local has no external Id
WARNING: Skipping local://374487: Provider local has no external Id
WARNING: Skipping local://883254: Provider local has no external Id
Processing TV Shows  [##----------------------------------]  801/13357  05:27:07WARNING: Skipping <tmdb:62698:<Show:180968:Apex-Predator>>: Not found on Trakt
WARNING: Skipping <tmdb:62698:<Show:180968:Apex-Predator>>: Not found on Trakt
Processing TV Shows  [##----------------------------------]  802/13357  05:27:05WARNING: Skipping <tmdb:68832:<Show:180855:Apocalypse-101>>: Not found on Trakt
WARNING: Skipping <tmdb:68832:<Show:180855:Apocalypse-101>>: Not found on Trakt
Processing TV Shows  [##----------------------------------]  808/13357  05:26:19ERROR: Unable to parse a valid provider from guid:plex://show/5e161d8a5dd66b00406d5c9d
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/opt/scripts/PlexTraktSync/pu/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/scripts/PlexTraktSync/pu/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/scripts/PlexTraktSync/pu/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/scripts/PlexTraktSync/pu/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/scripts/PlexTraktSync/pu/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 165, in sync
    sync_all(walker=w, trakt=trakt, server=server)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 87, in sync_all
    for episode in walker.find_episodes():
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/walker.py", line 83, in find_episodes
    show = self.mf.resolve_any(plex)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/media.py", line 105, in resolve_any
    for guid in pm.guids:
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/plex_api.py", line 110, in guids
    ordered = sorted(guids, key=lambda guid: sort_order[guid.provider])
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/plex_api.py", line 110, in <lambda>
    ordered = sorted(guids, key=lambda guid: sort_order[guid.provider])
KeyError: 'plex'
```

### Expected behavior
It continue on if it can't parse the provider

### Steps to reproduce the behavior

Using Python 3.8 with the latest main against my very large plex library (46K movies 13K+ shows)

### Workarounds

No

### Environment

Main
Python 3.8
Ubuntu 18.04

**Comment by glensc** [comment]
@RXWatcher: The workaround is to use the older version: 0.9.x

**Comment by RXWatcher** [comment]
unfortunately 0.9.x errors in a different way. It went through 733 series before it hit this:

WARNING: Skipping <local:319258:<Episode:319258:Angelina-Ballerina:--s03e18>>: Provider local has no external Id
WARNING: Skipping <local:319259:<Episode:319259:Angelina-Ballerina:--s03e19>>: Provider local has no external Id
WARNING: Skipping <local:319260:<Episode:319260:Angelina-Ballerina:--s03e20>>: Provider local has no external Id
Processing TV Shows  [#-----------------------------------]  733/13360  07:36:21
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/home/seed/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/seed/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/seed/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/seed/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/seed/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 169, in sync
    sync_all(walker=w, trakt=trakt, server=server)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 87, in sync_all
    sync_collection(episode)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 21, in sync_collection
    if m.is_collected:
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/media.py", line 47, in is_collected
    collected = self.trakt_api.collected(self.show.trakt)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/decorators/nocache.py", line 10, in inner
    return method(self, *args, **kwargs)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/decorators/rate_limit.py", line 22, in wrapper
    return fn(*args, **kwargs)
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/trakt_api.py", line 192, in collected
    return pytrakt_extensions.collected(tm.trakt)
  File "/home/seed/.local/lib/python3.6/site-packages/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/home/seed/.local/lib/python3.6/site-packages/trakt/core.py", line 527, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by glensc** [comment]
Could you add `print(self.show.trakt)` before this call:

```
  File "/opt/scripts/PlexTraktSync/plex_trakt_sync/media.py", line 47, in is_collected
    collected = self.trakt_api.collected(self.show.trakt)
```

and once you ob tained the id, run

```
python3 main.py inspect The_number
```

This looks like a problem with trakt.tv API, the error needs to be reported there.

**Comment by twolaw** [comment]
Just like the `local` key, a `plex` key should be added in :
https://github.com/Taxel/PlexTraktSync/blob/3ae8889e2ed0dfe58ce5fea6e602b2c6a4cd56ec/plex_trakt_sync/plex_api.py#L104-L109

**Comment by glensc** [comment]
> Just like the `local` key, a `plex` key should be added in :
> https://github.com/Taxel/PlexTraktSync/blob/3ae8889e2ed0dfe58ce5fea6e602b2c6a4cd56ec/plex_trakt_sync/plex_api.py#L104-L109

No, the plex:// should be resolved to tvdb, etc.

Would know more of the reporter (@RXWatcher) posted details of inspect command:
- https://github.com/Taxel/PlexTraktSync/issues/338#issuecomment-861457561

**Comment by twolaw** [comment]
> No, the plex:// should be resolved to tvdb, etc.

I know. But according to logs, a 'plex' key is coming from nowhere so I was thinking to add it as a security to prevent a crash, just like the 'local' key.
Nevermind, as you say we should wait more infos from RXWatcher to fully understand what's going on.
