### ISSUE TITLE
trakt.errors.TraktInternalException: Internal Server Error

### ISSUE THREAD

**Issue by Rouzax** [Taxel/PlexTraktSync#35]
@twolaw After updating to the latest release of the master branch it is not working any more for me.

Currently on: 8be3a7ec603cfae8a5fd3d53b9a94c11e3584ed2

```
PS C:\GitHub\PlexTraktSync> python .\main.py
Processing section Kids Movies
Traceback (most recent call last):
  File ".\main.py", line 324, in <module>
    main()
  File ".\main.py", line 305, in main
    section, trakt_watched_movies, ratings, listutil, trakt_movie_collection)
  File ".\main.py", line 65, in process_movie_section
    search = trakt.sync.search_by_id(x, id_type=provider)
  File "C:\Python37\lib\site-packages\trakt\core.py", line 472, in inner
    json_data = self._handle_request('get', url)
  File "C:\Python37\lib\site-packages\trakt\core.py", line 449, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.TraktInternalException: Internal Server Error
PS C:\GitHub\PlexTraktSync>
```

[last_update.txt](https://github.com/Taxel/PlexTraktSync/files/4671818/last_update.txt)

**Comment by twolaw** [comment]
How old is your oauth token?
It is only valid for 3 months, this issue may be a duplicate of issue #20

**Comment by Rouzax** [comment]
Should be new and it is kicking of but let me delete everything and start afresh

**Comment by Rouzax** [comment]
After deleting everything and starting fresh it is working again. Not sure what was going wrong.
