### ISSUE TITLE
Crash during initial scan

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#375]
### The problem

I saw the new version posted, so I decided to try a brand new reinstall from scratch. This means I am also doing a fresh initial scan, without the benefit of the local cache. As the scan is progressing, I occasionally get a crash with a traceback. Keep in mind I have an extremely large library (over 14k movies), so this might not happen for everyone. But I'm finding this crash happens roughly every 1-2000 movies.

```
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from   
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()  
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)  
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Python/3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10-243-234-60.8ffa95f9a6a4493ba0a24465abed823e.plex.direct', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/Library/Python/3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bink/scripts/PlexTraktSync-main/plex_trakt_sync/commands/sync.py", line 164, in sync
    sync_all(walker=w, trakt=trakt, plex=plex)
  File "/Users/bink/scripts/PlexTraktSync-main/plex_trakt_sync/commands/sync.py", line 80, in sync_all
    for movie in walker.find_movies():
  File "/Users/bink/scripts/PlexTraktSync-main/plex_trakt_sync/walker.py", line 71, in find_movies
    movie = self.mf.resolve_any(plex)
  File "/Users/bink/scripts/PlexTraktSync-main/plex_trakt_sync/media.py", line 100, in resolve_any
    for guid in pm.guids:
  File "/Users/bink/scripts/PlexTraktSync-main/plex_trakt_sync/plex_api.py", line 143, in guids
    guids = [PlexGuid(guid.id, self.type, self) for guid in self.item.guids]
  File "/Library/Python/3.7/site-packages/plexapi/base.py", line 441, in __getattribute__
    self.reload()
  File "/Library/Python/3.7/site-packages/plexapi/base.py", line 323, in reload
    data = self._server.query(key)
  File "/Library/Python/3.7/site-packages/plexapi/server.py", line 523, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests_cache/core.py", line 136, in request
    **kwargs
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)  
  File "/Library/Python/3.7/site-packages/requests_cache/core.py", line 109, in send
    return send_request_and_cache_response()
  File "/Library/Python/3.7/site-packages/requests_cache/core.py", line 97, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)  
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='10-243-234-60.8ffa95f9a6a4493ba0a24465abed823e.plex.direct', port=32400): Read timed out. (read timeout=30)
```
### Expected behavior

Scan should complete without crashing

### Steps to reproduce the behavior

After initial setup, I'm running the script with the following command: `./plex_trakt_sync.sh sync --sync=movies`

### Workarounds

Re-run the command. The scan will go very fast up until the point where the last scan crashed, due to the local cache. Then it will progress and scan a few thousand more movies, before crashing again at some point.

### Environment

- Version: main
- Python version: 3.7.3
- Platform: macOS 10.15.7

**Comment by glensc** [comment]
Timeout related existing issues:
- https://github.com/Taxel/PlexTraktSync/issues/9
- https://github.com/Taxel/PlexTraktSync/issues/161
- https://github.com/Taxel/PlexTraktSync/issues/130

**Comment by glensc** [comment]
https://github.com/Taxel/PlexTraktSync/pull/383 resolves this specific code point exception trapping.
