### ISSUE TITLE
Initial scan crash - Metadata parsing error : height = None

### ISSUE THREAD

**Issue by esticle** [Taxel/PlexTraktSync#380]
### The problem

On inital scan I get:

```
INFO: Marking as watched in Plex: <tvdb:313091/1/23:<Episode:151801:Rusty-Rivets-s01e23>>
Processing TV Shows  [###########################---------]  1394/1829  00:04:10INFO: To be added to collection: <tvdb:352833/1/7:<Episode:180550:Sally4Ever-s01e07>>

Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/PlexTraktSync/plex_trakt_sync/cli.py", line 22, in cli
    sync()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 164, in sync
    sync_all(walker=w, trakt=trakt, plex=plex)
  File "/tmp/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 88, in sync_all
    sync_collection(episode)
  File "/tmp/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 25, in sync_collection
    m.add_to_collection()
  File "/tmp/PlexTraktSync/plex_trakt_sync/media.py", line 52, in add_to_collection
    self.trakt_api.add_to_collection(self.trakt, self.plex)
  File "/tmp/PlexTraktSync/plex_trakt_sync/trakt_api.py", line 194, in add_to_collection
    **pm.to_json()
  File "/tmp/PlexTraktSync/plex_trakt_sync/plex_api.py", line 335, in to_json
    "resolution": self.resolution,
  File "/tmp/PlexTraktSync/plex_trakt_sync/plex_api.py", line 256, in resolution
    if height > 1100:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
$
```

Last few lines of last_update.log:

```
# tail -3 last_update.log 
2021-07-12 14:12:47,889 INFO[PlexTraktSync]:Marking as watched in Plex: <tvdb:313091/1/21:<Episode:151800:Rusty-Rivets-s01e21>>
2021-07-12 14:12:47,893 INFO[PlexTraktSync]:Marking as watched in Plex: <tvdb:313091/1/23:<Episode:151801:Rusty-Rivets-s01e23>>
2021-07-12 14:12:49,694 INFO[PlexTraktSync]:To be added to collection: <tvdb:352833/1/7:<Episode:180550:Sally4Ever-s01e07>>

```

This occurs at the same point on every re-run.

### Expected behavior

No stacktrace and a exit code of 0 is expected

### Steps to reproduce the behavior

Re-run 

`
$ ./plex_trakt_sync.sh 
`

### Workarounds

None found

### Environment

- Version: 0.13.2
- Python version: 3.8.10
- Platform: Ubuntu 20.04.2

**Comment by glensc** [comment]
Workarounds:
- use an older version of plextraktsync

**Comment by glensc** [comment]
Please post debug of `plextraktsync inspect 180550`

**Comment by esticle** [comment]
> Please post debug of `plextraktsync inspect 180550`

Thanks, sure:

```
$ ./plex_trakt_sync.sh inspect 180550
PlexTraktSync inspect [Unknown version]
Inspecting: <tvdb:352833/1/7:<Episode:180550:Sally4Ever-s01e07>>
URL: https://app.plex.tv/desktop/#!/server/08577491ce58b7cd488a8bad517b1d5818a1240b/details?key=/library/metadata/180550
Media.Guid: 'com.plexapp.agents.thetvdb://352833/1/7?lang=en'
Media.Guids: []
Audio: '5.1(side)', 'English (EAC3 5.1)'
Video: 'h264'
Guids:
  Guid: com.plexapp.agents.thetvdb://352833/1/7?lang=en, Id: 352833/1/7, Provider: tvdb
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/PlexTraktSync/plex_trakt_sync/commands/inspect.py", line 43, in inspect
    print(f"Metadata: {m.to_json()}")
  File "/tmp/PlexTraktSync/plex_trakt_sync/plex_api.py", line 335, in to_json
    "resolution": self.resolution,
  File "/tmp/PlexTraktSync/plex_trakt_sync/plex_api.py", line 256, in resolution
    if height > 1100:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

```
