### ISSUE TITLE
Error:  ekey was not provided

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Taxel/PlexTraktSync#385]
### The problem

getting this error when processing shows

```
Processing 4K TV  [############------------------------]  127/360  00:00:46
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/plexguide/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 164, in sync
    sync_all(walker=w, trakt=trakt, plex=plex)
  File "/home/plexguide/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 87, in sync_all
    for episode in walker.find_episodes():
  File "/home/plexguide/PlexTraktSync/plex_trakt_sync/walker.py", line 92, in find_episodes
    yield from self.episode_from_show(show)
  File "/home/plexguide/PlexTraktSync/plex_trakt_sync/walker.py", line 112, in episode_from_show
    me = self.mf.resolve_any(pe, show.trakt)
  File "/home/plexguide/PlexTraktSync/plex_trakt_sync/media.py", line 101, in resolve_any
    m = self.resolve_guid(guid, tm)
  File "/home/plexguide/PlexTraktSync/plex_trakt_sync/media.py", line 130, in resolve_guid
    tm = self.trakt.find_episode_guid(tm, guid)
  File "/home/plexguide/PlexTraktSync/plex_trakt_sync/trakt_api.py", line 257, in find_episode_guid
    return lookup[guid.pm.season_number][guid.pm.episode_number].instance
  File "/home/plexguide/PlexTraktSync/plex_trakt_sync/plex_api.py", line 313, in season_number
    return self.item.seasonNumber
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 457, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/video.py", line 860, in seasonNumber
    self._seasonNumber = self.parentIndex if self.parentIndex else self.season().seasonNumber
  File "/usr/local/lib/python3.7/dist-packages/plexapi/video.py", line 880, in season
    return self.fetchItem(self.parentKey)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 169, in fetchItem
    raise BadRequest('ekey was not provided')
plexapi.exceptions.BadRequest: ekey was not provided
```

I am guessing something is wrong with this particular show.  How do I find out what was being processed at the time?  Could there be some issue with metadata for this item that is causing this error?

- Version:  main
- Python version: 3.7.11
- Platform: Ubuntu 18.04.5

**Comment by twolaw** [comment]
Could you enable debug in **config.json** with `"log_debug_messages": true` then run script and show the content of **last_update.log** ?
Do you have episodes or videos not properly identified by Plex in your 4K TV library ?

**Comment by ookla-ariel-ride** [comment]
so the issue that I found here was that there was an entry in the sqlite cache db, but it was no longer in Plex.  I renamed the .sqlite file and it has been rebuilt and I no longer experience this error.

I think there need to be some routines to prune/maintain the sqlite db to prevent issues like this.
