### ISSUE TITLE
PlexAPI Bad Request

### ISSUE THREAD

**Issue by Tawagot0** [Taxel/PlexTraktSync#402]
Hi! When I try to synchronize my Plex history (already existing) to Trakt I get this error

### The problem

```
Processing Animes:   0%|▍                                                                                                                                                       | 5/1759 [00:00<01:54, 15.29it/s]
Traceback (most recent call last):
  File "/home/user/PlexTraktSync/./main.py", line 6, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 165, in sync
    sync_all(walker=w, trakt=trakt, plex=plex)
  File "/home/user/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 88, in sync_all
    for episode in walker.find_episodes():
  File "/home/user/PlexTraktSync/plex_trakt_sync/walker.py", line 89, in find_episodes
    show = self.mf.resolve_any(plex)
  File "/home/user/PlexTraktSync/plex_trakt_sync/media.py", line 100, in resolve_any
    for guid in pm.guids:
  File "/home/user/PlexTraktSync/plex_trakt_sync/plex_api.py", line 147, in guids
    guids = [PlexGuid(guid.id, self.type, self) for guid in self.get_guids()]
  File "/home/user/PlexTraktSync/plex_trakt_sync/decorators/rate_limit.py", line 22, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/PlexTraktSync/plex_trakt_sync/plex_api.py", line 135, in get_guids
    return self.item.guids
  File "/home/user/.local/lib/python3.9/site-packages/plexapi/base.py", line 471, in __getattribute__
    self._reload(_autoReload=True)
  File "/home/user/.local/lib/python3.9/site-packages/plexapi/base.py", line 350, in _reload
    data = self._server.query(key)
  File "/home/user/.local/lib/python3.9/site-packages/plexapi/server.py", line 669, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/27309?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
```

### Steps to reproduce the behavior

Launch the command: `python3 main.py` or `./plex_trakt_sync.sh sync`

### Environment

- Version: Latest
- Python version: 3.9.5
- Platform: Ubuntu

Thanks!

**Comment by glensc** [comment]
Try this branch to see if it gives you what movie/episode has the problem:
- https://github.com/Taxel/PlexTraktSync/pull/403

and when you have the id, run `plex_trakt_sync.sh inspect <id>` command

**Comment by Tawagot0** [comment]
> 
> 
> Try this branch to see if it gives you what movie/episode has the problem:
> 
>     * [Add logging when can't resolve guid #403](https://github.com/Taxel/PlexTraktSync/pull/403)
> 
> 
> and when you have the id, run `plex_trakt_sync.sh inspect <id>` command

Thanks for your help!
Logs:
```
PlexTraktSync inspect [b7776381: Add logging when can't resolve guid @2021-07-31 17:10:32]
Inspecting: <tmdb:613377:<Movie:205745:30-jours-max>>
URL: https://app.plex.tv/desktop/#!/server/XXXXXXX/details?key=/library/metadata/205745
Media.Guid: 'plex://movie/5e1632f0a71f54003dba84af'
Media.Guids: [<Guid:imdb://tt11206302>, <Guid:tmdb://613377>, <Guid:tvdb://134385>]
Audio: '5.1(side)', 'Français (DTS-HD MA 5.1)'
Video: 'h264'
Guids:
  Guid: tmdb://613377, Id: 613377, Provider: tmdb
  Guid: tvdb://134385, Id: 134385, Provider: tvdb
  Guid: imdb://tt11206302, Id: tt11206302, Provider: imdb
Metadata: {'collected_at': '2021-03-20:T16:28:58.000Z', 'media_type': 'digital', 'resolution': 'hd_1080p', 'audio': 'dts', 'audio_channels': '5.1'}
Trakt match: <Movie>: 30 Days Max
```

**Comment by glensc** [comment]
you did not show your error with the workaround from the branch.

**Comment by glensc** [comment]
also, since inspect did not give any error, I'm assuming the original error is gone, i.e it was just a temporary error?

**Comment by Tawagot0** [comment]
> lso, since inspect did not give any error, I'm assuming the original error is gone, i.e it was just a temporary error?

No always the error full logs:

```
INFO: PlexTraktSync [b7776381: Add logging when can't resolve guid @2021-07-31 17:10:32]
INFO: Syncing with Plex XXX and Trakt XXXX
Sync Movies: True
Sync Shows: True
INFO: Loaded Trakt lists in 2.8 seconds
Plex Server version: 1.23.6.4881-e2e58f321, updated at: 2021-07-31 16:01:33
WARNING: Skipping local://166646: Provider local has no external Id
Processing Documentaires: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 143/143 [00:01<00:00, 122.62it/s]
INFO: Documentaires processed in 1.5 seconds
ERROR: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/205745?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html> while resolving <Movie:205745:30-jours-max>
Processing Films:   1%|█▋                                                                                                                                                      | 83/7441 [00:01<01:40, 73.39it/s]
Traceback (most recent call last):
  File "/home/USER/PlexTraktSync/main.py", line 6, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/USER/PlexTraktSync/plex_trakt_sync/cli.py", line 22, in cli
    sync()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/USER/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 165, in sync
    sync_all(walker=w, trakt=trakt, plex=plex)
  File "/home/USER/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 81, in sync_all
    for movie in walker.find_movies():
  File "/home/USER/PlexTraktSync/plex_trakt_sync/walker.py", line 71, in find_movies
    movie = self.mf.resolve_any(plex)
  File "/home/USER/PlexTraktSync/plex_trakt_sync/media.py", line 100, in resolve_any
    for guid in pm.guids:
  File "/home/USER/PlexTraktSync/plex_trakt_sync/plex_api.py", line 152, in guids
    guids = [PlexGuid(guid.id, self.type, self) for guid in self.get_guids()]
  File "/home/USER/PlexTraktSync/plex_trakt_sync/decorators/rate_limit.py", line 22, in wrapper
    return fn(*args, **kwargs)
  File "/home/USER/PlexTraktSync/plex_trakt_sync/plex_api.py", line 139, in get_guids
    raise e
  File "/home/USER/PlexTraktSync/plex_trakt_sync/plex_api.py", line 136, in get_guids
    guids = self.item.guids
  File "/home/USER/.local/lib/python3.9/site-packages/plexapi/base.py", line 471, in __getattribute__
    self._reload(_autoReload=True)
  File "/home/USER/.local/lib/python3.9/site-packages/plexapi/base.py", line 350, in _reload
    data = self._server.query(key)
  File "/home/USER/.local/lib/python3.9/site-packages/plexapi/server.py", line 669, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/205745?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
```

**Comment by glensc** [comment]
I've updated #403 to skip faulty entries. Please post the result!

**Comment by Tawagot0** [comment]
> 
> 
> I've updated #403 to skip faulty entries. Please post the result!

Ok thanks!
```
INFO: Documentaires processed in 1.4 seconds
ERROR: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/205745?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html> while resolving <Movie:205745:30-jours-max>
Processing Films:   1%|█▋                                                                                                                                                      | 83/7442 [00:12<18:35,  6.60it/s]
Traceback (most recent call last):
  File "/home/user/PlexTraktSync/plex_trakt_sync/media.py", line 101, in resolve_any
    guids = pm.guids
  File "/home/user/PlexTraktSync/plex_trakt_sync/plex_api.py", line 152, in guids
    guids = [PlexGuid(guid.id, self.type, self) for guid in self.get_guids()]
  File "/home/user/PlexTraktSync/plex_trakt_sync/decorators/rate_limit.py", line 22, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/PlexTraktSync/plex_trakt_sync/plex_api.py", line 139, in get_guids
    raise e
  File "/home/user/PlexTraktSync/plex_trakt_sync/plex_api.py", line 136, in get_guids
    guids = self.item.guids
  File "/home/user/.local/lib/python3.9/site-packages/plexapi/base.py", line 471, in __getattribute__
    self._reload(_autoReload=True)
  File "/home/user/.local/lib/python3.9/site-packages/plexapi/base.py", line 350, in _reload
    data = self._server.query(key)
  File "/home/user/.local/lib/python3.9/site-packages/plexapi/server.py", line 669, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/205745?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/PlexTraktSync/main.py", line 6, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/PlexTraktSync/plex_trakt_sync/cli.py", line 22, in cli
    sync()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 165, in sync
    sync_all(walker=w, trakt=trakt, plex=plex)
  File "/home/user/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 81, in sync_all
    for movie in walker.find_movies():
  File "/home/user/PlexTraktSync/plex_trakt_sync/walker.py", line 71, in find_movies
    movie = self.mf.resolve_any(plex)
  File "/home/user/PlexTraktSync/plex_trakt_sync/media.py", line 103, in resolve_any
    logger.error(f"Skipping {pm}: {e}")
  File "/home/user/PlexTraktSync/plex_trakt_sync/plex_api.py", line 337, in __repr__
    guid = self.guids[0]
IndexError: list index out of range
```

**Comment by glensc** [comment]
Uh, ups. error on formatting. Try again :)

**Comment by Tawagot0** [comment]
Working now thanks!
However I have many series or movies that are skip:


```
ERROR: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/88770?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html> while resolving <Show:88770:Beastars>
ERROR: Skipping <<Show:88770:Beastars>>: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/88770?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
ERROR: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/6721?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html> while resolving <Show:6721:Berserk>
ERROR: Skipping <<Show:6721:Berserk>>: (500) internal_server_error; http://172.20.0.2:32400/library/metadata/6721?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
```

**Comment by glensc** [comment]
yes. These errors are on Plex side. You need to solve it in there.

since PlexTraktSync no longer crashes on invalid entries, this issue will be closed.

you can continue posting details here, how you fixed plex side, may be useful to someone some day.
