### ISSUE TITLE
Errors after updating

### ISSUE THREAD

**Issue by montizzl3** [Taxel/PlexTraktSync#467]
I have been using version 13.14 and realized there have been a lot of updates since then.  When updating to 13.18 the script starts but I get this:

C:\PlexTraktSync-montizzl3 - Copy>main.py
INFO: Syncing with Plex montizzl3 and Trakt montizzl3
Sync Movies: True
Sync Shows: True
INFO: Loaded Trakt lists in 7.1 seconds
Plex Server version: 1.24.0.4930-ab6e1a058, updated at: 2021-09-03 15:15:00
Server has 1 libraries: ['TV Shows']
Processing TV Shows:   0%|                                                                    | 0/1030 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\PlexTraktSync-montizzl3 - Copy\main.py", line 6, in <module>
    cli()
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\cli.py", line 22, in cli
    sync()
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\commands\sync.py", line 131, in sync
    sync_all(walker=w, trakt=trakt, plex=plex, dry_run=dry_run)
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\commands\sync.py", line 40, in sync_all
    runner.sync(walker, listutil, dry_run=dry_run)
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\sync.py", line 21, in sync
    for episode in walker.find_episodes():
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\walker.py", line 88, in find_episodes
    for plex in self.get_plex_shows():
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\walker.py", line 85, in get_plex_shows
    yield from shows
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\walker.py", line 103, in media_from_sections
    yield from it
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\walker.py", line 124, in progressbar
    yield from it
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\plex_api.py", line 389, in items
    for item in self.all(max_items):
  File "C:\PlexTraktSync-montizzl3 - Copy\plex_trakt_sync\plex_api.py", line 369, in all
    key = self.section._buildSearchKey(libtype=libtype, returnKwargs=False)
AttributeError: 'ShowSection' object has no attribute '_buildSearchKey'

I can still run 13.14 but it sometimes errors out at the end.  If I sync only movies or TV it seems to finish, but if I do both it errors out.

**Comment by glensc** [comment]
Dependencies not updated, a point outlined in bug report form:

> 
> Be sure to use required pip packages matching the release, see
> - https://github.com/Taxel/PlexTraktSync#installing
>
