### ISSUE TITLE
Error due to config.default.json missing while running in Docker

### ISSUE THREAD

**Issue by AndreiArdelean1** [Taxel/PlexTraktSync#517]
Using the latest docker image (v 0.14), I get an error while running.

Prior to today's release, everything was working (on v 0.13).

Here is the stack trace: 

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/app/plex_trakt_sync/__main__.py", line 14, in <module>

    from plex_trakt_sync.cli import cli

  File "/app/plex_trakt_sync/cli.py", line 4, in <module>

    from plex_trakt_sync.commands.clear_collections import clear_collections

  File "/app/plex_trakt_sync/commands/clear_collections.py", line 4, in <module>

    from plex_trakt_sync.logging import logger

  File "/app/plex_trakt_sync/logging.py", line 38, in <module>

    initialize()

  File "/app/plex_trakt_sync/logging.py", line 10, in initialize

    log_level = logging.DEBUG if CONFIG['log_debug_messages'] else logging.INFO

  File "/app/plex_trakt_sync/config.py", line 37, in __getitem__

    self.initialize()

  File "/app/plex_trakt_sync/config.py", line 41, in initialize

    defaults = self.load_json(default_config_file)

  File "/app/plex_trakt_sync/config.py", line 73, in load_json

    with open(path, "r") as fp:

FileNotFoundError: [Errno 2] No such file or directory: '/app/plex_trakt_sync/config.default.json'

```

running `ls -1a "/app/plex_trakt_sync/"` prints `. .. __init__.py __main__.py cli.py commands config.py decorators events.py factory.py listener.py logging.py media.py path.py plex_api.py plex_server.py pytrakt_extensions.py style.py sync.py timer.py trakt_api.py trakt_list_util.py version.py walker.py`

**Comment by sirloinofbeef** [comment]
The `config.default.json` file has been relocated to the `plex_trakt_sync` dir in this version.
Please check if the file is present.

**Comment by AndreiArdelean1** [comment]
The `plex_trakt_sync` dir contains `. .. __init__.py __main__.py cli.py commands config.py decorators events.py factory.py listener.py logging.py media.py path.py plex_api.py plex_server.py pytrakt_extensions.py style.py sync.py timer.py trakt_api.py trakt_list_util.py version.py walker.py`.
`config.default.json` is missing

**Comment by glensc** [comment]
@AndreiArdelean1 fix issue title that this is docker specific problem
