### ISSUE TITLE
Version 0.15.0 crashing on a timeout

### ISSUE THREAD

**Issue by Warstomper** [Taxel/PlexTraktSync#527]
### The problem

When running the sync, when it encounters some timeout, Python throws an error and the entire process is halted.

```
Processing Movies   0% ━━━━━━━━━━━━━━━━━━━ 0/835  [ 0:00:00 < -:--:-- , ? it/s ]
Processing Movies   0% ━━━━━━━━━━━━━━━━━━━ 1/835  [ 0:00:01 < -:--:-- , ? it/s ]
Processing Movies   0% ━━━━━━━━━━━━━━━━━━━ 2/835  [ 0:00:02 < 0:10:10 , 1 it/s ]
Processing Movies   0% ━━━━━━━━━━━━━━━━━━━ 3/835  [ 0:00:02 < 0:07:49 , 2 it/s ]
Processing Movies   0% ━━━━━━━━━━━━━━━━━━━ 4/835  [ 0:00:03 < 0:08:30 , 2 it/s ]
Processing Movies   1% ━━━━━━━━━━━━━━━━━━━ 5/835  [ 0:00:04 < 0:08:39 , 2 it/s ]
Processing Movies   1% ━━━━━━━━━━━━━━━━━━━ 6/835  [ 0:00:04 < 0:08:03 , 2 it/s ]
Processing Movies   1% ━━━━━━━━━━━━━━━━━━━ 7/835  [ 0:00:05 < 0:07:38 , 2 it/s ]
Processing Movies   1% ━━━━━━━━━━━━━━━━━━━ 8/835  [ 0:00:05 < 0:07:53 , 2 it/s ]
Processing Movies   1% ━━━━━━━━━━━━━━━━━━━ 9/835  [ 0:00:06 < 0:07:56 , 2 it/s ]
Processing Movies   1% ━━━━━━━━━━━━━━━━━━ 10/835  [ 0:00:06 < 0:08:01 , 2 it/s ]
Processing Movies   1% ━━━━━━━━━━━━━━━━━━ 11/835  [ 0:00:07 < 0:08:06 , 2 it/s ]
Processing Movies   1% ━━━━━━━━━━━━━━━━━━ 12/835  [ 0:00:08 < 0:08:09 , 2 it/s ]
Processing Movies   2% ━━━━━━━━━━━━━━━━━━ 13/835  [ 0:00:08 < 0:08:12 , 2 it/s ]
Processing Movies   2% ━━━━━━━━━━━━━━━━━━ 14/835  [ 0:00:09 < 0:08:10 , 2 it/s ]
Processing Movies   2% ━━━━━━━━━━━━━━━━━━ 15/835  [ 0:00:09 < 0:07:57 , 2 it/s ]
Processing Movies   2% ━━━━━━━━━━━━━━━━━━ 16/835  [ 0:00:10 < 0:08:00 , 2 it/s ]
Processing Movies   2% ━━━━━━━━━━━━━━━━━━ 17/835  [ 0:00:11 < 0:08:05 , 2 it/s ]
Processing Movies   2% ━━━━━━━━━━━━━━━━━━ 18/835  [ 0:00:11 < 0:07:55 , 2 it/s ]
Processing Movies   2% ━━━━━━━━━━━━━━━━━━ 19/835  [ 0:00:12 < 0:07:56 , 2 it/s ]
Processing Movies   2% ━━━━━━━━━━━━━━━━━━ 20/835  [ 0:00:12 < 0:07:59 , 2 it/s ]
Processing Movies   3% ━━━━━━━━━━━━━━━━━━ 21/835  [ 0:00:13 < 0:07:50 , 2 it/s ]
Processing Movies   3% ━━━━━━━━━━━━━━━━━━ 22/835  [ 0:00:13 < 0:07:44 , 2 it/s ]
Processing Movies   3% ━━━━━━━━━━━━━━━━━━ 23/835  [ 0:00:14 < 0:07:47 , 2 it/s ]
Processing Movies   3% ╸━━━━━━━━━━━━━━━━━ 24/835  [ 0:00:14 < 0:07:48 , 2 it/s ]
Processing Movies   3% ╸━━━━━━━━━━━━━━━━━ 25/835  [ 0:00:15 < 0:07:41 , 2 it/s ]
Processing Movies   3% ╸━━━━━━━━━━━━━━━━━ 26/835  [ 0:00:15 < 0:07:35 , 2 it/s ]
Processing Movies   3% ╸━━━━━━━━━━━━━━━━━ 27/835  [ 0:00:16 < 0:07:38 , 2 it/s ]
Processing Movies   3% ╸━━━━━━━━━━━━━━━━━ 28/835  [ 0:00:17 < 0:07:39 , 2 it/s ]
Processing Movies   3% ╸━━━━━━━━━━━━━━━━━ 29/835  [ 0:00:17 < 0:07:34 , 2 it/s ]
Processing Movies   3% ╸━━━━━━━━━━━━━━━━━ 29/835  [ 0:00:18 < 0:07:34 , 2 it/s ]

Processing Movies   3% ╸━━━━━━━━━━━━━━━━━ 29/835  [ 0:00:47 < 0:07:34 , 2 it/s ]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 278, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='XXX-XXX-XXX-XXX.XXX.plex.direct', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plex_trakt_sync/__main__.py", line 16, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/plex_trakt_sync/cli.py", line 23, in cli
    sync()

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/app/plex_trakt_sync/commands/sync.py", line 131, in sync
    sync_all(walker=w, trakt=trakt, plex=plex, dry_run=dry_run)
  File "/app/plex_trakt_sync/commands/sync.py", line 40, in sync_all
    runner.sync(walker, listutil, dry_run=dry_run)
  File "/app/plex_trakt_sync/sync.py", line 17, in sync
    self.sync_ratings(movie, dry_run=dry_run)
  File "/app/plex_trakt_sync/sync.py", line 41, in sync_ratings
    if m.plex_rating is m.trakt_rating:
  File "/app/plex_trakt_sync/media.py", line 92, in plex_rating
    return self.plex.rating
  File "/app/plex_trakt_sync/plex_api.py", line 203, in rating
    return int(self.item.userRating) if self.item.userRating is not None else None
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 471, in __getattribute__
    self._reload(_autoReload=True)
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 350, in _reload
    data = self._server.query(key)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 659, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_cache/session.py", line 116, in request
    return super().request(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_cache/session.py", line 148, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_cache/session.py", line 178, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='XXX-XXX-XXX-XXX.XXX.plex.direct', port=32400): Read timed out. (read timeout=30)`
```
### Expected behavior

For the syncing to continue after a timeout.

### Steps to reproduce the behavior

I have attempted to rerun the sync in various environments (Windows, Linux, Docker), all ending with the same result on the same "number" (29/835).

### Workarounds

Unknown

### Environment

- Docker image

**Comment by glensc** [comment]
@Warstomper see if this branch changes anything:
- https://github.com/Taxel/PlexTraktSync/pull/529

**Comment by Warstomper** [comment]
Can confirm changing these lines of code allows the process to continue with the latest version as well. 
Thanks! 

Unsure what to look for in the debug log in regards to what it's failing on though..
