### ISSUE TITLE
Error on initial scan

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#544]
### The problem

I'm getting an error when doing an initial scan of TV libraries. It happens on the same item each time, which makes me think there is something wrong with that particular TV episode. Before I try removing the episode, I wanted to post here to see if the error message gives any indication what could be going wrong.

```
INFO: Marking as watched in Trakt: <tvdb:6655616:<Episode:257860:Celebrity-Family-Feu-s05e01>>
Processing Reality / Talk / Documentary TV  17% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179/1,073  [ 0:21:03 < 0:51:50 , 0 it/
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/__main__.py", line 16, in <module>
    cli()
  File "/home/bink/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/bink/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/bink/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bink/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bink/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 130, in sync
    sync_all(walker=w, trakt=trakt, plex=plex, runner=factory.sync(), dry_run=dry_run)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 39, in sync_all
    runner.sync(walker, listutil, dry_run=dry_run)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/sync.py", line 23, in sync
    self.sync_watched(episode, dry_run=dry_run)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/sync.py", line 64, in sync_watched
    m.mark_watched_trakt()
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/media.py", line 81, in mark_watched_trakt
    self.trakt_api.mark_watched(self.trakt, self.plex.seen_date)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/decorators/nocache.py", line 14, in inner
    return method(*args, **kwargs)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/decorators/rate_limit.py", line 23, in wrapper
    return fn(*args, **kwargs)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/decorators/time_limit.py", line 18, in wrapper
    return fn(*args, **kwargs)
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/trakt_api.py", line 187, in mark_watched
    self.watched_shows.add(m.show.trakt, m.season, m.number)
AttributeError: 'dict' object has no attribute 'trakt'
```
- Version: [0.14.x]
- Python version: 3.8.10
- Platform: Ubuntu 20.04

**Comment by glensc** [comment]
closing as duplicate. you may want to use workaround specified in that issue

**Comment by BEisem** [comment]
FWIW I just downloaded 0.15.2 and when I run it, the INFO still shows `INFO: PlexTraktSync [0.14.x]`. So with that said, I'm not entirely sure what version I was running before. But I'm trying it now with 0.15.2, which was the latest release available at https://github.com/Taxel/PlexTraktSync/releases.

**Comment by BEisem** [comment]
Also I got the same crash with 0.15.2, on the same episode entry as before...
