### ISSUE TITLE
Error: BadRequest - ekey was not provided

### ISSUE THREAD

**Issue by PlzDontScrobbleMe** [Taxel/PlexTraktSync#550]
### The problem

_A description of what the bug is, including a complete traceback (if applicable)_

whenever i sync, this is happening:

```
INFO: PlexTraktSync [0.15.2-3-g0312394_main]
INFO: Syncing with Plex and Trakt
Sync Movies: True
Sync Shows: True
INFO: Loaded Trakt lists in 3.2 seconds
Plex Server version: 1.24.4.5081-e362dc1ee, updated at: 2021-10-20 11:12:04
Server has 5 libraries: ['Movies', 'Movies 4K', 'Anime', 'Shows', 'Shows 4K']
/app/plex_trakt_sync/walker.py:122: TqdmExperimentalWarning: rich is experimental/alpha
  pb = self._progressbar(iterable, **kwargs)
WARNING: <Movie:1283:Razrazthe1>: Skipping guid local://1283 because provider local has no external Id
Processing Movies 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7  [ 0:00:02 < 0:00:00 , 3 it/s ]
INFO: Movies processed in 3.0 seconds
Processing Movies 4K 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1  [ 0:00:00 < 0:00:00 , ? it/s ]
INFO: Movies 4K processed in 1.3 seconds
Processing Anime  33% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/9  [ 0:00:09 < 0:00:16 , 0 it/s ]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plex_trakt_sync/__main__.py", line 16, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/plex_trakt_sync/commands/sync.py", line 130, in sync
    sync_all(walker=w, trakt=trakt, plex=plex, runner=factory.sync(), dry_run=dry_run)
  File "/app/plex_trakt_sync/commands/sync.py", line 39, in sync_all
    runner.sync(walker, listutil, dry_run=dry_run)
  File "/app/plex_trakt_sync/sync.py", line 21, in sync
    for episode in walker.find_episodes():
  File "/app/plex_trakt_sync/walker.py", line 92, in find_episodes
    yield from self.episode_from_show(show)
  File "/app/plex_trakt_sync/walker.py", line 113, in episode_from_show
    me = self.mf.resolve_any(pe, show.trakt)
  File "/app/plex_trakt_sync/media.py", line 124, in resolve_any
    m = self.resolve_guid(guid, tm)
  File "/app/plex_trakt_sync/media.py", line 154, in resolve_guid
    tm = self.trakt.find_episode_guid(tm, guid)
  File "/app/plex_trakt_sync/trakt_api.py", line 263, in find_episode_guid
    return lookup[guid.pm.season_number][guid.pm.episode_number].instance
  File "/app/plex_trakt_sync/plex_api.py", line 331, in season_number
    return self.item.seasonNumber
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 457, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
  File "/usr/local/lib/python3.10/site-packages/plexapi/video.py", line 869, in seasonNumber
    self._seasonNumber = self.parentIndex if self.parentIndex else self.season().seasonNumber
  File "/usr/local/lib/python3.10/site-packages/plexapi/video.py", line 894, in season
    return self.fetchItem(self.parentKey)
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 169, in fetchItem
    raise BadRequest('ekey was not provided')
plexapi.exceptions.BadRequest: ekey was not provided
ERROR: 1
```
I saw this problem at #385, tried to delete the cache, same result.
all my plex anime library is fully recognized, so i dont know why it crashes. maybe its related to one of the shows? 
here is my last_update.log:
[last_update.log](https://github.com/Taxel/PlexTraktSync/files/7380758/last_update.log)

anyhow imho, itll be better if the exception would be caught instead of crashing the entire thing.
ill live with one missing episode / show :)

### Environment

- Version: 0.15.2-3
- Python version:  XX
- Platform: docker (main - f6d3b743ce6ce8d50f7888114e1cbf5d394c7a85152475156487134216eec029)

**Comment by twolaw** [comment]
Maybe fixed by https://github.com/pkkid/python-plexapi/pull/950
