### ISSUE TITLE
unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by bilyboy785** [Taxel/PlexTraktSync#6]
Hello,

After lunching main.py, I've got this error : 

```
Processing section Divertissement
Traceback (most recent call last):
  File "main.py", line 179, in process_show_section
    eps = lookup[episode.seasonNumber][episode.index]
KeyError: 2019

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 301, in <module>
    main()
  File "main.py", line 286, in main
    process_show_section(section)
  File "main.py", line 220, in process_show_section
    show.title, show.year, episode.seasonNumber, episode.index))
TypeError: unsupported format string passed to NoneType.__format__
```

Do you have any idea ?

**Comment by Taxel** [comment]
Could you enable debug logging in the config (on latest commit) and paste the last couple lines of last_run.log please?

**Comment by bilyboy785** [comment]
```
2019-11-13 11:38:36,997 DEBUG:Show [Burger Quiz (2001)]: Synced episode S03E38
2019-11-13 11:38:36,998 INFO:Show [Burger Quiz (2001)]: Finished sync
2019-11-13 11:38:36,998 DEBUG:Show [The Daily Show Nederlandse Editie (2011)]: Started sync
2019-11-13 11:38:36,998 DEBUG:get: https://api-v2launch.trakt.tv/search?id=228101&id_type=tvdb
2019-11-13 11:38:36,998 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'a5e115aac522077c8e6d1363c8b98b61407defe3770779e77ca0885a6ae32b9e', 'Authorization': 'Bearer 602aaa718dcc2780a24b8f7ccb03a3e89683cc180b73386e55b1ba0d375c89f6'}
2019-11-13 11:38:36,998 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/search?id=228101&id_type=tvdb
2019-11-13 11:38:37,001 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/search?id=228101&id_type=tvdb): <Response [200]>
2019-11-13 11:38:37,001 DEBUG:get: https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/progress/watched
2019-11-13 11:38:37,001 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'a5e115aac522077c8e6d1363c8b98b61407defe3770779e77ca0885a6ae32b9e', 'Authorization': 'Bearer 602aaa718dcc2780a24b8f7ccb03a3e89683cc180b73386e55b1ba0d375c89f6'}
2019-11-13 11:38:37,001 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/progress/watched
2019-11-13 11:38:37,002 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2019-11-13 11:38:37,213 DEBUG:https://api-v2launch.trakt.tv:443 "GET /shows/the-daily-show-nederlandse-editie/progress/watched HTTP/1.1" 200 240
2019-11-13 11:38:37,215 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/progress/watched): <Response [200]>
2019-11-13 11:38:37,216 DEBUG:get: https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/progress/collection
2019-11-13 11:38:37,216 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'a5e115aac522077c8e6d1363c8b98b61407defe3770779e77ca0885a6ae32b9e', 'Authorization': 'Bearer 602aaa718dcc2780a24b8f7ccb03a3e89683cc180b73386e55b1ba0d375c89f6'}
2019-11-13 11:38:37,216 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/progress/collection
2019-11-13 11:38:37,217 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2019-11-13 11:38:37,432 DEBUG:https://api-v2launch.trakt.tv:443 "GET /shows/the-daily-show-nederlandse-editie/progress/collection HTTP/1.1" 200 238
2019-11-13 11:38:37,436 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/progress/collection): <Response [200]>
2019-11-13 11:38:37,474 DEBUG:get: https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/seasons?extended=episodes
2019-11-13 11:38:37,474 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'a5e115aac522077c8e6d1363c8b98b61407defe3770779e77ca0885a6ae32b9e', 'Authorization': 'Bearer 602aaa718dcc2780a24b8f7ccb03a3e89683cc180b73386e55b1ba0d375c89f6'}
2019-11-13 11:38:37,474 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/seasons?extended=episodes
2019-11-13 11:38:37,476 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2019-11-13 11:38:38,152 DEBUG:https://api-v2launch.trakt.tv:443 "GET /shows/the-daily-show-nederlandse-editie/seasons?extended=episodes HTTP/1.1" 200 372
2019-11-13 11:38:38,155 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/shows/the-daily-show-nederlandse-editie/seasons?extended=episodes): <Response [200]>
2019-11-13 11:38:38,156 DEBUG:Show [The Daily Show Nederlandse Editie (2011)]: Generated LUT in 0.6821060180664062 seconds
2019-11-13 11:38:38,179 DEBUG:http://localhost:32400 "GET /library/metadata/16147/allLeaves HTTP/1.1" 200 5960
2019-11-13 11:38:38,208 DEBUG:http://localhost:32400 "GET /library/metadata/16149?checkFiles=1&includeExtras=1&includeRelated=1&includeOnDeck=1&includeChapters=1&includePopularLeaves=1&includeConcerts=1&includePreferences=1 HTTP/1.1" 200 1039
```

Thank's for help, there is the log.

**Comment by Taxel** [comment]
Just to clarify: Are you on the latest commit and are these the last lines on the log before the error shows up?

**Comment by bilyboy785** [comment]
Yes i am, i pulled another time to make sure i'm on the latest commit : OK.

If i run again the main.py : 

```
python3 main.py
Processing section Divertissement
Traceback (most recent call last):
  File "main.py", line 186, in process_show_section
    eps = lookup[episode.seasonNumber][episode.index]
KeyError: 2019

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 309, in <module>
    main()
  File "main.py", line 294, in main
    process_show_section(section)
  File "main.py", line 227, in process_show_section
    show.title, show.year, episode.seasonNumber, episode.index))
TypeError: unsupported format string passed to NoneType.__format__
```

i've just got the last_update.log file without any ERROR.

I've updated config.json with "log_debug_messages": true,

**Comment by chukaism** [comment]
Came here to say getting pretty much the same issue, code for code.

**Comment by Taxel** [comment]
One of you please try the latest commit - if it only logs an error, please paste the line here (should contain "invalid episode")
If the error still occurs the fix needs to occur in a different place so that is useful information, too.

**Comment by bilyboy785** [comment]
It's seems to be good now : 

```
root@srvmedias:/opt/PlexTraktSync  master ✗                                                                        0m ⚑
▶ python3 main.py
Processing section Divertissement
Processing section Documentaires
Processing section Films
Processing section Séries TV
Completed full sync in 3778.3494942188263 seconds
```

**Comment by glensc** [comment]
@bilyboy785 you have leaked your trakt api key here. edit the post to indicate you've acknowledged the problem and delete the API key, as it has been leaked publicly.
