### ISSUE TITLE
Play count gets incremented on Plex for certain movies.

### ISSUE THREAD

**Issue by Rouzax** [Taxel/PlexTraktSync#619]
### The problem

Some movies keep getting an additional play count at the time the plexytraktsync script is run

```
INFO: Marking as watched in Plex: <tmdb:259991:<Movie:121394:Ernst,-Bobbie-en-de->>
INFO: Marking as watched in Plex: <tmdb:324868:<Movie:121395:Ernst,-Bobbie-en-de->>
INFO: Marking as watched in Plex: <tmdb:503676:<Movie:121400:Ernst,-Bobbie-en-de->>
INFO: Marking as watched in Plex: <tmdb:588016:<Movie:121399:Ernst,-Bobbie-en-de->>
INFO: Marking as watched in Plex: <tmdb:508570:<Movie:128712:The-One-and-Only-Iva>>
INFO: Marking as watched in Plex: <tmdb:271525:<Movie:116879:Sprookjesboom-de-Mus>>
INFO: Marking as watched in Plex: <tmdb:391488:<Movie:116878:Sprookjesboom-de-Mus>>
INFO: Marking as watched in Plex: <tmdb:266297:<Movie:116880:Woezel-En-Pip---Alle>>
```

### Error trace

```text
2021-11-23 10:32:12,247 DEBUG[plexapi]:GET https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400/library/metadata/4251?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1
2021-11-23 10:32:12,247 DEBUG[plexapi]:GET https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400/library/metadata/4251?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1
2021-11-23 10:32:12,266 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/266297?type=movie
2021-11-23 10:32:12,266 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'e38bdcc0b831a18ec586500d1581b7f5b38cb786f26f6c32eb9a425b977fda13', 'Authorization': 'Bearer ecb0106eeda7246ae25f1282c5e1149871e6542906c28fb162fd813a9e245ad5'}
2021-11-23 10:32:12,266 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/266297?type=movie
2021-11-23 10:32:12,268 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/266297?type=movie): request: GET https://api-v2launch.trakt.tv/search/tmdb/266297?type=movie, response: 200 (214 bytes), created: 2021-11-23 09:25:01 W. Europe Standard Time, expires: N/A (fresh)
2021-11-23 10:32:12,268 DEBUG[plexapi]:Reloading Movie 'Woezel En Pip - Alles Is Fijn Familiemusical' for attr 'userRating'
2021-11-23 10:32:12,268 DEBUG[plexapi]:Reloading Movie 'Woezel En Pip - Alles Is Fijn Familiemusical' for attr 'userRating'
2021-11-23 10:32:12,268 DEBUG[plexapi]:GET https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400/library/metadata/116880?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1
2021-11-23 10:32:12,268 DEBUG[plexapi]:GET https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400/library/metadata/116880?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1
2021-11-23 10:32:12,277 INFO[PlexTraktSync]:Marking as watched in Plex: <tmdb:266297:<Movie:116880:Woezel-En-Pip---Alle>>
2021-11-23 10:32:12,291 DEBUG[plexapi]:GET https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400/:/scrobble?key=116880&identifier=com.plexapp.plugins.library
2021-11-23 10:32:12,291 DEBUG[plexapi]:GET https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400/:/scrobble?key=116880&identifier=com.plexapp.plugins.library
2021-11-23 10:32:12,315 DEBUG[urllib3.connectionpool]:https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400 "GET /:/scrobble?key=116880&identifier=com.plexapp.plugins.library HTTP/1.1" 200 0
2021-11-23 10:32:12,316 DEBUG[requests_cache.session]:Pre-cache checks for response from https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400/:/scrobble?key=116880&identifier=com.plexapp.plugins.library: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2021-11-23 10:32:12,316 DEBUG[requests_cache.session]:Skipping cache write for URL: https://192-168-2-13.50f5366c69c94499b5515522c37d9ec1.plex.direct:32400/:/scrobble?key=116880&identifier=com.plexapp.plugins.library
2021-11-23 10:32:12,317 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/441130?type=movie
2021-11-23 10:32:12,317 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'e38bdcc0b831a18ec586500d1581b7f5b38cb786f26f6c32eb9a425b977fda13', 'Authorization': 'Bearer ecb0106eeda7246ae25f1282c5e1149871e6542906c28fb162fd813a9e245ad5'}
2021-11-23 10:32:12,317 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/441130?type=movie
2021-11-23 10:32:12,322 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/441130?type=movie): request: GET https://api-v2launch.trakt.tv/search/tmdb/441130?type=movie, response: 200 (157 bytes), created: 2021-11-23 10:32:12 W. Europe Standard Time, expires: N/A (fresh)
```

### Expected behavior

To not keep adding play count

### Inspect of problematic items

```text
Here is 1 of the movies where it happens to.

PS C:\Users\SA-Download> plextraktsync inspect 116880
PlexTraktSync [0.16.5]

Inspecting 116880: <tmdb:266297:<Movie:116880:Woezel-En-Pip---Alle>>
URL: https://app.plex.tv/desktop/#!/server/727f2769aad8b0f031dfe0540695d8b261dd4943/details?key=/library/metadata/116880
Media.Type: movie
Media.Guid: 'plex://movie/5d776ff77a53e9001e79979d'
Media.Guids: [<Guid:tmdb://266297>]
Audio: 'stereo', 'Nederlands (AAC Stereo)'
Video: 'h264'
Guids:
  Guid: tmdb://266297, Id: 266297, Provider: tmdb
Metadata: {'collected_at': '2018-07-21:T10:00:34.000Z', 'media_type': 'digital', 'resolution': 'sd_480p', 'audio': 'aac', 'audio_channels': '2.0'}
Trakt: https://trakt.tv/movies/164868
Watched on Plex: True
Watched on Trakt: True
Play history:
- None by USER with DOWNLOAD on PlexTraktSync
- None by USER with DOWNLOAD on PlexTraktSync
- None by USER with DOWNLOAD on PlexTraktSync
- None by USER with DOWNLOAD on PlexTraktSync
- None by USER with DOWNLOAD on PlexTraktSync
```

### Install method

pipx (Recommended)

### Version

0.16.5

### Python Version

3.9.7

### Operating System and Version

Microsoft Server 2019

**Comment by twolaw** [comment]
You should continue in this issue you already opened about it :
- https://github.com/Taxel/PlexTraktSync/issues/450

so helpers can know your history. Or at least refer to it.

**Comment by Rouzax** [comment]
I created a new one because this was a clean install from scratch using the pipx installation method, but I should have referred to it indeed.

**Comment by Rouzax** [comment]
Most of these are part of Kids Movies library, the Plex Agent Settings are using `Plex Movie` agent
![image](https://user-images.githubusercontent.com/4103090/143841112-84ed0bb2-c5dc-45aa-8f97-6a50875c267e.png)

Have looked at this comment https://github.com/Taxel/PlexTraktSync/issues/450#issuecomment-903857252 but as far as I can see Plex is already leveraging the new `Plex Movie` agent.
There is a Plex article on switching agent, but that menu does not show for me
https://support.plex.tv/articles/upgrading-a-movie-library-to-the-use-the-new-plex-movie-agent/
![image](https://user-images.githubusercontent.com/4103090/143841520-567afa82-9a6a-4c4c-95c4-221691eba300.png)

**Comment by twolaw** [comment]
Your Plex play history is quite strange.
Can you investigate this ? Are other movies or tv shows identical?
```
Play history:
- None by USER with DOWNLOAD on PlexTraktSync
- None by USER with DOWNLOAD on PlexTraktSync
- None by USER with DOWNLOAD on PlexTraktSync
- None by USER with DOWNLOAD on PlexTraktSync
- None by USER with DOWNLOAD on PlexTraktSync
```

**Comment by Rouzax** [comment]
> Your Plex play history is quite strange. Can you investigate this ? Are other movies or tv shows identical?
> 
> ```
> Play history:
> - None by USER with DOWNLOAD on PlexTraktSync
> - None by USER with DOWNLOAD on PlexTraktSync
> - None by USER with DOWNLOAD on PlexTraktSync
> - None by USER with DOWNLOAD on PlexTraktSync
> - None by USER with DOWNLOAD on PlexTraktSync
> ```

Sorry for the late reply. I did anonymize the USER account. Those play histories keep getting added each time plextraktsync runs

Here is one that has normal play count
```
PS C:\Users\SA-Download> plextraktsync inspect 131988
PlexTraktSync [0.16.5]

Inspecting 131988: <tmdb:337404:<Movie:131988:Cruella>>
URL: https://app.plex.tv/desktop/#!/server/727f2769aad8b0f031dfe0540695d8b261dd4943/details?key=/library/metadata/131988
Media.Type: movie
Media.Guid: 'plex://movie/5d776b99ad5437001f7a47db'
Media.Guids: [<Guid:imdb://tt3228774>, <Guid:tmdb://337404>, <Guid:tvdb://70925>]
Audio: '7.1', 'English (TRUEHD 7.1)'
Video: 'hevc'
Guids:
  Guid: tmdb://337404, Id: 337404, Provider: tmdb
  Guid: tvdb://70925, Id: 70925, Provider: tvdb
  Guid: imdb://tt3228774, Id: tt3228774, Provider: imdb
Metadata: {'collected_at': '2021-08-15:T02:34:27.000Z', 'media_type': 'digital', 'resolution': 'uhd_4k', 'hdr': 'hdr10', 'audio': 'dolby_truehd', 'audio_channels': '7.1'}
Trakt: https://trakt.tv/movies/218008
Watched on Plex: True
Watched on Trakt: True
Play history:
- 2021-06-21 16:03:53 by <USERNAME> with DOWNLOAD on PlexTraktSync
```

**Comment by mvanbaak** [comment]
I see exactly the same problem with random movies in my library. All known 'big' movies.

The workaround I use is to delete the file `trakt_cache.sqlite` before every run.
It makes the sync very slow, but at least I dont get those duplicated history items on the movies.

I started testing plextraktsync 2 months ago, saw this behaviour, and retested today and it's still happening with latest code in the main branch

**Comment by animosity22** [comment]
I think I've nailed down the root cause for me anyway.

If I have a movie on Plex and I sync and that movie was matched wrong and I update it, it continues to mark it as played.

I had to redo my library a few times and it was consistently movies that I had to fix.

Once I cleared my local cache and my library was properly matched up, I didn't get those repeat items anymore.

So I'd imagine something is getting out of sync with the locale cache/trakt as it thinks it's marking a movie that is not played but on the plex side, it got changed.

**Comment by glensc** [comment]
The underlying problem is that pts has cached state that item is not played, and continues to add a play.

You can try inspecting cache with the `cache` subcommand, see `plextraktsync cache --help` for usage. Use `--sort` and `--limit` options to find your API url and add `URL` argument too see cached url content.

**Comment by animosity22** [comment]
Here is the order of operations to reproduce the problem:

- Have a 'bad' match on a movie
- Mark it watched in Plex
- Run PTS and let Sync
- Validate it's right movie on Trakt and it is already marked watched
- Fix Match in Plex
- Rerun PTS and it tries to remark the movie since it looks not matched but in reality, it's not the same movie

So in my example:

```
INFO: Marking as watched in Plex: <tmdb:543917:<Movie:109832:Bloodline>>
```

Kept marking over and over and I eventually deleted the cache after fixing the match and no issues at all now.

**Comment by Rouzax** [comment]
I started from scratch and didn't have a cache yet and still have the issue.
Will try later today to delete the cache and try it again.

**Comment by glensc** [comment]
@Rouzax find the item's xml in cache, maybe gives some idea what is happening

@animosity22 unclear what is "bad match"? give details how to reproduce this locally.

also, you can sync only specific item with `--id=109832`, then the cache is smaller, also is it reproducible with id search?

**Comment by animosity22** [comment]
A bad match - Just meaning in Plex, have a movie matched wrong, sync and fix the match afterwards in Plex.

**Comment by Rouzax** [comment]
> The underlying problem is that pts has cached state that item is not played, and continues to add a play.
> 
> You can try inspecting cache with the `cache` subcommand, see `plextraktsync cache --help` for usage. Use `--sort` and `--limit` options to find your API url and add `URL` argument too see cached url content.

Sorry, I need a little more help to do what you need 😄 
Have an export of the entire cache sorted by URL but not sure what we are after

**Comment by twolaw** [comment]
@animosity22 can you explain [order of operations](https://github.com/Taxel/PlexTraktSync/issues/619#issuecomment-991837404) with an example and much more details. I don't understand what you mean by "right movie on Trakt". And why a "bad match in Plex" would mark the "right movie in trakt".

**Comment by animosity22** [comment]
Sure.

1) Add movie to Plex
2) Match it with the wrong/bad/incorrect movie name (This happens at times with Plex natively)
3) Mark Watched on Plex
4) PTS
5) On Plex, correct the match to the proper movie name
6) Validate Trakt shows Movie as watched
7) PTS - This keeps marking that movie in Plex as watched over and over

I'd guess it's because the URL in Plex hasn't changed but the movie has. Not sure, but that was a way I could reproduce the issue.

**Comment by twolaw** [comment]
This is not an example because you don't give movies names. On step 4, which trakt movie gets a watched status?

**Comment by animosity22** [comment]
> This is not an example because you don't give movies names.

You asked for a generic flow and that's what I gave. The 'movie' can be any movie you like.

> On step 4, which trakt movie gets a watched status?

The same 'movie' you choose on step 1.

> And what happen if you mark it unwatched on trakt just after you match the correct movie on plex?

I haven't tried that yet as I can step through that.

**Comment by animosity22** [comment]
> also, you can sync only specific item with `--id=109832`, then the cache is smaller, also is it reproducible with id search?

I get an error when I try that.

```
felix@gemini:~$ plextraktsync sync --id=118925
INFO: PlexTraktSync [0.17.0]
Traceback (most recent call last):
  File "/home/felix/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 101, in sync
    w.print_plan(print=tqdm.write)
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/walker.py", line 195, in print_plan
    if self.plan.movie_sections:
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/walker.py", line 192, in plan
    return WalkPlanner(self.plex, self.config).plan()
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/walker.py", line 73, in plan
    movies, shows, episodes = self.find_by_id(movie_sections, show_sections)
  File "/home/felix/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/walker.py", line 94, in find_by_id
    results = defaultdict(list[Movie, Show, Episode])
TypeError: 'type' object is not subscriptable
felix@gemini:~$
```

**Comment by glensc** [comment]
> ```
>     results = defaultdict(list[Movie, Show, Episode])
> TypeError: 'type' object is not subscriptable
> ```

looks like python 3.8 is no longer supported.

try changing that line to:
```py
    results = defaultdict(list)
```

**Comment by animosity22** [comment]
> ```python
>   results = defaultdict(list)
> ```

That fixed it.

```
felix@gemini:~$ plextraktsync sync --id=118925
INFO: PlexTraktSync [0.17.0]
Sync Movies: [<Movie:118925:The-Apartment>]
Processing movies 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1  [ 0:00:01 < 0:00:00 , ? it/s ]
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 1.7 seconds
```

**Comment by twolaw** [comment]
> You asked for a generic flow and that's what I gave. The 'movie' can be any movie you like.

No, I asked an example. Example is the opposite of generic.
Is that so difficult to detail each step with movies names? To identify precisely the consequences of the name mismatch.

> > On step 4, which trakt movie gets a watched status?
> 
> The same 'movie' you choose on step 1.

Ok so if the correct movie (from step 1) is synced to trakt (step 4) even if you matched it with an incorrect movie name (step 2), this means Plex guids are correct (even after step 2) and only Plex movie name is incorrect. I doubt that. I ask you again : give example with names at each step.


> > And what happen if you mark it unwatched on trakt just after you match the correct movie on plex?
> 
> I haven't tried that yet as I can step through that.

Please try.


> The underlying problem is that pts has cached state that item is not played, and continues to add a play.

Watched status are not cached. Quite a challenging issue.

**Comment by animosity22** [comment]
> Is that so difficult to detail each step with movies names?

Sorry as I misunderstand so I guess it is. Good luck as I'm checking out as I was trying to help.

**Comment by glensc** [comment]
Without providing steps to reproduce it's difficult (read: impossible) for developers to digest the problem.

Try thinking out of the box, make a reproducer to someone who has no access or information of your setup. Perhaps start blank Plex Server and export the library:
-  https://github.com/Taxel/PlexTraktSync/blob/HEAD/CONTRIBUTING.md#sharing-plex-media-server-database

I personally see no relation to "wrong" vs "good" match being the problem, you may be just seeing the symptom of id being changed, which means there's no previous cache because the specific id was never "seen" by PlexTraktSync.

**Comment by Rouzax** [comment]
> > The underlying problem is that pts has cached state that item is not played, and continues to add a play.
> > You can try inspecting cache with the `cache` subcommand, see `plextraktsync cache --help` for usage. Use `--sort` and `--limit` options to find your API url and add `URL` argument too see cached url content.
> 
> Sorry, I need a little more help to do what you need 😄 Have an export of the entire cache sorted by URL but not sure what we are after

To quote myself, please let me know what exactly you want me to test and happy to do so.

**Comment by glensc** [comment]
> To quote me, please let me know what exactly you want me to test and happy to do so.

I don't have exact instructions, as don't even have the IDs of the problem (no reproducer).

since I can't reproduce this locally, the instructions will be: find the problematic request yourself.

1. `plextraktsync cache --limit=0` -> find some plex urls
2. `plextraktsync cache 'https://xxx.plex.direct:12521/status/sessions/history/all?metadataItemID=15981&sort=viewedAt%3Adesc&X-Plex-Container-Size=100&X-Plex-Container-Start=0'` -> show that request content

In general, inspect the cache, find your problematic id and its XML and see if you find something suspicious with the data.

if you can reproduce with an empty cache and use `--id=` to sync, it would likely be most easier to identify the problem.

how pts works is:
1. find libraries: `/library`, `/library/sections`
2. ask XML of the library: `/library/sections/1/all`
3. iterate over each item, python-plex may be making additional requests here depending on agent type and some other unknown reasons.

you can also see what exact requests it makes from debug log if you enable debugging from `config.json`

also, now I've realized what none of you have tried: downgrade and find since what version this problem starts with?

**Comment by Rouzax** [comment]
Will do these steps and report back. Hopefully today.

**Comment by glensc** [comment]
@Rouzax there are your trakt api keys in bugreport. edit the bugreport and confiscate to indicate you've understood the problem. and you should delete those keys and recreate the tokens.

**Comment by Rouzax** [comment]
@glensc Good catch, I missed that one.
To my knowledge there is no process to remove API app from Trakt, right?

PS: Not sure what you mean with confiscate, I suspect remove from the post?

**Comment by twolaw** [comment]
Keep in mind that Trakt token expires after 3 months. It is refreshed automatically, so your current token is safe.

**Comment by glensc** [comment]
I meant obfuscate/redact, not sure how auto-correct managed to fill confiscate there :D maybe it was late and it was I who typed it. who knows.
