### ISSUE TITLE
Crash every run. Data of git clone 8/27

### ISSUE THREAD

**Issue by gorgarp** [Taxel/PlexTraktSync#64]
Every time running after initial config throws these errors:

Starting sync Plex {{{{{Email}}}}}} and Trakt {{{{{username}}}}}
Traceback (most recent call last):
  File "./main.py", line 342, in <module>
    main()
  File "./main.py", line 285, in main
    trakt_watched_shows = pytrakt_extensions.allwatched()
  File "/usr/local/lib/python3.8/site-packages/trakt/core.py", line 539, in inner
    json_data = self._handle_request('get', url)
  File "/usr/local/lib/python3.8/site-packages/trakt/core.py", line 519, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by gorgarp** [comment]
Traceback (most recent call last):
  File "./main.py", line 342, in <module>
    main()
  File "./main.py", line 285, in main
    trakt_watched_shows = pytrakt_extensions.allwatched()
  File "/usr/local/lib/python3.8/site-packages/trakt/core.py", line 539, in inner
    json_data = self._handle_request('get', url)
  File "/usr/local/lib/python3.8/site-packages/trakt/core.py", line 516, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.TraktInternalException: Internal Server Error

**Comment by twolaw** [comment]
It happens sometimes when Trakt servers don't answer properly.
I tried a sync just now and I get the same error.
Just wait and retry later.

**Comment by gorgarp** [comment]
@twolaw you are right. My apologies. They had a window but only posted on twitter...
