### ISSUE TITLE
JSONDecodeError when processing movies

### ISSUE THREAD

**Issue by montizzl3** [Taxel/PlexTraktSync#66]
When I run this script it does work for awhile and then I get the following:

"Processing section Movies
Traceback (most recent call last):
  File "C:\PlexTraktSync\main.py", line 342, in <module>
    main()
  File "C:\PlexTraktSync\main.py", line 322, in main
    process_movie_section(
  File "C:\PlexTraktSync\main.py", line 65, in process_movie_section
    search = trakt.sync.search_by_id(x, id_type=provider)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\trakt\core.py", line 539, in inner
    json_data = self._handle_request('get', url)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\trakt\core.py", line 519, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Monte\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

When this happens it stops and it never makes it to TV Shows or lists.  It is making progress prior to getting this error because I see movies added to my collection in Trakt that are on my Plex server.

Anyone know what any of these errors mean, or more importantly, how to fix them?

**Comment by twolaw** [comment]
That's because Trakt sometimes doesn't reply correctly to all requests.
And the script doesn't handle those errors, so it crashes completely.
I will take a look to make it more robust... by catching more exceptions.

**Comment by montizzl3** [comment]
OK, thank you.  If that's all it is then I'll just rerun it every so often.  Each time I run it it seems to make some more progress.  I do have a pretty large collection so it's slowly making it through it.  Maybe once it gets everything it will get through subsequent updates more quickly without crashing.

**Comment by twolaw** [comment]
Yes, the first run is slow because it has to search each movie in trakt db, next ones will be faster thanks to the cache file.

**Comment by twolaw** [comment]
I fixed it.
Try with this `main.py` file : https://github.com/twolaw/PlexTraktSync/blob/bypass-requests-error/main.py

**Comment by montizzl3** [comment]
Thanks!  It made it through Movies and now it's rocking and rolling on TV Shows.  We'll see how long this takes.

**Comment by montizzl3** [comment]
Boom!  Completed full sync in 3474.5 seconds.  Thanks for your help!!
