### ISSUE TITLE
Error on sync: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by arude** [Taxel/PlexTraktSync#685]
On Ubuntu 21.11
Ran from pipx install on terminal w/o arguments. What else can I post to ease debugging?

```
INFO: Updated Trakt collection: {'added': {'episodes': 1}}
INFO: To be added to collection: <tmdb:62242:<Episode:15156:The-Simpsons-s02e10>>
Processing Series  76% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174/229  [ 2:58:42 < -:--:-- , ? it/s ]
Traceback (most recent call last):
  File "/home/adrian/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/cli.py", line 23, in cli
    sync()
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/commands/sync.py", line 110, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/sync.py", line 75, in sync
    self.sync_collection(episode, dry_run=dry_run)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/sync.py", line 96, in sync_collection
    m.add_to_collection()
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/media.py", line 65, in add_to_collection
    self.trakt_api.add_to_collection(self.trakt, self.plex)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_api.py", line 199, in add_to_collection
    self.batch.add_to_collection(m.media_type, item)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_api.py", line 335, in add_to_collection
    self.flush()
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_api.py", line 325, in flush
    self.submit_collection()
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/decorators/rate_limit.py", line 23, in wrapper
    return fn(*args, **kwargs)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/decorators/time_limit.py", line 18, in wrapper
    return fn(*args, **kwargs)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_api.py", line 303, in submit_collection
    result = self.trakt_sync_collection(self.collection)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_api.py", line 339, in trakt_sync_collection
    return trakt.sync.add_to_collection(media_object)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/trakt/core.py", line 587, in inner
    json_data = self._handle_request('post', url, data=args)
  File "/home/adrian/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/trakt/core.py", line 532, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by glensc** [comment]
enable debug and see what was last trakt request

**Comment by glensc** [comment]
perhaps your account is locked     out like here:
- https://github.com/Taxel/PlexTraktSync/issues/579

**Comment by arude** [comment]
I tried to reproduce the problem and the whole sync went through now without any issue. I don't know what it was, but I don't think I'll be able to reproduce the problem. Thank you for your time.

**Comment by glensc** [comment]
The error came from trakt website, and such error is given if the HTTP status code is not recognized by trakt python library. so in such cases library needs to be improved, like this:
- https://github.com/moogar0880/PyTrakt/pull/163
