### ISSUE TITLE
Error Decoding? or Rate Limit?

### ISSUE THREAD

**Issue by justinglock40** [Taxel/PlexTraktSync#708]
### The problem

Not sure exact problem, posting to get help with error. I saw some stuff about decoding error, but also rate limit error. Just looking for help to determine actual error. This panic happened after it had run through all libraries and got through about 20% of the last library (TV Shows)

### Error trace

```text
Traceback (most recent call last):
  File "/home/jwashington/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 110, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/sync.py", line 75, in sync
    self.sync_collection(episode, dry_run=dry_run)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/sync.py", line 96, in sync_collection
    m.add_to_collection()
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/media.py", line 65, in add_to_collection
    self.trakt_api.add_to_collection(self.trakt, self.plex)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 199, in add_to_collection
    self.batch.add_to_collection(m.media_type, item)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 335, in add_to_collection
    self.flush()
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 325, in flush
    self.submit_collection()
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/rate_limit.py", line 23, in wrapper
    return fn(*args, **kwargs)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/time_limit.py", line 18, in wrapper
    return fn(*args, **kwargs)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 303, in submit_collection
    result = self.trakt_sync_collection(self.collection)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 339, in trakt_sync_collection
    return trakt.sync.add_to_collection(media_object)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 587, in inner
    json_data = self._handle_request('post', url, data=args)
  File "/home/jwashington/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 532, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Expected behavior

No panics

### Inspect of problematic items

```text
unknown
```

### Workarounds

Unknown

### Install method

pipx (Recommended)

### Version

0.18.3

### Python Version

3.8.10

### Operating System and Version

Linux 20.04

**Comment by glensc** [comment]
Same as other "json.decoder.JSONDecodeError" issues:
- https://github.com/Taxel/PlexTraktSync/search?q=%22json.decoder.JSONDecodeError%22+is%3Aissue&type=issues

this is problem on trakt.tv api side, and need debug log what last trakt.tv request that might had been.

**Comment by glensc** [comment]
For example most recent one:
- https://github.com/Taxel/PlexTraktSync/issues/685

but since you use pipx and 0.18.3 can exclude that your account is locked error as that should be handled now:
- https://github.com/Taxel/PlexTraktSync/pull/581

**Comment by glensc** [comment]
Example debug log which lead to conclusion status 423 not handled by trakt API client:
- https://github.com/Taxel/PlexTraktSync/issues/579#issuecomment-961990366

**Comment by justinglock40** [comment]
Hmm. Ok, I'm rerunning now. and it has progressed passed that point for now with no issues. So maybe one of those issues did apply? Thanks for the responses.

**Comment by glensc** [comment]
As I said. it's error coming from trakt.tv site, to be able to understand the problem, need details what the request was and what was the response given by trakt.tv api.
