### ISSUE TITLE
ReadTimeoutError on Plex request

### ISSUE THREAD

**Issue by gitttt54** [Taxel/PlexTraktSync#742]
### The problem

Every time, I run plextraktsync I get a traceback.

Movies seem to get processed fine.

I have no idea what caused the issue, nor, what I can report to help.

```
/app # plextraktsync info
PlexTraktSync Version: 0.18.11
Python Version: 3.10.0 (default, Nov 13 2021, 03:43:50) [GCC 10.2.1 20201203]
Plex API Version: 4.8.0
Trakt API Version: 3.4.0
Cache Dir: /app/config
Config Dir: /app/config
Log Dir: /app/config
Plex username: myplexusername
Trakt username: mytraktusername
Plex Server version: 1.25.3.5409-f11334058, updated at: 2022-01-23 00:24:48
Enabled 2 libraries in Plex Server: ['Movies', 'Series']
/app # 
```

### Error trace

```text
INFO: Rating <tmdb:1276153:<Episode:26579:American-Gods-s01e01>> with 9 on Plex
Processing Series   4% ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55/1,334  [ 0:03:24 < 1:08:27 , 0 it/s ]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 278, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='91-41-59-112.7aec5c30ac8047b79882085e9f4bd190.plex.direct', port=32241): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 16, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/plextraktsync/cli.py", line 23, in cli
    sync()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 110, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 72, in sync
    self.sync_ratings(episode, dry_run=dry_run)
  File "/app/plextraktsync/sync.py", line 113, in sync_ratings
    m.plex_rate()
  File "/app/plextraktsync/media.py", line 134, in plex_rate
    self.plex_api.rate(self.plex.item, self.trakt_rating)
  File "/app/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/app/plextraktsync/plex_api.py", line 541, in rate
    m.rate(rating)
  File "/usr/local/lib/python3.10/site-packages/plexapi/mixins.py", line 229, in rate
    self._server.query(key, method=self._server._session.put)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 659, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_cache/session.py", line 116, in request
    return super().request(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_cache/session.py", line 148, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_cache/session.py", line 178, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='91-41-59-112.7aec5c30ac8047b79882085e9f4bd190.plex.direct', port=32241): Read timed out. (read timeout=30)
/app #
```

### Expected behavior

No Errors :-)

### Steps to reproduce the behavior

I just start `plextraktsync` via console in a started docker on unraid.

### Inspect of problematic items

```text
/app # plextraktsync inspect
PlexTraktSync [0.18.11]
/app #
```

### Install method

docker-compose

### Version

0.18.11

### Python Version

3.10.0

### Operating System and Version

Unraid 6.9.2

**Comment by glensc** [comment]
Your plex server gives timeout, you may check the plex server logs

**Comment by glensc** [comment]
See this comment on how to increase timeout:
- https://github.com/Taxel/PlexTraktSync/issues/9#issuecomment-558216283

**Comment by gitttt54** [comment]
> See this comment on how to increase timeout:
> 
>     * [Timeout #9 (comment)](https://github.com/Taxel/PlexTraktSync/issues/9#issuecomment-558216283)

Modifying the `plex_trakt_sync.sh` is nothing, I'd like to do, because it'll overwritten by the next update anyways.
I'm confident, that the added "retry" will work :-) Thank you!

**Comment by glensc** [comment]
Pardon, where do you read modifying plex_trakt_sync.sh script? please copy out the text

**Comment by gitttt54** [comment]
Finally, looking at the file plex_trakt_sync.sh, I copied the 3rd line python3 ./main.py and everything worked!

> Pardon, where do you read modifying plex_trakt_sync.sh script? please copy out the text

"Finally, looking at the file plex_trakt_sync.sh, I copied the 3rd line python3 ./main.py and everything worked!"

**Comment by glensc** [comment]
But I linked to a specific comment:
- https://github.com/Taxel/PlexTraktSync/issues/9#issuecomment-558216283

it directs to plexapi documentation where you can configure timeout. only that comment. everything else in that issue is useless noise.
