### ISSUE TITLE
TypeError: Invalid first argument to register(). ForwardRef('CachedResponse') is not a class.

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#745]
### Discussed in https://github.com/Taxel/PlexTraktSync/discussions/740

<div type='discussions-op-text'>

<sup>Originally posted by **eyarea51** January 22, 2022</sup>
**Update**
I have attempted to use python version 3.9 and the latest 3.10.2
I have tried different versions of plextraktsync all the way down to 16.5
I have attempted this on a Windows 10 and windows 11 device 

Nothing I do ever gets past the setup Any Help would be great as I am not a python programmer but do understand coding.

I had to re install windows 10 on my Plex Media Server and now when I do the setup I get past the scheduling and the requirements install the command prompt window goes away instead of going though and connecting to my plex server and trakt.  I run the plextraktsync.bat and the command prompt widow opens and some text flash by and then closes.

I placed a Pause after the line `python -m plextraktsync %*` to see what is happening and the following text shows on the screen

```
Traceback (most recent call last):
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\PlexTraktSync\plextraktsync\__main__.py", line 14, in <module>
    from plextraktsync.cli import cli
  File "C:\PlexTraktSync\plextraktsync\cli.py", line 3, in <module>
    from plextraktsync.commands.cache import cache
  File "C:\PlexTraktSync\plextraktsync\commands\cache.py", line 4, in <module>
    from requests_cache import CachedSession
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_cache\__init__.py", line 43, in <module>
    from .backends import *
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_cache\backends\__init__.py", line 8, in <module>
    from .base import BaseCache, BaseStorage
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_cache\backends\base.py", line 18, in <module>
    from ..serializers import init_serializer
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_cache\serializers\__init__.py", line 6, in <module>
    from .preconf import (
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_cache\serializers\preconf.py", line 26, in <module>
    base_stage = CattrStage()  #: Base stage for all serializer pipelines
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_cache\serializers\cattrs.py", line 32, in __init__
    self.converter = init_converter(factory)
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_cache\serializers\cattrs.py", line 67, in init_converter
    converter.register_structure_hook(
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\cattr\converters.py", line 269, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\site-packages\cattr\dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "C:\Users\eyare\AppData\Local\Programs\Python\Python310\lib\functools.py", line 856, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. ForwardRef('CachedResponse') is not a class.
```
</div>

**Comment by glensc** [comment]
Fixed in 0.18.13
