### ISSUE TITLE
Immediate crash when running plextraktsync 0.8.17

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#781]
### The problem

Immedately crashes when trying to run `plextraktsync`

### Error trace

```text
INFO: PlexTraktSync [0.18.17]
Traceback (most recent call last):
  File "/home/bink/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/cli.py", line 46, in cli
    sync()
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 34, in sync
    wc = factory.walk_config().update(movies=movies, shows=shows)
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/factory.py", line 95, in walk_config
    from plextraktsync.walker import WalkConfig
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/walker.py", line 177, in <module>
    class Walker:
  File "/home/bink/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/walker.py", line 249, in Walker
    def walk_shows(self, shows: set[Media], title="Processing Shows"):
TypeError: 'type' object is not subscriptable
```

### Expected behavior

Should not crash

### Steps to reproduce the behavior

I installed plextraktsync via pipx. On first run, I went through logins for Plex and trakt. Everything worked correctly until installation was complete, then the traceback displayed and it crashed.

Afterwards, any time I run `plextraktsync` it immediately crashes with the traceback being displayed.

### Workarounds

Roll back to 0.18.16

### Install method

pipx (Recommended)

### Version

0.18.17

### Python Version

3.8.10

### Operating System and Version

Ubuntu 20.04

**Comment by BEisem** [comment]
Update ... I force installed 0.18.16 using `pipx install PlexTraktSync==0.18.16 --force` and now it seems to be working. So the error must exist somewhere in 0.18.17.

**Comment by hdecoded** [comment]
can confirm the same issue on 0.18.17.

**Comment by glensc** [comment]
okay, perhaps you can avoid brain bomb and update the title what version breaks?

**Comment by BEisem** [comment]
Not sure what "brain bomb" means, but ok, just updated the title.
