### ISSUE TITLE
Error: watchlist_movies throws NotFoundException: Not Found - method exists, but no record found

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#790]
### Discussed in https://github.com/Taxel/PlexTraktSync/discussions/789

<div type='discussions-op-text'>

<sup>Originally posted by **dik23** February  8, 2022</sup>
I've installed with pipx and the app seems to be working

```
> plextraktsync info
PlexTraktSync Version: 0.18.18
Python Version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
Plex API Version: 4.9.1
Trakt API Version: 3.4.0
Cache Dir: /home/dik/.cache/PlexTraktSync
Config Dir: /home/dik/.config/PlexTraktSync
Log Dir: /home/dik/.cache/PlexTraktSync/log
Plex username: ****
Trakt username: ****
Plex Server version: 1.25.5.5492-12f6b8c83, updated at: 2022-02-08 11:25:34
Enabled 12 libraries in Plex Server: ['Dad', 'Films', 'Johnsons', 'Requested Films', 'Brian', 'Documentaries', 'Naked and Afraid', 'Requested TV', 'TV Series', 'Music', 'Photos', 'Home Videos']
```

However sync doesn't seem to work

```
> plextraktsync sync
INFO: PlexTraktSync [0.18.18]
Sync Movie sections: [<PlexLibrarySection:movie:Dad>, <PlexLibrarySection:movie:Films>, <PlexLibrarySection:movie:Johnsons>, <PlexLibrarySection:movie:Requested Films>, <PlexLibrarySection:movie:Home Videos>]
Sync Show sections: [<PlexLibrarySection:show:Brian>, <PlexLibrarySection:show:Documentaries>, <PlexLibrarySection:show:Naked and Afraid>, <PlexLibrarySection:show:Requested TV>, <PlexLibrarySection:show:TV Series>]
Traceback (most recent call last):
  File "/home/dik/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/sync.py", line 57, in sync
    if self.config.trakt_to_plex["watchlist"] and trakt.watchlist_movies:
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/rate_limit.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 170, in watchlist_movies
    return self.me.watchlist_movies
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 552, in inner
    json_data = self._handle_request('get', url)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 529, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found
```

What have I missed?
</div>

**Comment by glensc** [comment]
@dik23: Any ideas why API call to fetch your watchlist_movies on trakt.tv gives 404?

**Comment by glensc** [comment]
As a workaround you can disable watchlist syncing from config.

**Comment by dik23** [comment]
Have now set to false, config.json here :  https://pastebin.com/ERq4X3ch

> plextraktsync sync --dry-run
INFO: PlexTraktSync [0.18.18]
Sync Movie sections: [<PlexLibrarySection:movie:Dad>, <PlexLibrarySection:movie:Films>, <PlexLibrarySection:movie:Johnsons>, <PlexLibrarySection:movie:Requested Films>, <PlexLibrarySection:movie:Home Videos>]
Sync Show sections: [<PlexLibrarySection:show:Brian>, <PlexLibrarySection:show:Documentaries>, <PlexLibrarySection:show:Naked and Afraid>, <PlexLibrarySection:show:Requested TV>, <PlexLibrarySection:show:TV Series>]
Enabled dry-run mode: not making actual changes
Traceback (most recent call last):
  File "/home/dik/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/sync.py", line 57, in sync
    if self.config.trakt_to_plex["watchlist"] and trakt.watchlist_movies:
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/rate_limit.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 170, in watchlist_movies
    return self.me.watchlist_movies
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 552, in inner
    json_data = self._handle_request('get', url)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 529, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found

**Comment by dik23** [comment]
Have just re-logged into Trakt:

> You are now logged into Trakt. Your Trakt credentials have been added in .env and .pytrakt.json files.

Same result

**Comment by glensc** [comment]
1. edited you post again to use block quote (click edit yourself to see syntax)
2. you can upload files to github, no need for third party sites. just drag and drop. may need to use .txt extension
3. watchlist sync is still enabled in your last trace. you sure you edited proper file, i.e `/home/dik/.config/PlexTraktSync/config.json`? perhaps edit the file to make syntax error to see that app really reads the correct file.
4. you did not answer, do you ideas why API call to fetch your watchlist_movies on trakt.tv gives 404? do you have any of them?

**Comment by dik23** [comment]
I've now edited the correct config.json and disabled watchlist sync.

I have no idea why the API call to fetch watchlist_movies on trakt.tv gives 404

```
> plextraktsync sync --dry-run
INFO: PlexTraktSync [0.18.18]
Sync Movie sections: [<PlexLibrarySection:movie:Films>]
Sync Show sections: [<PlexLibrarySection:show:Documentaries>, <PlexLibrarySection:show:Naked and Afraid>, <PlexLibrarySection:show:TV Series>]
Enabled dry-run mode: not making actual changes
Processing Films   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/546  [ 0:00:01 < -:--:-- , ? it/s ]
Traceback (most recent call last):
  File "/home/dik/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/sync.py", line 66, in sync
    self.sync_ratings(movie, dry_run=dry_run)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/sync.py", line 105, in sync_ratings
    if m.plex_rating is m.trakt_rating:
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/media.py", line 121, in trakt_rating
    rating = self.trakt_api.ratings[self.media_type].get(self.trakt_id, None)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 78, in __missing__
    ratings = self.ratings(media_type)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/flatten.py", line 15, in inner
    return dict(method(*args, **kwargs))
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 86, in ratings
    for r in self.trakt.me.get_ratings(media_type):
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 552, in inner
    json_data = self._handle_request('get', url)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 529, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found
```

**Comment by glensc** [comment]
Now it fails with get ratings:

```
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 86, in ratings
    for r in self.trakt.me.get_ratings(media_type):
```

workaround, is to disable ratings from config.

**Comment by dik23** [comment]
```
> plextraktsync sync --dry-run
INFO: PlexTraktSync [0.18.18]
Sync Movie sections: [<PlexLibrarySection:movie:Films>]
Sync Show sections: [<PlexLibrarySection:show:Naked and Afraid>, <PlexLibrarySection:show:TV Series>]
Enabled dry-run mode: not making actual changes
Processing Films   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/546  [ 0:00:00 < -:--:-- , ? it/s ]
Traceback (most recent call last):
  File "/home/dik/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/sync.py", line 67, in sync
    self.sync_watched(movie, dry_run=dry_run)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/sync.py", line 126, in sync_watched
    if m.watched_on_plex is m.watched_on_trakt:
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/media.py", line 101, in watched_on_trakt
    return self.trakt_id in self.trakt_api.watched_movies
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/decorators/rate_limit.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/plextraktsync/trakt_api.py", line 131, in watched_movies
    map(lambda m: m.trakt, self.me.watched_movies)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 552, in inner
    json_data = self._handle_request('get', url)
  File "/home/dik/.local/pipx/venvs/PlexTraktSync/lib/python3.8/site-packages/trakt/core.py", line 529, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found
```

**Comment by dik23** [comment]
I have only installed PlexTraktSync today.  This is my first attempt

I had one watchlist which was empty.  I have just deleted it, it wasn't used for anything.  Same result

I don't use ratings

I am not a premium user.  I use the Kodi trakt.tv addon which works fine - trakt.tv tells me what I watched last night so I doubt I'm banned

I have had the trakttv.bundle plugin installed on Plex which I have now moved to trakttv.bundleBAK to see if it was interfering.  No change in result

I didn't read the original output properly and copied the config.default.json to config.json in ~/.local/pipx/venvs/PlexTraktSync/

**Comment by glensc** [comment]
I don't know your tokens don't work. you can try creating them again, otherwise contact trakt.tv support.

**Comment by dik23** [comment]
Any tips on what to ask trakt.tv support?

**Comment by glensc** [comment]
you should probably try to make api request with `curl`:
- https://trakt.docs.apiary.io/#reference/users/watched/get-watched

**Comment by dik23** [comment]
I don't really understand how to do this with curl

**Comment by twolaw** [comment]
Can you enable debug in config file then run the script then show us the logs ?
How many items are in your trakt watchlist ? what kind of medias are listed in it ?

**Comment by dik23** [comment]
I have found the problem.  My trakt username had a pipe | symbol in it.  I have removed the | and now it works.

Thanks for the time and help, very much appreciated
