### ISSUE TITLE
inspect <id> returns warnings or critical - no authorization to trakt

### ISSUE THREAD

**Issue by stevietv** [Taxel/PlexTraktSync#799]
### The problem

When inspecting an episode, for every GUID linked to that episode a warning is generated that trakt is not authenticated. The followning debug log is generated:

```
2022-02-10 08:28:25,114 DEBUG[plexapi]:GET https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/
2022-02-10 08:28:25,116 DEBUG[urllib3.connectionpool]:Starting new HTTPS connection (1): 192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400
2022-02-10 08:28:28,306 DEBUG[urllib3.connectionpool]:https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400 "GET / HTTP/1.1" 200 3046
2022-02-10 08:28:28,306 DEBUG[requests_cache.session]:Pre-cache checks for response from https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:28:28,307 DEBUG[requests_cache.session]:Skipping cache write for URL: https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/
2022-02-10 08:28:28,311 DEBUG[plexapi]:GET https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library
2022-02-10 08:28:28,313 DEBUG[urllib3.connectionpool]:https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400 "GET /library HTTP/1.1" 200 289
2022-02-10 08:28:28,313 DEBUG[requests_cache.session]:Pre-cache checks for response from https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:28:28,313 DEBUG[requests_cache.session]:Skipping cache write for URL: https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library
2022-02-10 08:28:28,313 DEBUG[plexapi]:GET https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library/metadata/853
2022-02-10 08:28:28,319 DEBUG[urllib3.connectionpool]:https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400 "GET /library/metadata/853 HTTP/1.1" 200 1589
2022-02-10 08:28:28,319 DEBUG[requests_cache.session]:Pre-cache checks for response from https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library/metadata/853: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:28:28,319 DEBUG[requests_cache.session]:Skipping cache write for URL: https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library/metadata/853
2022-02-10 08:28:28,323 DEBUG[trakt.core]:get: https://api.trakt.tv/search/tmdb/2043632?type=episode
2022-02-10 08:28:28,323 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': None, 'Authorization': 'Bearer None'}
2022-02-10 08:28:28,323 DEBUG[trakt.core]:method, url :: get, https://api.trakt.tv/search/tmdb/2043632?type=episode
2022-02-10 08:28:28,324 DEBUG[urllib3.connectionpool]:Starting new HTTPS connection (1): api.trakt.tv:443
2022-02-10 08:28:28,527 DEBUG[urllib3.connectionpool]:https://api.trakt.tv:443 "GET /search/tmdb/2043632?type=episode HTTP/1.1" 403 None
2022-02-10 08:28:28,528 DEBUG[requests_cache.session]:Pre-cache checks for response from https://api.trakt.tv/search/tmdb/2043632?type=episode: {'disabled cache': False, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:28:28,528 DEBUG[requests_cache.session]:Skipping cache write for URL: https://api.trakt.tv/search/tmdb/2043632?type=episode
2022-02-10 08:28:28,529 DEBUG[trakt.core]:RESPONSE [get] (https://api.trakt.tv/search/tmdb/2043632?type=episode): <Response [403]>
2022-02-10 08:28:28,529 WARNING[PlexTraktSync]:<Episode:853:Archer-(2009)-s11e01>: Skipping guid tmdb://2043632 Trakt errors: Forbidden - invalid API key or unapproved app
2022-02-10 08:28:28,537 DEBUG[trakt.core]:get: https://api.trakt.tv/search/tvdb/7859203?type=episode
2022-02-10 08:28:28,537 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': None, 'Authorization': 'Bearer None'}
2022-02-10 08:28:28,537 DEBUG[trakt.core]:method, url :: get, https://api.trakt.tv/search/tvdb/7859203?type=episode
2022-02-10 08:28:28,683 DEBUG[urllib3.connectionpool]:https://api.trakt.tv:443 "GET /search/tvdb/7859203?type=episode HTTP/1.1" 403 None
2022-02-10 08:28:28,684 DEBUG[requests_cache.session]:Pre-cache checks for response from https://api.trakt.tv/search/tvdb/7859203?type=episode: {'disabled cache': False, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:28:28,684 DEBUG[requests_cache.session]:Skipping cache write for URL: https://api.trakt.tv/search/tvdb/7859203?type=episode
2022-02-10 08:28:28,684 DEBUG[trakt.core]:RESPONSE [get] (https://api.trakt.tv/search/tvdb/7859203?type=episode): <Response [403]>
2022-02-10 08:28:28,684 WARNING[PlexTraktSync]:<Episode:853:Archer-(2009)-s11e01>: Skipping guid tvdb://7859203 Trakt errors: Forbidden - invalid API key or unapproved app
2022-02-10 08:28:28,684 DEBUG[trakt.core]:get: https://api.trakt.tv/search/imdb/tt10692628?type=episode
2022-02-10 08:28:28,684 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': None, 'Authorization': 'Bearer None'}
2022-02-10 08:28:28,684 DEBUG[trakt.core]:method, url :: get, https://api.trakt.tv/search/imdb/tt10692628?type=episode
2022-02-10 08:28:29,101 DEBUG[urllib3.connectionpool]:https://api.trakt.tv:443 "GET /search/imdb/tt10692628?type=episode HTTP/1.1" 403 None
2022-02-10 08:28:29,102 DEBUG[requests_cache.session]:Pre-cache checks for response from https://api.trakt.tv/search/imdb/tt10692628?type=episode: {'disabled cache': False, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:28:29,103 DEBUG[requests_cache.session]:Skipping cache write for URL: https://api.trakt.tv/search/imdb/tt10692628?type=episode
2022-02-10 08:28:29,103 DEBUG[trakt.core]:RESPONSE [get] (https://api.trakt.tv/search/imdb/tt10692628?type=episode): <Response [403]>
2022-02-10 08:28:29,103 WARNING[PlexTraktSync]:<Episode:853:Archer-(2009)-s11e01>: Skipping guid imdb://tt10692628 Trakt errors: Forbidden - invalid API key or unapproved app
```

When inspecting a movie, a critical error is generated. debug log is here, error trace is below

```
2022-02-10 08:39:52,602 DEBUG[plexapi]:GET https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/
2022-02-10 08:39:52,603 DEBUG[urllib3.connectionpool]:Starting new HTTPS connection (1): 192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400
2022-02-10 08:39:52,660 DEBUG[urllib3.connectionpool]:https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400 "GET / HTTP/1.1" 200 3046
2022-02-10 08:39:52,660 DEBUG[requests_cache.session]:Pre-cache checks for response from https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:39:52,660 DEBUG[requests_cache.session]:Skipping cache write for URL: https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/
2022-02-10 08:39:52,666 DEBUG[plexapi]:GET https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library
2022-02-10 08:39:52,667 DEBUG[urllib3.connectionpool]:https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400 "GET /library HTTP/1.1" 200 289
2022-02-10 08:39:52,668 DEBUG[requests_cache.session]:Pre-cache checks for response from https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:39:52,668 DEBUG[requests_cache.session]:Skipping cache write for URL: https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library
2022-02-10 08:39:52,668 DEBUG[plexapi]:GET https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library/metadata/11994
2022-02-10 08:39:52,677 DEBUG[urllib3.connectionpool]:https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400 "GET /library/metadata/11994 HTTP/1.1" 200 3678
2022-02-10 08:39:52,677 DEBUG[requests_cache.session]:Pre-cache checks for response from https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library/metadata/11994: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:39:52,678 DEBUG[requests_cache.session]:Skipping cache write for URL: https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library/metadata/11994
2022-02-10 08:39:52,688 DEBUG[trakt.core]:get: https://api.trakt.tv/search/tmdb/4234?type=movie
2022-02-10 08:39:52,688 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': None, 'Authorization': 'Bearer None'}
2022-02-10 08:39:52,688 DEBUG[trakt.core]:method, url :: get, https://api.trakt.tv/search/tmdb/4234?type=movie
2022-02-10 08:39:52,691 DEBUG[trakt.core]:RESPONSE [get] (https://api.trakt.tv/search/tmdb/4234?type=movie): request: GET https://api.trakt.tv/search/tmdb/4234?type=movie, response: 200 (147 bytes), created: 2022-02-09 19:47:10 CET, expires: N/A (fresh)
2022-02-10 08:39:52,691 DEBUG[plexapi]:Reloading Movie 'Scream 3' for attr 'userRating'
2022-02-10 08:39:52,691 DEBUG[plexapi]:GET https://192-168-90-248.e7e5c4ea7e914bb6a322f1e3454287d7.plex.direct:32400/library/metadata/11994?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1
2022-02-10 08:39:52,752 DEBUG[urllib3.connectionpool]:https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400 "GET /library/metadata/11994?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 HTTP/1.1" 200 6765
2022-02-10 08:39:52,752 DEBUG[requests_cache.session]:Pre-cache checks for response from https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library/metadata/11994?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:39:52,752 DEBUG[requests_cache.session]:Skipping cache write for URL: https://192-168-90-248.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400/library/metadata/11994?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1
2022-02-10 08:39:52,764 DEBUG[trakt.core]:get: https://api.trakt.tv/users/me
2022-02-10 08:39:52,764 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': None, 'Authorization': 'Bearer None'}
2022-02-10 08:39:52,764 DEBUG[trakt.core]:method, url :: get, https://api.trakt.tv/users/me
2022-02-10 08:39:52,765 DEBUG[urllib3.connectionpool]:Starting new HTTPS connection (1): api.trakt.tv:443
2022-02-10 08:39:52,971 DEBUG[urllib3.connectionpool]:https://api.trakt.tv:443 "GET /users/me HTTP/1.1" 403 None
2022-02-10 08:39:52,972 DEBUG[requests_cache.session]:Pre-cache checks for response from https://api.trakt.tv/users/me: {'disabled cache': True, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-02-10 08:39:52,973 DEBUG[requests_cache.session]:Skipping cache write for URL: https://api.trakt.tv/users/me
2022-02-10 08:39:52,973 DEBUG[trakt.core]:RESPONSE [get] (https://api.trakt.tv/users/me): <Response [403]>
2022-02-10 08:39:52,973 CRITICAL[PlexTraktSync]:Trakt authentication error: Forbidden - invalid API key or unapproved app

```

### Error trace

```text
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/__main__.py", line 16, in <module>
    cli()
  File "/home/stevietv/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/stevietv/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/stevietv/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stevietv/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stevietv/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/commands/inspect.py", line 112, in inspect
    inspect_media(id)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/commands/inspect.py", line 76, in inspect_media
    print(f"Trakt Rating: {m.trakt_rating}")
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/media.py", line 121, in trakt_rating
    rating = self.trakt_api.ratings[self.media_type].get(self.trakt_id, None)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/trakt_api.py", line 78, in __missing__
    ratings = self.ratings(media_type)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/decorators/flatten.py", line 15, in inner
    return dict(method(*args, **kwargs))
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/trakt_api.py", line 86, in ratings
    for r in self.trakt.get_ratings(media_type):
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/decorators/rate_limit.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/decorators/time_limit.py", line 18, in wrapper
    return fn(*args, **kwargs)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/trakt_api.py", line 180, in get_ratings
    return self.me.get_ratings(media_type)
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/decorators/rate_limit.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/trakt_api.py", line 118, in me
    raise e
  File "/home/stevietv/projects/PlexTraktSync/plextraktsync/trakt_api.py", line 115, in me
    return trakt.users.User('me')
  File "/home/stevietv/.local/lib/python3.8/site-packages/trakt/users.py", line 222, in __init__
    self._get()
  File "/home/stevietv/.local/lib/python3.8/site-packages/trakt/core.py", line 552, in inner
    json_data = self._handle_request('get', url)
  File "/home/stevietv/.local/lib/python3.8/site-packages/trakt/core.py", line 529, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.ForbiddenException: Forbidden - invalid API key or unapproved app
```

### Expected behavior

the lines should show the watched of the episode on trakt I believe

### Steps to reproduce the behavior

run `plextraktsync -m inspect <id>`

### Inspect of problematic items

```text
Inspecting 853: <tmdb:2043632:<Episode:853:Archer-(2009)-s11e01>>
URL: https://app.plex.tv/desktop/#!/server/a11cbdb28b4627ac3578117d58bc6705994aa099/details?key=/library/metadata/853
Media.Type: episode
Media.Guid: 'plex://episode/5f1e7c375b5fa3003dae9571'
Media.Guids: [<Guid:imdb://tt10692628>, <Guid:tmdb://2043632>, <Guid:tvdb://7859203>]
Audio: 'None', 'Unknown (AAC Stereo)'
Video: 'h264'
Parts:
  Part 1: /data/tv/Archer (2009)/Season 11/Archer (2009) - S11E01 - The Orpheus Gambit [SDTV x264].mkv
Guids:
  Guid: tmdb://2043632, Id: 2043632, Provider: tmdb
  Guid: tvdb://7859203, Id: 7859203, Provider: tvdb
  Guid: imdb://tt10692628, Id: tt10692628, Provider: imdb
Metadata: {'collected_at': '2020-09-17:T02:00:00.000Z', 'media_type': 'digital', 'resolution': 'sd_480p', 'audio': 'aac', 'audio_channels': '2.0'}
WARNING: <Episode:853:Archer-(2009)-s11e01>: Skipping guid tmdb://2043632 Trakt errors: Forbidden - invalid API key or unapproved app
WARNING: <Episode:853:Archer-(2009)-s11e01>: Skipping guid tvdb://7859203 Trakt errors: Forbidden - invalid API key or unapproved app
WARNING: <Episode:853:Archer-(2009)-s11e01>: Skipping guid imdb://tt10692628 Trakt errors: Forbidden - invalid API key or unapproved app



Inspecting 11994: <tmdb:4234:<Movie:11994:Scream-3>>
URL: https://app.plex.tv/desktop/#!/server/a11cbdb28b4627ac3578117d58bc6705994aa099/details?key=/library/metadata/11994
Media.Type: movie
Media.Guid: 'plex://movie/5d77682d3c3c2a001fbcc70b'
Media.Guids: [<Guid:imdb://tt0134084>, <Guid:tmdb://4234>, <Guid:tvdb://2187>]
Audio: 'None', 'English (AAC 5.1)'
Video: 'h264'
Parts:
  Part 1: /data/movies/Scream 3 (2000)/Scream 3 (2000) [imdb-tt0134084][Bluray-1080p][8bit][x264][AAC 5.1]-RARBG.mp4
Guids:
  Guid: tmdb://4234, Id: 4234, Provider: tmdb
  Guid: tvdb://2187, Id: 2187, Provider: tvdb
  Guid: imdb://tt0134084, Id: tt0134084, Provider: imdb
Metadata: {'collected_at': '2022-02-05:T23:41:41.000Z', 'media_type': 'digital', 'resolution': 'hd_1080p', 'audio': 'aac', 'audio_channels': '5.1'}
Trakt: https://trakt.tv/movies/2483
Plex Rating: None
CRITICAL: Trakt authentication error: Forbidden - invalid API key or unapproved app
```

### Install method

git clone

### Version

0.18.20

### Python Version

3.8.10

### Operating System and Version

ubuntu 20.04

**Comment by stevietv** [comment]
This was fixed by updating some pip packages. By installing with a git clone my pip packages were not totally up to date with the requirements.
ones I updated: trakt, inquirerpy, requests-cache, rich

**Comment by glensc** [comment]
you should use `pipx` or docker image, then the versions match ones provided by this repository

**Comment by glensc** [comment]
`'trakt-api-key': None, 'Authorization': 'Bearer None'` indicates that trakt token was missing
