### ISSUE TITLE
Log flooded with "WARNING: Invalid JSON body" and "JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by Hubro** [Taxel/PlexTraktSync#809]
### The problem

I'm using the official Docker image, tag "main", hash `20332faa96a8`.

My log (docker log plextractsync) is completely flooded with thousands of these warnings:

<pre>
WARNING: Invalid JSON body:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
    body = json.loads(decode(original_body))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING: Invalid JSON body:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
    body = json.loads(decode(original_body))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING: Invalid JSON body:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
    body = json.loads(decode(original_body))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING: Invalid JSON body:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
    body = json.loads(decode(original_body))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
...
</pre>

But in spite of this, everything appears to be working. At least my shows are updated and marked as watched corrently on Trakt.

### Error trace

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
    body = json.loads(decode(original_body))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Expected behavior

I would expect no warnings or errors in the log when things are working.

### Steps to reproduce the behavior

I am running the image like this. I followed the instructions on first launch.

```
docker run --rm -ti --name plextraktsync -v plextractsync-config:/app/config ghcr.io/taxel/plextraktsync:main sync
```

### Install method

docker-compose

### Version

0.18.2-16-g961fe7b_main

### Python Version

Python 3.10.0

### Operating System and Version

Arch Linux (5.16.2-arch1-1)

**Comment by Hubro** [comment]
Just upgraded to `0.18.20-6-g781fe5c_main` (Docker image hash `a650bf6cdeae`) and it solved the problem.
