### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by dojoge** [Taxel/PlexTraktSync#81]
I am getting a JSONDecodeError whenever I try to sync anything. 
I found the closed issue from a few weeks ago and updated everything but I am still getting the error. 

From the debug log, it looks like there is a problem with retrieving the watched shows from Trakt (Error 524 Timeout?).

```
Traceback (most recent call last):
  File "/root/PlexTraktSync/PlexTraktSync/main.py", line 355, in <module>
    main()
  File "/root/PlexTraktSync/PlexTraktSync/main.py", line 294, in main
    map(lambda m: m.trakt, trakt_user.watchlist_movies)))
  File "/usr/local/lib/python3.7/dist-packages/trakt/core.py", line 539, in inner
    json_data = self._handle_request('get', url)
  File "/usr/local/lib/python3.7/dist-packages/trakt/core.py", line 519, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Debug log:
```
2020-10-26 08:50:56,584 INFO:Starting sync Plex *** and Trakt ***
2020-10-26 08:50:56,585 DEBUG:get: https://api-v2launch.trakt.tv/users/me
2020-10-26 08:50:56,585 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': '***', 'Authorization': 'Bearer ***$
2020-10-26 08:50:56,585 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/me
2020-10-26 08:50:56,590 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-26 08:50:57,054 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/me HTTP/1.1" 200 None
2020-10-26 08:50:57,059 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/me): <Response [200]>
2020-10-26 08:50:57,060 DEBUG:get: https://api-v2launch.trakt.tv/users/likes/lists
2020-10-26 08:50:57,060 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': '***', 'Authorization': 'Bearer ***$
2020-10-26 08:50:57,060 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/likes/lists
2020-10-26 08:50:57,063 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-26 08:50:57,251 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/likes/lists HTTP/1.1" 200 2042
2020-10-26 08:50:57,255 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/likes/lists): <Response [200]>
2020-10-26 08:50:57,257 DEBUG:get: https://api-v2launch.trakt.tv/users/dojoge/watched/movies
2020-10-26 08:50:57,257 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': '***', 'Authorization': 'Bearer ***$
2020-10-26 08:50:57,257 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/dojoge/watched/movies
2020-10-26 08:50:57,260 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-26 08:50:58,138 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/dojoge/watched/movies HTTP/1.1" 200 None
2020-10-26 08:50:58,146 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/dojoge/watched/movies): <Response [200]>
2020-10-26 08:50:58,164 DEBUG:Watched movies from trakt: {7, 8, 9, 8202, 14, 18, 75798, 223262, 31, 208930, 102438, 163882, 48, 92214, 92215, 58, 4158, 77887, 92226, 92230, 74, 129102, 88, 89, 90, 120, 102523, 147585, 149640, 51342, 424$
2020-10-26 08:50:58,164 DEBUG:get: https://api-v2launch.trakt.tv/users/dojoge/collection/movies?extended=metadata
2020-10-26 08:50:58,164 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': '***', 'Authorization': 'Bearer ***$
2020-10-26 08:50:58,164 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/dojoge/collection/movies?extended=metadata
2020-10-26 08:50:58,167 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-26 08:50:58,768 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/dojoge/collection/movies?extended=metadata HTTP/1.1" 200 None
2020-10-26 08:50:58,777 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/dojoge/collection/movies?extended=metadata): <Response [200]>
2020-10-26 08:50:58,798 DEBUG:get: https://api-v2launch.trakt.tv/sync/watched/shows
2020-10-26 08:50:58,799 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': '***', 'Authorization': 'Bearer ****$
2020-10-26 08:50:58,799 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/sync/watched/shows
2020-10-26 08:50:58,802 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-26 08:51:14,423 DEBUG:https://api-v2launch.trakt.tv:443 "GET /sync/watched/shows HTTP/1.1" 524 None
2020-10-26 08:51:14,427 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/sync/watched/shows): <Response [524]>
```

**Comment by dojoge** [comment]
Sorry, I found my mistake. After reinstalling I didn't change the config.json completly. I removed the default exluded_libraries and now the issue is gone. 
Sorry again for raising the issue.
