### ISSUE TITLE
Some non-latin characters not allowed in excluded-libraries

### ISSUE THREAD

**Issue by downey-lv** [Taxel/PlexTraktSync#878]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

Library names containing some non-Latin characters (Latvian in this case) are shown fine when running info command, but when adding them to the excluded-libraries setting charmap error is thrown. 

`Enabled 5 libraries in Plex Server: ['Kristīnei', 'Latviešu filmas', 'Movies', 'TV Shows', 'Audiobooks']`

### Error trace / logs

```text
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\.local\bin\plextraktsync.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\commands\info.py", line 24, in info
    print(f"Plex username: {config['PLEX_USERNAME']}")
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\config.py", line 55, in __getitem__
    self.initialize()
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\config.py", line 73, in initialize
    config = self.load_json(self.config_file)
  File "C:\Users\user\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\config.py", line 117, in load_json
    config = json.load(fp)
  File "C:\Users\user\Anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\user\Anaconda3\lib\encodings\cp1257.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0xa1 in position 881: character maps to <undefined>
```

### Expected behavior

Expected to parse the non-Latin characters the same as Latin

### Steps to reproduce the behavior

1. Set excluded-libraries in config.json to contain latvian characters e.g. `"excluded-libraries": ["Kristīnei","Latviešu filmas"]`
2. Run any PlexTraktSync command, e.g. `plextraktsync info`

### Install method

pipx (Recommended)

### Version

0.18.25

### Python Version

3.9.7

### Operating System and Version

Windows 11

**Comment by twolaw** [comment]
The config.json looks utf-8 encoded (because 0xa1 matches the š in utf8 and is not in cp1257 table) but is decoded with cp1257 table because of `json.load()` used instead of `json.loads()`.
json.load() invoques read() method :
https://github.com/python/cpython/blob/12d0a7642fc552fa17b1608fe135306cddec5f4e/Lib/json/__init__.py#L274

which uses the `locale.getpreferredencoding()` of the OS.
Windows-1257 must be the host encoding of @downey-lv 's OS.
That's why this error occurs here.

**Comment by glensc** [comment]
nah. `loads` needs `string` (that the `s` stands for),

so, the fix is to add `encoding="utf-8"` to open call:
- https://github.com/Taxel/PlexTraktSync/pull/881

**Comment by glensc** [comment]
Probably some other local mitigation is to set environment variable: `LC_ALL="en_US.UTF-8"` or `C.UTF-8`.

- https://docs.python.org/3/library/locale.html#locale.getpreferredencoding

or `PYTHONUTF8`:
- https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8

**Comment by glensc** [comment]
Or `python` be called with `-X utf8`:
- https://docs.python.org/3/using/cmdline.html#cmdoption-X

**Comment by glensc** [comment]
Fixed in 0.18.27

**Comment by twolaw** [comment]
> nah. `loads` needs `string` (that the `s` stands for),

[loads](https://docs.python.org/3/library/json.html) also read bytes :
> Deserialize s (a [str](https://docs.python.org/3/library/stdtypes.html#str), [bytes](https://docs.python.org/3/library/stdtypes.html#bytes) or [bytearray](https://docs.python.org/3/library/stdtypes.html#bytearray) instance containing a JSON document) to a Python object using this [conversion table](https://docs.python.org/3/library/json.html#json-to-py-table).

But your fix is ok too.

**Comment by glensc** [comment]
but `open()` does not return any of them. it returns `StringIO`

```
TypeError: the JSON object must be str, bytes or bytearray, not TextIOWrapper
```

**Comment by twolaw** [comment]
ok, isn't this fix needed for writing `open()` too ?

**Comment by glensc** [comment]
comment code in code pr.

but answer: indeed, I forgot, and it would be symmetrical to do so, but in reality not needed, as write is done only when copying default config. and currently default config is in ASCII.

also, there's a plan to change config to yaml:
- https://github.com/Taxel/PlexTraktSync/pull/852

...so that code would go away
