### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by Al4ndil** [Taxel/PlexTraktSync#882]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I had launch plextraktsync a second time but i have errors

### Error trace / logs

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/plextraktsync/cli.py", line 46, in cli
    sync()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 60, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 66, in sync
    for movie in walker.find_movies():
  File "/app/plextraktsync/walker.py", line 246, in find_movies
    for plex in self.get_plex_movies():
  File "/app/plextraktsync/walker.py", line 243, in get_plex_movies
    yield from movies
  File "/app/plextraktsync/walker.py", line 300, in media_from_sections
    yield from it
  File "/app/plextraktsync/walker.py", line 320, in progressbar
    yield from it
  File "/usr/local/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/app/plextraktsync/plex_api.py", line 459, in items
    for item in self.all(max_items):
  File "/app/plextraktsync/plex_api.py", line 444, in all
    items = self.fetch_items(key, size, start)
  File "/app/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/app/plextraktsync/plex_api.py", line 456, in fetch_items
    return self.section.fetchItems(key, container_start=start, container_size=size)
  File "/usr/local/lib/python3.10/site-packages/plexapi/library.py", line 426, in fetchItems
    data = self._server.query(ekey, params=url_kw)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 682, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; http://90.93.221.170:32400/library/sections/1/all?includeGuids=1&type=1&X-Plex-Container-Start=600&X-Plex-Container-Size=100 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
```

### Expected behavior

Go to the end of process

### Steps to reproduce the behavior

Launch process
On 34% the process bug

### Install method

docker-compose

### Version

0.18.28

### Python Version

3.10.0

### Operating System and Version

Docker on debian 11

**Comment by glensc** [comment]
The error comes from hyour plex server, check it's logs:
> `plexapi.exceptions.BadRequest: (500) internal_server_error; http://90.93.221.170:32400/library/sections/1/all?includeGuids=1&type=1&X-Plex-Container-Start=600&X-Plex-Container-Size=100 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>`

**Comment by glensc** [comment]
Added retry to the method:
- https://github.com/Taxel/PlexTraktSync/pull/883

if retry also fails, then it's nothing this program can do
