### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by bbakermmc** [Taxel/PlexTraktSync#9]
I think this should continue to next request :)
```


Processing section TV Shows
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files (x86)\Python38-32\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\Python38-32\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files (x86)\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='148.251.159.246', port=42411): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/bradl/Desktop/PlexTraktSync-master/main.py", line 315, in <module>
    main()
  File "C:/Users/bradl/Desktop/PlexTraktSync-master/main.py", line 300, in main
    process_show_section(section)
  File "C:/Users/bradl/Desktop/PlexTraktSync-master/main.py", line 186, in process_show_section
    for episode in show.episodes():
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\plexapi\video.py", line 352, in episodes
    return self.fetchItems(key, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\plexapi\base.py", line 147, in fetchItems
    data = self._server.query(ekey)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\plexapi\server.py", line 376, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='148.251.159.246', port=42411): Read timed out. (read timeout=30)

Process finished with exit code 1
```

**Comment by Taxel** [comment]
My means of fixing this are very limited. Might it be helpful to you if you could edit the [PlexAPI configuration file](https://github.com/pkkid/python-plexapi/blob/master/docs/configuration.rst) directly? With this, you could try to increase the timeout from 30 seconds (which already seems high) to 60 or 120 seconds. It is, of course, possible for me to change the script so instead of stopping it  just skips the library item where this occurs, but to me that does not make a lot of sense: When the connection to the Plex server does not work, the program should terminate instead of trying all the other library items and hoping that the Plex server answers some of them.

**Comment by CMaclellan** [comment]
It would be nice if you could configure the application to retry X times with a Y timeout rather than fail so dramatically.

**Comment by gitthangbaby** [comment]
i am getting interruption by a random error often:

`  File "main.py", line 315, in <module>
    main()
  File "main.py", line 296, in main
    section, trakt_watched_movies, ratings, listutil, trakt_movie_collection)
  File "main.py", line 63, in process_movie_section
    search = trakt.sync.search_by_id(x, id_type=provider)
  File "/usr/local/lib/python3.6/site-packages/trakt/core.py", line 472, in inner
    json_data = self._handle_request('get', url)
  File "/usr/local/lib/python3.6/site-packages/trakt/core.py", line 452, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

`  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /search?id=xxxxxx&id_type=tvdb (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x807e3af28>: Failed to establish a new connection: [Errno 8] hostname nor servname provided, or not known',))
`

it hurts a bit since i run daily, each run is 15min (or 6min without liked lists) i also think about retries.
