### ISSUE TITLE
OAuthException: Unauthorized - OAuth must be provided - ERROR

### ISSUE THREAD

**Issue by MarcelCosta79** [Taxel/PlexTraktSync#92]
Hi guys,

I tried to install but I'm getting this error:
What Should I do ? 
Thank you

```
Starting sync Plex ******  and Trakt *******
Traceback (most recent call last):
  File "main.py", line 359, in <module>
    main()
  File "main.py", line 303, in main
    listutil.addList(lst['username'], lst['listname'])
  File "/home/mestre/PlexTraktSync/trakt_list_util.py", line 56, in addList
    self.lists.append(TraktList(username, listname))
  File "/home/mestre/PlexTraktSync/trakt_list_util.py", line 17, in __init__
    self.traktids = dict(zip(map(lambda e: e.trakt, [elem for elem in UserList._get(listname, username).get_items() if isinstance(elem, (Movie, TVEpisode))]), count(1)))
  File "/usr/local/lib/python3.8/dist-packages/trakt/core.py", line 539, in inner
    json_data = self._handle_request('get', url)
  File "/usr/local/lib/python3.8/dist-packages/trakt/core.py", line 516, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
```

**Comment by twolaw** [comment]
Hi,
Could you set log_debug_messages to true in config.json, run script and then show content of last_update.log please.

**Comment by MarcelCosta79** [comment]
thank you !!
I've nailed it down.
Some time ago I "liked" a playlist but now the owner's profile is private and I can't see it anymore until I follow him.
I've just removed the like and now it's running but I got another error.
I'm using the plexagentfix build.


`Starting sync Plex mco_007 and Trakt MarcelCosta
Processing section Movies
Traceback (most recent call last):
  File "main.py", line 359, in <module>
    main()
  File "main.py", line 337, in main
    process_movie_section(
  File "main.py", line 40, in process_movie_section
    if len(movie.guids) > 0:
  File "/usr/local/lib/python3.8/dist-packages/plexapi/base.py", line 279, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Movie' object has no attribute 'guids'
`


Debug log:

`2020-12-16 05:22:30,474 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/marcelcosta/watched/movies
2020-12-16 05:22:30,477 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-12-16 05:22:31,369 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/marcelcosta/watched/movies HTTP/1.1" 200 None
2020-12-16 05:22:31,505 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/marcelcosta/watched/movies): <Response [200]>
2020-12-16 05:22:31,524 DEBUG:Watched movies from trakt: {284678, 7, 9, 10, 18, 19, 23, 94232, 31, 20512, 33, 34, 43, 47, 48, 54, 58, 59, 67, 70, 92230, 74, 76, 10322, 86, 87, 88, 280668, 8301, 120, 4219, 126, 4225, 130, 149640, 239755, 141, 51342, 145, 4242, 149, 159, 160, 139432, 106666, 106667, 258220, 177, 161972, 24763, 250049, 196, 12496, 212, 6357, 223444, 188631, 4314, 228, 230, 6375, 233, 234, 236, 239, 4335, 383221, 4346, 71938, 276, 16662, 254235, 8476, 8477, 233766, 295, 297, 301, 12589, 304, 254263, 313, 12601, 4428, 343, 346, 2399, 24931, 358, 59753, 14701, 6510, 547185, 217461, 450934, 377, 390, 410, 33179, 10655, 192932, 264623, 432, 438, 439, 442, 443, 285120, 211394, 213443, 2503, 457, 55753, 469, 475, 231900, 479, 480, 481, 482, 483, 485, 82405, 336359, 489, 55786, 2541, 149999, 496, 371189, 503, 505, 328196, 4613, 520, 4633, 538, 545, 546, 547, 4642, 549, 4646, 4647, 461346, 553, 554, 4653, 129583, 242226, 119348, 193079, 4667, 178749, 4670, 4676, 589, 590, 591, 4685, 595, 55894, 205404, 610, 614, 72297, 4715, 635, 92802, 650, 651, 4766, 184992, 4771, 2724, 37540, 4783, 98998, 697, 6841, 699, 700, 705, 4811, 375504, 461537, 363240, 76524, 256749, 762, 23293, 766, 23294, 769, 770, 23299, 23300, 23308, 782, 784, 785, 793, 60185, 6948, 316199, 2857, 123707, 226108, 4934, 6989, 846, 127824, 127828, 240475, 191328, 4977, 25482, 5003, 39822, 5007, 913, 299929, 933, 56230, 269236, 952, 5058, 293826, 5061, 5065, 981, 50134, 5080, 50139, 991, 50145, 7146, 463851, 1006, 168946, 363514, 1032, 23560, 181256, 72719, 1048, 7198, 56358, 56360, 5161, 222254, 222255, 5177, 7228, 7229, 181311, 5184, 181312, 181313, 11334, 183371, 1101, 308302, 154718, 293982, 83040, 353379, 1126, 124008, 5226, 273537, 1155, 1157, 179334, 343180, 169105, 1170, 13469, 1185, 5282, 5293, 1199, 179407, 1237, 1244, 464098, 5355, 1261, 1266, 1267, 1268, 1269, 1270, 265465, 167163, 269568, 214279, 34067, 1302, 34073, 5408, 214312, 1323, 34093, 34095, 34097, 87348, 191797, 191798, 44345, 193850, 1343, 56686, 1394, 1406, 224641, 56709, 1430, 5535, 5542, 146856, 193963, 322988, 193968, 243128, 347587, 89542, 89543, 222674, 298468, 24047, 189952, 1542, 77335, 261663, 247334, 5678, 163375, 7729, 355892, 3642, 73293, 22105, 36449, 196213, 5762, 216715, 216716, 5778, 147091, 3774, 1736, 34507, 73425, 34515, 34517, 3799, 24279, 5853, 3812, 5864, 22248, 3825, 3843, 53002, 102156, 102162, 112404, 239425, 30533, 1863, 94024, 1865, 14160, 30549, 40808, 73582, 3954, 210803, 128888, 382862, 42897, 6039, 130970, 6049, 53166, 1967, 12216, 24505, 6075, 12219, 303043, 2004, 432086, 301015, 75735, 190430, 65508, 192487, 12269, 399358}
2020-12-16 05:22:31,525 DEBUG:get: https://api-v2launch.trakt.tv/users/marcelcosta/collection/movies?extended=metadata
2020-12-16 05:22:31,525 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'f04dd45955b0f338de099c3bbce11c9147057aeee9ebe0b5b6218839bc8f1b55', 'Authorization': 'Bearer 1dc0573f94c9183f04369a8d7543613555ae740421c731fb700fc9deb9a958af'}
2020-12-16 05:22:31,525 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/marcelcosta/collection/movies?extended=metadata
2020-12-16 05:22:31,528 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-12-16 05:22:32,517 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/marcelcosta/collection/movies?extended=metadata HTTP/1.1" 200 None
2020-12-16 05:22:32,684 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/marcelcosta/collection/movies?extended=metadata): <Response [200]>
2020-12-16 05:22:32,780 DEBUG:get: https://api-v2launch.trakt.tv/sync/watched/shows
2020-12-16 05:22:32,781 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'f04dd45955b0f338de099c3bbce11c9147057aeee9ebe0b5b6218839bc8f1b55', 'Authorization': 'Bearer 1dc0573f94c9183f04369a8d7543613555ae740421c731fb700fc9deb9a958af'}
2020-12-16 05:22:32,781 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/sync/watched/shows
2020-12-16 05:22:32,784 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-12-16 05:22:33,599 DEBUG:https://api-v2launch.trakt.tv:443 "GET /sync/watched/shows HTTP/1.1" 200 None
2020-12-16 05:22:33,727 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/sync/watched/shows): <Response [200]>
2020-12-16 05:22:33,752 DEBUG:get: https://api-v2launch.trakt.tv/users/marcelcosta/watchlist/movies
2020-12-16 05:22:33,752 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'f04dd45955b0f338de099c3bbce11c9147057aeee9ebe0b5b6218839bc8f1b55', 'Authorization': 'Bearer 1dc0573f94c9183f04369a8d7543613555ae740421c731fb700fc9deb9a958af'}
2020-12-16 05:22:33,752 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/marcelcosta/watchlist/movies
2020-12-16 05:22:33,756 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-12-16 05:22:34,484 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/marcelcosta/watchlist/movies HTTP/1.1" 200 None
2020-12-16 05:22:34,501 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/marcelcosta/watchlist/movies): <Response [200]>
2020-12-16 05:22:34,504 INFO:Downloaded List Trakt Watchlist
2020-12-16 05:22:34,504 DEBUG:get: https://api-v2launch.trakt.tv/users/marcelcosta/ratings/movies
2020-12-16 05:22:34,504 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'f04dd45955b0f338de099c3bbce11c9147057aeee9ebe0b5b6218839bc8f1b55', 'Authorization': 'Bearer 1dc0573f94c9183f04369a8d7543613555ae740421c731fb700fc9deb9a958af'}
2020-12-16 05:22:34,504 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/marcelcosta/ratings/movies
2020-12-16 05:22:34,507 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-12-16 05:22:35,198 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/marcelcosta/ratings/movies HTTP/1.1" 200 None
2020-12-16 05:22:35,205 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/marcelcosta/ratings/movies): <Response [200]>
2020-12-16 05:22:35,207 DEBUG:Movie ratings from trakt: {'house-1986': 9, 'cube-1997': 8, 'what-happened-to-monday-2017': 8, 'warcraft-2016': 8, 'the-platform-2019': 7, 'mortal-engines-2018': 6, 'the-hunt-2020': 4, 'american-made-2017': 8, 'superman-red-son-2020': 1, 'brightburn-2019': 6, 'cocoon-1985': 9, 'the-return-of-the-living-dead-1985': 9, 'ferris-bueller-s-day-off-1986': 9, 'the-goonies-1985': 9, 'schindler-s-list-1993': 8, 'saving-private-ryan-1998': 10, 'gone-with-the-wind-1939': 10, 'the-internship-2013': 2, 'marighella-2019': 1, 'the-wave-2008': 8, 'top-gun-1986': 8, 'the-death-of-stalin-2017': 7, 'downfall-2004': 9, 'in-the-tall-grass-2019': 5, 'citizenfour-2014': 1, 'the-great-wall-2016': 7, 'back-to-the-future-1985': 10, 'apocalypse-now-1979': 8, 'jojo-rabbit-2019': 8, 'parasite-2019': 7, 'mad-max-beyond-thunderdome-1985': 10, 'mad-max-1979': 10, 'mad-max-2-1981': 10, 'once-upon-a-deadpool-2018': 8, 'striptease-1996': 10}
2020-12-16 05:22:35,208 INFO:Loaded Trakt lists.
2020-12-16 05:22:35,212 DEBUG:Starting new HTTPS connection (1): 192-168-1-30.84880e8f25c9406d82a40181830e30ff.plex.direct:32400
2020-12-16 05:22:35,304 DEBUG:https://192-168-1-30.84880e8f25c9406d82a40181830e30ff.plex.direct:32400 "GET / HTTP/1.1" 200 3568
2020-12-16 05:22:35,306 INFO:Server version 1.21.1.3795-ee64ab56f updated at: 2020-12-16 04:36:46
2020-12-16 05:22:35,310 DEBUG:https://192-168-1-30.84880e8f25c9406d82a40181830e30ff.plex.direct:32400 "GET /library HTTP/1.1" 200 289
2020-12-16 05:22:35,450 DEBUG:https://192-168-1-30.84880e8f25c9406d82a40181830e30ff.plex.direct:32400 "GET /library/recentlyAdded HTTP/1.1" 200 21129
2020-12-16 05:22:35,753 INFO:Recently added: [<Season:139328:The-Expanse-s5>, <Movie:139317:Alguém-Avisa?>, <Movie:139313:Em-Busca-da-Felicida>, <Movie:139312:Boni-Bonita>, <Movie:139298:Jornada-nas-Estrelas>]
2020-12-16 05:22:35,759 DEBUG:https://192-168-1-30.84880e8f25c9406d82a40181830e30ff.plex.direct:32400 "GET /library/sections HTTP/1.1" 200 1026
2020-12-16 05:22:36,825 DEBUG:https://192-168-1-30.84880e8f25c9406d82a40181830e30ff.plex.direct:32400 "GET /library/sections/1/all HTTP/1.1" 200 1062682
2020-12-16 05:22:53,348 INFO:Now working on movie section Movies containing 2319 elements`

**Comment by twolaw** [comment]
> Some time ago I "liked" a playlist but now the owner's profile is private and I can't see it anymore until I follow him.

I understand. Thank you, I will add a bypass for this special use case.

The 'guids' problem is another issue, you are not using the master branch.
Please discuss it in #87.
