### ISSUE TITLE
Feature request: Progress Reset

### ISSUE THREAD

**Issue by EffeF** [Taxel/PlexTraktSync#966]
### Feature description
This VIP feature allows you to reset a show's progress and track rewatches from your progress page and dashboard up next.
I expect progress to be reset on Plex as well, so that rewatching can be done easily without having to go searching for the episode within a series already watched.

### References
https://trakt.tv/vip/progress-reset
https://support.trakt.tv/support/solutions/articles/70000628748-how-to-reset-watched-progress
https://trakt.docs.apiary.io/#reference/shows/watched-progress/get-show-watched-progress

**Comment by EffeF** [comment]
> Yes.

Then manually marking it with unwatched is not the right solution, at least to my way of use.

> PS: I don't know if we want to add code designed for trakt VIP members only.

I don't know how many VIP users use this script, surely there are some.

Trakt's API provides the user's VIP status, so in this respect just do a check and disable this and possibly other VIP features.

At this point whether to implement it or not just depends on the time required to implement it and whether there are other VIP users interested...

**Comment by twolaw** [comment]
> Then manually marking it with unwatched is not the right solution, at least to my way of use.

We can add a condition reading show's **reset_at** value before matching watched status of episodes.
A reset show must not re-mark as watched episodes seen before the reset.

**Comment by EffeF** [comment]
This could be an interesting solution, more than the smart playlist in my opinion.

Therefore, the process would be:
1. reset the progress on Trakt
2. mark as unwatched on Plex
3. if `reset_at` > `last_watched_at` PlexTraktSync not re-mark as watched episodes

Ideally, step 2 would be automated as well, but even so it is a great solution for managing rewatches

**Comment by EffeF** [comment]
>  You loose Plex view history, but it's still available on trakt.

This is not a problem for me. In my use Plex is just a media server, my history is on Trakt.

> So they know what they did on purpose.

Agreed. Maybe as an option disabled by default in the configuration file? So it would be something that just happens only as a choice on purpose.

**Comment by Hubro** [comment]
> About step 2, I'm not fond of automatically mark all episodes unwatched because users will loose their Plex view history after a trakt reset

This seems like the expected outcome to me. If a user resets a show in Trakt, the intuitive result is that it should become unwatched in Plex.

It also seems to me that if somebody uses Trakt, it's unlikely that they care very much about the long term local state in Plex. If I want to check how many times I've watched episode, I will check Trakt, not Plex.

If you think there are users that would be bothered by this (I don't) then you could hide this behind an option.

Something like:

```
--allow-reset-unwatch    Allow Trakt show resets to mark shows
                         as unwatched in Plex
```

**Comment by twolaw** [comment]
That's a good logic too.
In #969 I added a safety in `mark_watched_trakt()` to prevent a show already reset to mark as watched episodes played in plex **before** the reset (without this safety it would send a new watched status at every sync).
With the logic of marking Plex show as unwatched, this safety is not needed anymore.

I don't know what to do.
Can anybody with Trakt VIP access try the #969 PR ?

**Comment by twolaw** [comment]
@EffeF @Hubro can you try this PR :
- https://github.com/Taxel/PlexTraktSync/pull/969

**Comment by Hubro** [comment]
I run both Plex and PlexTraktSync on a remote server using Docker, so testing this PR is a bit of a pain for me, which is why I haven't found time yet.

@EffeF Are you able to test this?

**Comment by glensc** [comment]
you can install pipx and then plextraktsync to that docker container

```
$ docker-compose run --rm --entrypoint sh plextraktsync
/app # pip install pipx
/app # pipx install plextraktsync
/app # apk add git
/app # /root/.local/bin/plextraktsync self-update --pr 969
/app # /root/.local/bin/plextraktsync@969 info
```

**Comment by NGDM** [comment]
Just tested this following @glensc's docker install.
Got this error message when running sync and having reset progress for one show, with 3 episodes seen since then.

> Traceback (most recent call last):
  File "/root/.local/bin/plextraktsync@969", line 8, in <module>
    sys.exit(cli())
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/commands/sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/sync.py", line 97, in sync
    self.sync_watched(episode, dry_run=dry_run)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/sync.py", line 160, in sync_watched
    m.mark_watched_trakt(dry_run)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/media.py", line 143, in mark_watched_trakt
    if self.show_reset_at and self.plex.seen_date < self.show_reset_at:
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by twolaw** [comment]
@NGDM you can test again, i updated PR #969

**Comment by NGDM** [comment]
New error, seems like a missing attribute used in the logging:

```
File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/media.py", line 144, in mark_watched_trakt
    logger.info(f"Show {self.show.title} has been reset in trakt at {self.show_reset_at}.")
AttributeError: 'Media' object has no attribute 'title'
```

**Comment by twolaw** [comment]
@NGDM
Fixed, can you test again ?

**Comment by NGDM** [comment]
@twolaw Different error this time:

```
Traceback (most recent call last):
  File "/root/.local/bin/plextraktsync@969", line 8, in <module>
    sys.exit(cli())
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/commands/sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/sync.py", line 88, in sync
    self.sync_ratings(movie, dry_run=dry_run)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/sync.py", line 142, in sync_ratings
    m.trakt_rate()
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/media.py", line 172, in trakt_rate
    self.trakt_api.rate(self.trakt, self.plex_rating)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/decorators/rate_limit.py", line 22, in wrapper
    return fn(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/decorators/time_limit.py", line 18, in wrapper
    return fn(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/decorators/retry.py", line 25, in wrapper
    return fn(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/trakt_api.py", line 226, in rate
    m.rate(rating)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/trakt/movies.py", line 321, in rate
    rate(self, rating)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/trakt/core.py", line 587, in inner
    json_data = self._handle_request('post', url, data=args)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/trakt/core.py", line 526, in _handle_request
    data=json.dumps(data))
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
```

**Comment by twolaw** [comment]
It doesn't seem related to progess reset. Please disable ratings for this test.
And open new issue for this new rating error.

**Comment by NGDM** [comment]
I don't get above error on my regular sync container, using the same config file… not sure if this is a newly added issue in this PR? 

I've disabled ratings and am now getting this error:
```
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/sync.py", line 160, in sync_watched
    m.mark_watched_trakt(dry_run)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/media.py", line 144, in mark_watched_trakt
    logger.info(f"Show {self.plex.show.title} has been reset in trakt at {self.show_reset_at}.")
AttributeError: 'PlexLibraryItem' object has no attribute 'show'

```

**Comment by twolaw** [comment]
`self.plex.item.show.title` instead of `self.plex.show.title`

I updated, can you test again ? (sorry i can't test)

**Comment by NGDM** [comment]
No worries mate, you implement, I test.
Next error:
```
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/sync.py", line 160, in sync_watched
    m.mark_watched_trakt(dry_run)
  File "/root/.local/pipx/venvs/plextraktsync@969/lib/python3.10/site-packages/plextraktsync/media.py", line 144, in mark_watched_trakt
    logger.info(f"Show {self.plex.item.show.title} has been reset in trakt at {self.show_reset_at}.")
AttributeError: 'function' object has no attribute 'title'
```

**Comment by twolaw** [comment]
test again

**Comment by NGDM** [comment]
Looks good.

I have Cyberpunk as the reset show and watched E05 last. 
This is the log output:
```
INFO     PlexTraktSync [0.22.0dev0]                                                                                       
INFO     Sync Show sections: [<PlexLibrarySection:show:My TV Shows>]                                                      
INFO     Show Cyberpunk: Edgerunners has been reset in trakt at 2022-09-27 22:14:44.                                      
INFO     Marking Cyberpunk: Edgerunners as unwatched in Plex.                                                             
INFO     Marking as watched in Trakt: <tmdb:3894664:Episode:38126:Cyberpunk:-Edgerunne-s01e06>                            
Processing My TV Shows 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33/33  [ 0:01:06 < 0:00:00 , 1 it/s ]
INFO     My TV Shows processed in 1 min 6.9 seconds                                                                       
Processing Plex watchlist 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5  [ 0:00:02 < 0:00:00 , 2 it/s ]
Processing Trakt watchlist   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/0  [ 0:00:00 < -:--:-- , ? it/s ]
INFO     Updated watchlist in 2.5 seconds                                                                                 
INFO     Completed full sync in 1 min 25.1 seconds                                                                        

```

Following the logs it seems like it marked E06 as watched in Trakt, which it shouldn't have but it isn't reflected on Trakt or Plex either way? So bogus log maybe? 

As expected, in Plex the episodes have been set as unwatched from E06 on and on Trakt all previous episodes have two plays, as expected. 👍
