### ISSUE TITLE
Crashing error upon running 'plextractsync' at console against a large library / plex collection.

### ISSUE THREAD

**Issue by ashepp** [Taxel/PlexTraktSync#982]
Crashing error upon running 'plextraktsync' from console with large library Plex server (50k+ movies and more).
I'm running on an Unraid Docker instance.

Signed up for a plex server and wanted a better way of highlighting / discovering movies and show by using Trakt lists. 
When I started the process yesterday I was making a few percent progress with an estimated 20hr time to index. 
When I checked this am the console seemed to be frozen. I reran the 'plextracktsync' command and I get the error every time. 

INFO     PlexTraktSync [0.20.4]                                                                                             
Sync Movie sections: [<PlexLibrarySection:movie:Movies>, <PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies - 4K DV>, <PlexLibrarySection:movie:Movies - Anime>, <PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies 3D>, <PlexLibrarySection:movie:Sports Movies>]
Sync Show sections: [<PlexLibrarySection:show:Courses>, <PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>, <PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows - 4K>, <PlexLibrarySection:show:TV Shows - 4K DV>, <PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
INFO     Downloaded List Trakt Watchlist                                                                                    
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/plextraktsync/cli.py", line 46, in cli
    sync()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 60, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 64, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/app/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/app/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/usr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/app/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: UserList.__new__() got an unexpected keyword argument 'type'
/app # plextraktsync
INFO     PlexTraktSync [0.20.4]                                                                                             
Sync Movie sections: [<PlexLibrarySection:movie:Movies>, <PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies - 4K DV>, <PlexLibrarySection:movie:Movies - Anime>, <PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies 3D>, <PlexLibrarySection:movie:Sports Movies>]
Sync Show sections: [<PlexLibrarySection:show:Courses>, <PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>, <PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows - 4K>, <PlexLibrarySection:show:TV Shows - 4K DV>, <PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
INFO     Downloaded List Trakt Watchlist                                                                                    
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/plextraktsync/cli.py", line 46, in cli
    sync()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 60, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 64, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/app/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/app/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/usr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/app/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: UserList.__new__() got an unexpected keyword argument 'type'
/app # plextraktsync
INFO     PlexTraktSync [0.20.4]                                                                                             
Sync Movie sections: [<PlexLibrarySection:movie:Movies>, <PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies - 4K DV>, <PlexLibrarySection:movie:Movies - Anime>, <PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies 3D>, <PlexLibrarySection:movie:Sports Movies>]
Sync Show sections: [<PlexLibrarySection:show:Courses>, <PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>, <PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows - 4K>, <PlexLibrarySection:show:TV Shows - 4K DV>, <PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
INFO     Downloaded List Trakt Watchlist                                                                                    
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/plextraktsync/cli.py", line 46, in cli
    sync()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 60, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 64, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/app/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/app/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/usr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/app/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: UserList.__new__() got an unexpected keyword argument 'type'
/app #

**Comment by twolaw** [comment]
You need to use bug report template.
You didn't check for identical issue #941
